Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\6_oMSS_fifile\oMSS_fifile.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\6_oMSS_fifile\oMSS_fifile.tel', line 2 
   Variable 'UNIT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\6_oMSS_fifile\oMSS_fifile.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
fifile
##########
# fifile #
##########
00400        DATA_SERV_14400             ACTIVATED   
00549        NITZ_IN_USE                 ACTIVATED   
00555        LCS_SUPPORTED               ACTIVATED   
00576        GPRS_V2_IN_USE              ACTIVATED   
00674        INTER_SYSTEM_HO_IN_USE      ACTIVATED   
00761        OVERLAY_MSC_SSP             ACTIVATED   
00848        ANN_FOR_GREY_LIST           ACTIVATED   
00853        SEL_RINGB_TONE_IN_USE       ACTIVATED   
01001        SEND_BW_ISDN_BCIE_TO_CH     ACTIVATED   
01044        SRBT_PREV_IN_CDR            ACTIVATED   
01119        PARALLEL_RAB_ASSIGNMENT     ACTIVATED   
01219        MSC_VOIP_TCP_SUPP           ACTIVATED   
01320        MSC_SIP_TUNNELING_SUPP      ACTIVATED   
01321        MSC_MGCF_SUPPORT            ACTIVATED   
01354        DX_SNTP_CLIENT              ACTIVATED   
01355        DX_SNTP_SRVR_AND_CLIENT     ACTIVATED   
01399        SIP_OPTIONS_PING_SUPP       ACTIVATED   
01414        SIP_MGCF_CT_UNATT_SUPP      ACTIVATED   
01478        ADD_PSAP_TO_SLR             ACTIVATED   
01548        EMLPP_NO_CHECK              ACTIVATED   
01559        SIP_TRUNK_GROUP_SUPP        ACTIVATED   
01651        NNSF_IN_MGW                 ACTIVATED   
02308        NTP                         ACTIVATED   
00004        H324_ALLWD_FOR_OP           ACTIVATED   
00005        BIT_T_DETECTION             ACTIVATED   
00006        T_3G_DATA_CALL              ACTIVATED   
00007        NT_3G_DATA_CALL             ACTIVATED   
00008        T_3G_DATA_CALL_NO_IWF       ACTIVATED   
00000        MSC_SERVER_SUPPORTED        ACTIVATED   
00001        MSS_TRFO_CAPAB_TRUE         ACTIVATED   
00000        PW_POLICY_FEATURE           ACTIVATED   
00006        HTTPS_WEBGUI_INTERFACE      ACTIVATED   
00007        HTTPS_XOH_INTERFACES        ACTIVATED   
00009        PW_POLICY_HCOUNT_FPWL       ACTIVATED   
Existen 34 Features activados
FIN!!!!