Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\97_oMSS_scp_call_control_parameters\oMSS_scp_call_control_parameters.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\97_oMSS_scp_call_control_parameters\oMSS_scp_call_control_parameters.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\97_oMSS_scp_call_control_parameters\oMSS_scp_call_control_parameters.tel', line 2 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\97_oMSS_scp_call_control_parameters\oMSS_scp_call_control_parameters.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\97_oMSS_scp_call_control_parameters\oMSS_scp_call_control_parameters.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Already connected
############
# MSSARA02 #
############
###############################
# scp_call_control_parameters #
###############################
FIN!!!!