Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\10_oMSS_network_and_ne_specific_numbers\oMSS_network_and_ne_specific_numbers.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
network_and_ne_specific_numbers
###################################
# network_and_ne_specific_numbers #
###################################
FIN!!!!