Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_FUNCIONES_BASE\oMSS_Verificar_Acceso_remoto.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

*1/59 MSS01ALK-D 192.168.131.33
device create ... OK
MSS01ALK-D: Connected
Sin acceso a MSS01ALK-D
MSS01ALK-D: Closing..
MSS01ALK-D: Disconnected
*2/59 MSS01BAR-D 192.168.32.65
device create ... OK
MSS01BAR-D: Connected
Sin acceso a MSS01BAR-D
MSS01BAR-D: Closing..
MSS01BAR-D: Disconnected
*3/59 MSS01BUC-D 192.168.32.134
device create ... OK
MSS01BUC-D: Connected
Sin acceso a MSS01BUC-D
MSS01BUC-D: Closing..
MSS01BUC-D: Disconnected
*4/59 MSS01CAL-D 192.168.32.208
device create ... OK
MSS01CAL-D: Connected
MSS01CAL-D: Connected
MSS01CAL-D: Disconnected
MSS01CAL-D: Disconnected
Sin acceso a MSS01CAL-D
MSS01CAL-D: Closing..
MSS01CAL-D: Disconnected
*5/59 MSS01ING-D 192.168.91.20
device create ... OK
MSS01ING-D: Connected
MSS01ING-D: Connected
MSS01ING-D: Closing..
MSS01ING-D: Disconnected
*6/59 MSS01PAS-D 192.168.140.11
device create ... OK
MSS01PAS-D: Connected
Sin acceso a MSS01PAS-D
MSS01PAS-D: Closing..
MSS01PAS-D: Disconnected
*7/59 MSS01PER-D 192.168.50.65
device create ... OK
MSS01PER-D: Connected
MSS01PER-D: Connected
MSS01PER-D: Closing..
MSS01PER-D: Disconnected
*8/59 MSS01SAI-D 192.168.237.134
device create ... OK
MSS01SAI-D: Connected
Sin acceso a MSS01SAI-D
MSS01SAI-D: Closing..
MSS01SAI-D: Disconnected
*9/59 MSS01SIN-D 192.168.141.6
device create ... OK
MSS01SIN-D: Connected
MSS01SIN-D: Connected
MSS01SIN-D: Closing..
MSS01SIN-D: Disconnected
*10/59 MSS01TOB-D 192.168.66.1
device create ... OK
MSS01TOB-D: Connected
MSS01TOB-D: Connected
MSS01TOB-D: Closing..
MSS01TOB-D: Disconnected
*11/59 MSS01VEN-D 192.168.133.6
device create ... OK
MSS01VEN-D: Connected
Sin acceso a MSS01VEN-D
MSS01VEN-D: Closing..
MSS01VEN-D: Disconnected
*12/59 MSS02ALK-D 192.168.131.64
device create ... OK
MSS02ALK-D: Connected
MSS02ALK-D: Connected
MSS02ALK-D: Closing..
MSS02ALK-D: Disconnected
*13/59 MSS02ARA-D 192.168.25.140
device create ... OK
MSS02ARA-D: Connected
Sin acceso a MSS02ARA-D
MSS02ARA-D: Closing..
MSS02ARA-D: Disconnected
*14/59 MSS02BUC-D 192.168.32.154
device create ... OK
MSS02BUC-D: Connected
MSS02BUC-D: Connected
MSS02BUC-D: Closing..
MSS02BUC-D: Disconnected
*15/59 MSS02CAL-D 192.168.32.1
device create ... OK
MSS02CAL-D: Connected
MSS02CAL-D: Connected
MSS02CAL-D: Closing..
MSS02CAL-D: Disconnected
*16/59 MSS02FON-D 192.168.63.6
device create ... OK
MSS02FON-D: Connected
Sin acceso a MSS02FON-D
MSS02FON-D: Closing..
MSS02FON-D: Disconnected
*17/59 MSS02MED-D 192.168.33.1
device create ... OK
MSS02MED-D: Connected
MSS02MED-D: Connected
MSS02MED-D: Closing..
MSS02MED-D: Disconnected
*18/59 MSS02PER-D 192.168.50.95
device create ... OK
MSS02PER-D: Connected
MSS02PER-D: Connected
MSS02PER-D: Closing..
MSS02PER-D: Disconnected
*19/59 MSS02SIN-D 192.168.141.38
device create ... OK
MSS02SIN-D: Connected
Sin acceso a MSS02SIN-D
MSS02SIN-D: Closing..
MSS02SIN-D: Disconnected
*20/59 MSS02TOB-D 192.168.66.22
device create ... OK
MSS02TOB-D: Connected
MSS02TOB-D: Connected
MSS02TOB-D: Closing..
MSS02TOB-D: Disconnected
*21/59 MSS02VEN-D 192.168.133.56
device create ... OK
MSS02VEN-D: Connected
MSS02VEN-D: Connected
MSS02VEN-D: Closing..
MSS02VEN-D: Disconnected
*22/59 MSS03ARA-D 192.168.25.148
device create ... OK
MSS03ARA-D: Connected
MSS03ARA-D: Connected
MSS03ARA-D: Closing..
MSS03ARA-D: Disconnected
*23/59 MSS03BAR-D 192.168.32.83
device create ... OK
MSS03BAR-D: Connected
MSS03BAR-D: Connected
MSS03BAR-D: Closing..
MSS03BAR-D: Disconnected
*24/59 MSS03BUC-D 192.168.34.49
device create ... OK
MSS03BUC-D: Connected
Sin acceso a MSS03BUC-D
MSS03BUC-D: Closing..
MSS03BUC-D: Disconnected
*25/59 MSS03CAL-D 192.168.32.33
device create ... OK
MSS03CAL-D: Connected
MSS03CAL-D: Connected
MSS03CAL-D: Closing..
MSS03CAL-D: Disconnected
*26/59 MSS03MED-D 192.168.33.28
device create ... OK
MSS03MED-D: Connected
MSS03MED-D: Connected
MSS03MED-D: Closing..
MSS03MED-D: Disconnected
*27/59 MSS03PER-D 192.168.223.1
device create ... OK
MSS03PER-D: Connected
Sin acceso a MSS03PER-D
MSS03PER-D: Closing..
MSS03PER-D: Disconnected
*28/59 MSS03PRA-D 192.168.33.163
device create ... OK
MSS03PRA-D: Connected
MSS03PRA-D: Connected
MSS03PRA-D: Closing..
MSS03PRA-D: Disconnected
*29/59 MSS03VEN-D 192.168.133.117
device create ... OK
MSS03VEN-D: Connected
MSS03VEN-D: Connected
MSS03VEN-D: Closing..
MSS03VEN-D: Disconnected
*30/59 MSS04ARA-D 192.168.49.29
device create ... OK
MSS04ARA-D: Connected
Sin acceso a MSS04ARA-D
MSS04ARA-D: Closing..
MSS04ARA-D: Disconnected
*31/59 MSS04BAR-D 192.168.93.6
device create ... OK
MSS04BAR-D: Connected
Sin acceso a MSS04BAR-D
MSS04BAR-D: Closing..
MSS04BAR-D: Disconnected
*32/59 MSS04CAL-D 192.168.32.49
device create ... OK
MSS04CAL-D: Connected
MSS04CAL-D: Connected
MSS04CAL-D: Closing..
MSS04CAL-D: Disconnected
*33/59 MSS04MED-D 192.168.59.31
device create ... OK
MSS04MED-D: Connected
Sin acceso a MSS04MED-D
MSS04MED-D: Closing..
MSS04MED-D: Disconnected
*34/59 MSS04VEN-D 192.168.133.146
device create ... OK
MSS04VEN-D: Connected
MSS04VEN-D: Connected
MSS04VEN-D: Closing..
MSS04VEN-D: Disconnected
*35/59 MSS05ARA-D 192.168.49.113
device create ... OK
MSS05ARA-D: Connected
MSS05ARA-D: Connected
MSS05ARA-D: Closing..
MSS05ARA-D: Disconnected
*36/59 MSS05MED-D 192.168.59.121
device create ... OK
MSS05MED-D: Connected
MSS05MED-D: Connected
MSS05MED-D: Closing..
MSS05MED-D: Disconnected
*37/59 MSS05VEN-D 192.168.236.75
device create ... OK
MSS05VEN-D: Connected
MSS05VEN-D: Connected
MSS05VEN-D: Closing..
MSS05VEN-D: Disconnected
*38/59 MSS06ARA-D 192.168.55.1
device create ... OK
MSS06ARA-D: Connected
MSS06ARA-D: Connected
MSS06ARA-D: Closing..
MSS06ARA-D: Disconnected
*39/59 MSS06MED-D 192.168.59.165
device create ... OK
MSS06MED-D: Connected
Sin acceso a MSS06MED-D
MSS06MED-D: Closing..
MSS06MED-D: Disconnected
*40/59 MSS06VEN-D 10.58.0.1
device create ... OK
MSS06VEN-D: Connected
MSS06VEN-D: Connected
MSS06VEN-D: Closing..
MSS06VEN-D: Disconnected
*41/59 MSS07ARA-D 192.168.55.55
device create ... OK
MSS07ARA-D: Connected
MSS07ARA-D: Connected
MSS07ARA-D: Closing..
MSS07ARA-D: Disconnected
*42/59 MSS07VEN-D 10.58.0.17
device create ... OK
MSS07VEN-D: Connected
MSS07VEN-D: Connected
MSS07VEN-D: Closing..
MSS07VEN-D: Disconnected
*43/59 MSSALK01-D 10.58.40.33
device create ... OK
MSSALK01-D: Connected
MSSALK01-D: Connected
MSSALK01-D: Closing..
MSSALK01-D: Disconnected
*44/59 MSSALK02-D 10.70.12.193
device create ... OK
MSSALK02-D: Connected
MSSALK02-D: Connected
MSSALK02-D: Closing..
MSSALK02-D: Disconnected
*45/59 MSSARA01-D 10.58.12.1
device create ... OK
MSSARA01-D: Connected
MSSARA01-D: Connected
MSSARA01-D: Closing..
MSSARA01-D: Disconnected
*46/59 MSSBUC01-D 10.58.48.66
device create ... OK
MSSBUC01-D: Connected
MSSBUC01-D: Connected
MSSBUC01-D: Closing..
MSSBUC01-D: Disconnected
*47/59 MSSING01-D 10.58.44.82
device create ... OK
MSSING01-D: Connected
MSSING01-D: Connected
MSSING01-D: Closing..
MSSING01-D: Disconnected
*48/59 MSSMAR01-D 10.58.96.1
device create ... OK
MSSMAR01-D: Connected
MSSMAR01-D: Connected
MSSMAR01-D: Closing..
MSSMAR01-D: Disconnected
*49/59 MSSMGA01-D 10.58.92.33
device create ... OK
MSSMGA01-D: Connected
MSSMGA01-D: Connected
MSSMGA01-D: Closing..
MSSMGA01-D: Disconnected
*50/59 MSSPER01-D 10.58.60.49
device create ... OK
MSSPER01-D: Connected
MSSPER01-D: Connected
MSSPER01-D: Closing..
MSSPER01-D: Disconnected
*51/59 MSSTRI01-D 10.58.89.49
device create ... OK
MSSTRI01-D: Connected
MSSTRI01-D: Connected
MSSTRI01-D: Closing..
MSSTRI01-D: Disconnected
*52/59 MSSTRI02-D 10.67.65.193
device create ... OK
MSSTRI02-D: Connected
MSSTRI02-D: Connected
MSSTRI02-D: Closing..
MSSTRI02-D: Disconnected
*53/59 MSSTRI03-D 10.67.145.1
device create ... OK
MSSTRI03-D: Connected
MSSTRI03-D: Connected
MSSTRI03-D: Closing..
MSSTRI03-D: Disconnected
*54/59 MSSVEN01-D 10.58.0.113
device create ... OK
MSSVEN01-D: Connected
MSSVEN01-D: Connected
MSSVEN01-D: Closing..
MSSVEN01-D: Disconnected
*55/59 MSSMGA02-D 10.58.92.194
device create ... OK
MSSMGA02-D: Connected
MSSMGA02-D: Connected
MSSMGA02-D: Closing..
MSSMGA02-D: Disconnected
*56/59 MSS01CAR-D 192.168.32.208
device create ... OK
MSS01CAR-D: Connected
MSS01CAR-D: Connected
MSS01CAR-D: Disconnected
MSS01CAR-D: Disconnected
Sin acceso a MSS01CAR-D
MSS01CAR-D: Closing..
MSS01CAR-D: Disconnected
*57/59 MSSARA02-D 10.66.67.193
device create ... OK
MSSARA02-D: Connected
MSSARA02-D: Connected
MSSARA02-D: Disconnected
MSSARA02-D: Disconnected
Sin acceso a MSSARA02-D
MSSARA02-D: Closing..
MSSARA02-D: Disconnected
*58/59 MSSVEN02-D 10.66.27.65
device create ... OK
MSSVEN02-D: Connected
MSSVEN02-D: Connected
MSSVEN02-D: Disconnected
MSSVEN02-D: Disconnected
Sin acceso a MSSVEN02-D
MSSVEN02-D: Closing..
MSSVEN02-D: Disconnected
*59/59 MSSING02-D 10.68.46.129
device create ... OK
MSSING02-D: Connected
MSSING02-D: Connected
MSSING02-D: Disconnected
MSSING02-D: Disconnected
Sin acceso a MSSING02-D
MSSING02-D: Closing..
MSSING02-D: Disconnected
*1/59 MSS01ALK-D 192.168.131.33 NOK
*2/59 MSS01BAR-D 192.168.32.65 NOK
*3/59 MSS01BUC-D 192.168.32.134 NOK
*4/59 MSS01CAL-D 192.168.32.208 NOK
*5/59 MSS01ING-D 192.168.91.20 OK
*6/59 MSS01PAS-D 192.168.140.11 NOK
*7/59 MSS01PER-D 192.168.50.65 OK
*8/59 MSS01SAI-D 192.168.237.134 NOK
*9/59 MSS01SIN-D 192.168.141.6 OK
*10/59 MSS01TOB-D 192.168.66.1 OK
*11/59 MSS01VEN-D 192.168.133.6 NOK
*12/59 MSS02ALK-D 192.168.131.64 OK
*13/59 MSS02ARA-D 192.168.25.140 NOK
*14/59 MSS02BUC-D 192.168.32.154 OK
*15/59 MSS02CAL-D 192.168.32.1 OK
*16/59 MSS02FON-D 192.168.63.6 NOK
*17/59 MSS02MED-D 192.168.33.1 OK
*18/59 MSS02PER-D 192.168.50.95 OK
*19/59 MSS02SIN-D 192.168.141.38 NOK
*20/59 MSS02TOB-D 192.168.66.22 OK
*21/59 MSS02VEN-D 192.168.133.56 OK
*22/59 MSS03ARA-D 192.168.25.148 OK
*23/59 MSS03BAR-D 192.168.32.83 OK
*24/59 MSS03BUC-D 192.168.34.49 NOK
*25/59 MSS03CAL-D 192.168.32.33 OK
*26/59 MSS03MED-D 192.168.33.28 OK
*27/59 MSS03PER-D 192.168.223.1 NOK
*28/59 MSS03PRA-D 192.168.33.163 OK
*29/59 MSS03VEN-D 192.168.133.117 OK
*30/59 MSS04ARA-D 192.168.49.29 NOK
*31/59 MSS04BAR-D 192.168.93.6 NOK
*32/59 MSS04CAL-D 192.168.32.49 OK
*33/59 MSS04MED-D 192.168.59.31 NOK
*34/59 MSS04VEN-D 192.168.133.146 OK
*35/59 MSS05ARA-D 192.168.49.113 OK
*36/59 MSS05MED-D 192.168.59.121 OK
*37/59 MSS05VEN-D 192.168.236.75 OK
*38/59 MSS06ARA-D 192.168.55.1 OK
*39/59 MSS06MED-D 192.168.59.165 NOK
*40/59 MSS06VEN-D 10.58.0.1 OK
*41/59 MSS07ARA-D 192.168.55.55 OK
*42/59 MSS07VEN-D 10.58.0.17 OK
*43/59 MSSALK01-D 10.58.40.33 OK
*44/59 MSSALK02-D 10.70.12.193 OK
*45/59 MSSARA01-D 10.58.12.1 OK
*46/59 MSSBUC01-D 10.58.48.66 OK
*47/59 MSSING01-D 10.58.44.82 OK
*48/59 MSSMAR01-D 10.58.96.1 OK
*49/59 MSSMGA01-D 10.58.92.33 OK
*50/59 MSSPER01-D 10.58.60.49 OK
*51/59 MSSTRI01-D 10.58.89.49 OK
*52/59 MSSTRI02-D 10.67.65.193 OK
*53/59 MSSTRI03-D 10.67.145.1 OK
*54/59 MSSVEN01-D 10.58.0.113 OK
*55/59 MSSMGA02-D 10.58.92.194 OK
*56/59 MSS01CAR-D 192.168.32.208 NOK
*57/59 MSSARA02-D 10.66.67.193 NOK
*58/59 MSSVEN02-D 10.66.27.65 NOK
*59/59 MSSING02-D 10.68.46.129 NOK
