Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_FUNCIONES_BASE\oMSS_CHECK_3G_RNC_STATUS_NODEB.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Connected
MSSVEN02: Connected

############
# MSSVEN02 #
############

#########################
# ASSOCIATIONS SET NAME #
#########################
MGVE4NA0                          0   M3UA        CLIENT
MGVE4NA1                          1   M3UA        CLIENT
STPVE                             2   M3UA        CLIENT
STPBU                             3   M3UA        CLIENT
RVE09                             4   M3UA        SERVER
BTO11                             5   M3UA        SERVER
RNBU4                             6   M3UA        SERVER


######################
# ASSOCIATIONS STATE #
######################
      0    IPDU-3    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.129                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.129                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.129/27                            
        SECONDARY DEST. ADDRESS  . : 10.63.97.89/30                             
      1    IPDU-4    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.130                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.130                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.34/27                             
        SECONDARY DEST. ADDRESS  . : 10.63.97.93/30                             
      2    IPDU-5    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.131                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.131                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.35/27                             
        SECONDARY DEST. ADDRESS  . : 10.63.96.131/27                            
      3    IPDU-6    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.132                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.132                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.36/27                             
        SECONDARY DEST. ADDRESS  . : 10.63.96.132/27                            
      4    IPDU-7    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.133                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.133                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.133/27                            
        SECONDARY DEST. ADDRESS  . : 10.63.97.113/30                            
      5    IPDU-10   ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.134                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.134                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.38/27                             
        SECONDARY DEST. ADDRESS  . : 10.63.97.117/30                            
      6    IPDU-11   ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.135                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.135                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.135/27                            
        SECONDARY DEST. ADDRESS  . : 10.63.96.39/27                             
      7    IPDU-8    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.119.136                              
        SOURCE ADDRESS 2 . . . . . : 10.41.119.136                              
        PRIMARY DEST. ADDRESS  . . : 10.63.96.40/27                             
        SECONDARY DEST. ADDRESS  . : 10.63.96.136/27                            

*1/8- ASSC_NAME: RNBU4 ID: 0 UNIT IPDU-3 OPIP 10.40.119.129 OSIP 10.41.119.129 DOPIP 10.63.96.129 DOSIP 10.63.97.89
 -->> # PING PRIMARY OPIP 10.40.119.129 OSIP 10.63.96.129 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.129 OSIP 10.63.97.89 FAIL

*2/8- ASSC_NAME: RNBU4 ID: 1 UNIT IPDU-4 OPIP 10.40.119.130 OSIP 10.41.119.130 DOPIP 10.63.96.34 DOSIP 10.63.97.93
 -->> # PING PRIMARY OPIP 10.40.119.130 OSIP 10.63.96.34 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.130 OSIP 10.63.97.93 FAIL

*3/8- ASSC_NAME: RNBU4 ID: 2 UNIT IPDU-5 OPIP 10.40.119.131 OSIP 10.41.119.131 DOPIP 10.63.96.35 DOSIP 10.63.96.131
 -->> # PING PRIMARY OPIP 10.40.119.131 OSIP 10.63.96.35 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.131 OSIP 10.63.96.131 FAIL

*4/8- ASSC_NAME: RNBU4 ID: 3 UNIT IPDU-6 OPIP 10.40.119.132 OSIP 10.41.119.132 DOPIP 10.63.96.36 DOSIP 10.63.96.132
 -->> # PING PRIMARY OPIP 10.40.119.132 OSIP 10.63.96.36 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.132 OSIP 10.63.96.132 FAIL

*5/8- ASSC_NAME: RNBU4 ID: 4 UNIT IPDU-7 OPIP 10.40.119.133 OSIP 10.41.119.133 DOPIP 10.63.96.133 DOSIP 10.63.97.113
 -->> # PING PRIMARY OPIP 10.40.119.133 OSIP 10.63.96.133 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.133 OSIP 10.63.97.113 FAIL

*6/8- ASSC_NAME: RNBU4 ID: 5 UNIT IPDU-10 OPIP 10.40.119.134 OSIP 10.41.119.134 DOPIP 10.63.96.38 DOSIP 10.63.97.117
 -->> # PING PRIMARY OPIP 10.40.119.134 OSIP 10.63.96.38 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.134 OSIP 10.63.97.117 FAIL

*7/8- ASSC_NAME: RNBU4 ID: 6 UNIT IPDU-11 OPIP 10.40.119.135 OSIP 10.41.119.135 DOPIP 10.63.96.135 DOSIP 10.63.96.39
 -->> # PING PRIMARY OPIP 10.40.119.135 OSIP 10.63.96.135 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.135 OSIP 10.63.96.39 FAIL

*8/8- ASSC_NAME: RNBU4 ID: 7 UNIT IPDU-8 OPIP 10.40.119.136 OSIP 10.41.119.136 DOPIP 10.63.96.40 DOSIP 10.63.96.136
 -->> # PING PRIMARY OPIP 10.40.119.136 OSIP 10.63.96.40 FAIL
 -->> # PING SECONDARY OPIP 10.41.119.136 OSIP 10.63.96.136 FAIL


############################
# SIGNALLING LINK SET DATA #
############################
ZNSI:NA1,3DC9;

LOADING PROGRAM VERSION 8.19-0

MSS       MSSVEN02                  2023-09-18  08:28:05

INTERROGATING SIGNALLING LINK SET DATA

                                                                   LS    IP
NET SP CODE H/D        LINK SET              ASSOCIATION SET       STATE LINK
--- ------------------ --------------------- --------------------- ----- ----
NA1   3DC9/15817         71 RNBU4               6 RNBU4             UA      4
                                       LINK TEST NOT ALLOWED


COMMAND EXECUTED


SIGNALLING LINK SET DATA HANDLING COMMAND <NS_>
<  

#############################
# SIGNALLING LINK SET STATE #
#############################
ZNLI;

LOADING PROGRAM VERSION 8.8-0

MSS       MSSVEN02                  2023-09-18  08:28:06

SIGNALLING LINK STATES

M3UA BASED LINKS
================
 M3UA                            ASSOCIATION  LINK
 LINK      LINK SET              SET          STATE
 ----      -------------------   ----------   -----
    0      16 MGVE4                 0         AV-EX     
    1      17 MGVE4                 1         AV-EX     
    2      18 STPVE                 2         AV-EX     
    3      19 STPBU                 3         AV-EX     
    4      71 RNBU4                 6         UA-AD     
   63      35 RVE09                 4         AV-EX     
   64      43 BTO11                 5         AV-EX     

COMMAND EXECUTED


SIGNALLING LINK STATE HANDLING COMMAND <NL_>
<  ZNEL;

LOADING PROGRAM VERSION 8.49-0

MSS       MSSVEN02                  2023-09-18  08:28:07

SIGNALLING LINK STATES

M3UA BASED LINKS
================
 M3UA                          ASSOCIATION  LINK
 LINK  LINK SET                SET          STATE
 ====  =====================   ===========  ======
    0    16 MGVE4                0          AV-EX     
    1    17 MGVE4                1          AV-EX     
    2    18 STPVE                2          AV-EX     
    3    19 STPBU                3          AV-EX     
    4    71 RNBU4                6          UA-AD     
   63    35 RVE09                4          AV-EX     
   64    43 BTO11                5          AV-EX     

COMMAND EXECUTED


SIGNALLING NETWORK STATE INTERROGATION COMMAND <NE_>
<  

#########################
# SIGNALLING POINT DATA #
#########################
ZNRI:NA1,3DC9;

LOADING PROGRAM VERSION 8.38-0

MSS       MSSVEN02                  2023-09-18  08:28:08

INTERROGATING SIGNALLING POINT DATA

NET  SP CODE H/D         NAME              RS STATE  PAR SET
---  ------------------  ----------------  --------  -------
NA1    3DC9/15817        RNBU4               UA        6
LOAD SHARING BETWEEN SIGNALLING ROUTES DENIED
SCREENING GROUPS: AASG 0, ADSG 0, OOSG 0, ODSG 0

ROUTES: SP CODE H/D         NAME              STATE   PRIO
        ------------------  ----------------  ------  ----
          3DC9/15817        RNBU4             UA-AD     7    



COMMAND EXECUTED


SIGNALLING ROUTE SET DATA HANDLING COMMAND <NR_>
<  

##########################
# SIGNALLING ROUTE STATE #
##########################
ZNVI:NA1,3DC9;

LOADING PROGRAM VERSION 8.2-0

MSS       MSSVEN02                  2023-09-18  08:28:09

SIGNALLING ROUTE STATES

DESTINATION:           SP               RS     ROUTES:            
NET SP CODE H/D        NAME             STATE  SP CODE H/D        STATE   PRIO
--- ------------------ ---------------- -----  ------------------ ------- ----
NA1   3DC9/15817       RNBU4             UA      3DC9/15817        UA-AD   7

COMMAND EXECUTED


SIGNALLING ROUTE STATE HANDLING COMMAND <NV_>
<  

##################################
# SCCP DATA OF SIGNALLING POINTS #
##################################
ZNFI:NA1,3DC9:A;

LOADING PROGRAM VERSION 8.8-0

MSS       MSSVEN02                  2023-09-18  08:28:10

SCCP STATES

DESTINATION:           SP                    
NET SP CODE H/D        NAME             ST RM
--- ------------------ ---------------- -- --
NA1   3DC9/15817       RNBU4            UA - 

           ROUTING:               SP                       PAR
           NET SP CODE H/D        NAME             STATE   SET
           --- ------------------ ---------------- ------- ---
           NA1   3DC9/15817       RNBU4            UA-INU    3 

                                                           PAR    
                      SUBSYSTEMS:  NO H/D  SS NAME STATE   SET SST
                      ===========  ------- ------- ------- --- ---
                                   01/001  SCMG    UA-INS      N 
                                   8E/142  RANAP   UA-INU    1 Y 


COMMAND EXECUTED


SCCP DATA HANDLING COMMAND <NF_>
<  ZNGI:NA1,3DC9:A;

LOADING PROGRAM VERSION 7.10-0

MSS       MSSVEN02                  2023-09-18  08:28:11

SCCP STATES

DESTINATION:             SP            
NET  SP CODE H/D         NAME             STATE RM
---  ------------------  ---------------- ----- --
NA1    3DC9/15817        RNBU4             UA   - 
          
          ROUTING:                 SP             
          NET  SP CODE H/D         NAME             STATE    
          ---  ------------------  ---------------- -------  
          NA1    3DC9/15817        RNBU4            UA-INU 

                      SUBSYSTEMS:  NO H/D   SS NAME  STATE
                      ===========  -------  -------  -------
                                   01/001   SCMG     UA-INS 
                                   8E/142   RANAP    UA-INU 


COMMAND EXECUTED


SCCP STATE HANDLING COMMAND <NG_>
<  ZNHI:NA1,3DC9:;

LOADING PROGRAM VERSION 7.7-0

MSS       MSSVEN02                  2023-09-18  08:28:12

SUBSYSTEM STATES

NETWORK: NA1   POINT H/D:   3DC9/15817          SP NAME: RNBU4           
============   =============================    =========================
DESTINATION:                ROUTING:                 SP
NO H/D  SS NAME  STATE  RM  NET  SP CODE H/D         NAME              STATE
------  -------  -----  --  ---  ------------------  ----------------  -------
01/001  SCMG      UA    -   NA1    3DC9/15817        RNBU4             UA-INS 

8E/142  RANAP     UA    -   NA1    3DC9/15817        RNBU4             UA-INU 


COMMAND EXECUTED


SCCP SUBSYSTEM STATE HANDLING COMMAND <NH_>
<  

#########################
# RADIO - Location Area #
#########################
LA    NAME :AUXLACDEF                   LAC     :65533
LA    NAME :LAC9902                     LAC     :09902
LA    NAME :LAC0538                     LAC     :00538

#############
# RNC - UPD #
#############
ZJFL;

LOADING PROGRAM VERSION 10.34-0

NAME             ID   BNCC
----             --   ----
UPDMGWALLIPV4   0000  IPV4
UPDIP4RNC04BUC  0001  IPV4
UPDRNC09VEN     0300  IPV4
UPDMCBSC11TOB   0301  IPV4

COMMAND EXECUTED


USER PLANE TOPOLOGY DATA HANDLING COMMAND <JF_>
<    MGVE4MSVE2V00     0           YES    1    NO    YES 
  MGVE4MSVE2V01     1           YES    1    NO    YES 
  MGVE4MSVE2V02     2           YES    1    NO    YES 
  MGVE4MSVE2V03     3           YES    1    NO    YES 
  MGVE4MSVE2V04     4           YES    1    NO    YES 
  MGVE4MSVE2V05     5           YES    1    NO    YES 


#######
# RNC #
#######

#########
# NodeB #
#########
*1/4- AUXSACDEF AUXLACDEF 65534 LOCKED -
*2/4- BOU56517 LAC9902 56517 LOCKED -
*3/4- BOU60849 LAC9902 60849 UNLOCKED -
*4/4- BOU60850 LAC9902 60850 UNLOCKED -

Existen 31 SA UNLOCKED
FIN DE MACRO

FIN!!!!MSSVEN02: Disconnected
