Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_PING_DESTINATIONS\oMSS_PING_DESTINATIONS.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSARA02: Already connected
############
# MSSARA02 #
############
 IPDU-0     0070 WO-EX   -                            
 IPDU-1     0071 WO-EX   -                            
 IPDU-3     0073 WO-EX  GRP2                          
 IPDU-4     0074 WO-EX  GRP2                          
 IPDU-5     0075 WO-EX  GRP2                          
 IPDU-6     0076 WO-EX  GRP2                          
 IPDU-7     0077 WO-EX  GRP2                          
 IPDU-8     0078 WO-EX  GRP2                          
 IPDU-9     0079 WO-EX  GRP2                          
 IPDU-10    007A WO-EX  GRP2                          
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>

FIN!!!