Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_PING_FISCALIA_FROM_OMU_STU\oMSS_PING_FISCALIA_FROM_OMU_STU.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSTRI02: Already connected
############
# MSSTRI02 #
############
 OMU-0      0000 WO-EX   -                            
   DEFAULT GW    : 10.67.65.222                           
  EL6        UP    1500  L        10.67.65.217/29                              
 STU-0      0002 WO-EX   -                            
  EL4        UP    1500  L        10.67.65.218/29                              
   DEFAULT GW    : 10.67.65.214                           
1 packets transmitted, 1 packets received, 0 packet loss

FIN!!!