Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\72_oMSS_Meas_ObjectList\oMSS_Meas_ObjectList_.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
###################
# Meas_ObjectList #
###################
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS135 OID:135
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS180 OID:180
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS182 OID:182
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS184 OID:184
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS185 OID:185
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS186 OID:186
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS188 OID:188
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS18C OID:188
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS191 OID:191
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS233 OID:233
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS183 OID:183
*1/11_ MEAS AMEAS135 OID 135
*2/11_ MEAS AMEAS180 OID 180
*3/11_ MEAS AMEAS182 OID 182
*4/11_ MEAS AMEAS184 OID 184
*5/11_ MEAS AMEAS185 OID 185
*6/11_ MEAS AMEAS186 OID 186
*7/11_ MEAS AMEAS188 OID 188
*8/11_ MEAS AMEAS18C OID 188
*9/11_ MEAS AMEAS191 OID 191
*10/11_ MEAS AMEAS233 OID 233
*11/11_ MEAS AMEAS183 OID 183
FIN!!!!