Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 2 
   Variable 'filename2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 2 
   Variable 'ASOC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 2 
   Variable 'ASOC_NAME' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 2 
   Variable 'FEBU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'CHU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'CGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'NCGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'TCGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'TDIR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'NBCRCT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'STATE' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'CKTNOWO' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 3 
   Variable 'COMCAL' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 4 
   Variable 'Opcion' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'handle2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'a' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'b' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'PORC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'CKTOOS' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'm1' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 5 
   Variable 'm2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 24 
   Variable 'PARAMETER_CLASS' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 24 
   Variable 'PARAMETER_NAME_STATUS' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_TX_PRFILE_CHECK\oMSS_Cloud_PRFILE.tel', line 82 
   Variable 'n' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
PARAMETER CLASS: 0      ANNOUNCEMENT_DEVICE         
PARAMETER CLASS: 1      CHARGING                    
00007        CHRG_RATE_CHK_PERIOD        1C20      NO  
00101        NBR_OF_DIFFERENT_FORMS      0001      NO  
00102        NBR_OF_FORMAT_TYPES         0032      NO  
PARAMETER CLASS: 2      SYSTEM_FUNCT_CONFIGUR       
00009        DPABX_CHARGING              00FF      NO  
00035        PRIMARY_RATE_INTERFACE      00FF      NO  
00266        ANALYSIS_MAX_COUNT          0064      NO  
00696        MULTICALL_NBRSN             0002      NO  
01654        LONG_CICS_FOR_TUP           0000      NO  
PARAMETER CLASS: 3      SUBSCRIBER_FACILITIES       
PARAMETER CLASS: 4      THREE_PARTY_FACILITIES      
PARAMETER CLASS: 5      OPERATOR_CALL               
PARAMETER CLASS: 6      CALL_TECHNIC_TIM_LIMI       
PARAMETER CLASS: 7      CALL_CONTROL                
00047        MAX_ATB_SUBANA_NBR          0032      NO  
00076        SCCP_CD_NUMB_FORMAT         0001      NO  
PARAMETER CLASS: 8      ACCESS_SERVER               
PARAMETER CLASS: 9      SYSTEM_SUPERVISION          
00010        CRC4_TRH_FOR_DEGRAD_MIN     007B      NO  
00011        CRC4_TRH_FOR_ERRORE_SEC     0367      NO  
PARAMETER CLASS: 10     IMPLEMENTA_OF_CALL_CTRL     
00004        PCM_MAINT_ANNOUNCE_TL       03E8      NO  
PARAMETER CLASS: 11     SYSTEM_DIMENSIONING         
PARAMETER CLASS: 12     OVERLOAD                    
PARAMETER CLASS: 13     PRIORITY_CALLS              
00003        QUE_SEARCH_TI_OF_OUTCRC     000A      NO  
00007        QUE_SEA_TI_CODE_EQUIP       0006      NO  
PARAMETER CLASS: 14     INCOM_CALL_BARRING          
PARAMETER CLASS: 15     SUBSC_NBR_ANALYSIS          
PARAMETER CLASS: 16     ALARM_SYSTEM                
PARAMETER CLASS: 17     CALL_FORWARDING             
PARAMETER CLASS: 18     DX_SCP                      
PARAMETER CLASS: 19     WAKE_UP_FACILITY            
PARAMETER CLASS: 20     CARRIER_ACCESS_CODES        
PARAMETER CLASS: 21     COMPLETION_OF_CALL          
PARAMETER CLASS: 22     DX_RF_CODES                 
00003        SSCP_TRUNC_NUMBERS          0000      NO  
PARAMETER CLASS: 23     DN_SIGNAL                   
PARAMETER CLASS: 24     V5_INTERFACE                
PARAMETER CLASS: 25     DIGITAL_CROSS_CONNECT       
PARAMETER CLASS: 26     OWN_ADDR                    
PARAMETER CLASS: 27     EOS_ATTRIBUTES              
PARAMETER CLASS: 28     ROUTING_ATTRIBUTES          
PARAMETER CLASS: 29     AIF_ATTRIBUTES              
PARAMETER CLASS: 30     CHARGING_ATTRIBUTES         
PARAMETER CLASS: 31     SHORT_MESSAGE_SERVICE       
PARAMETER CLASS: 32     CM_ATTRIBUTE_CONTROL        
PARAMETER CLASS: 33     CM_ATTRIBUTES               
PARAMETER CLASS: 34     NTN_COMM_OPTIONS            
PARAMETER CLASS: 35     CALL_PARK                   
PARAMETER CLASS: 36     SUBSC_IDENTIFICATION        
PARAMETER CLASS: 37     RADIO_NW_CTRL_REL           
PARAMETER CLASS: 38     MML_COMMAND_LOG             
PARAMETER CLASS: 39     CHA_MODIFICATION            
PARAMETER CLASS: 40     ECT_PARAMETERS              
PARAMETER CLASS: 41     CAMEL_PARAMETERS            
PARAMETER CLASS: 42     QSIG_PARAMETERS             
PARAMETER CLASS: 43     IWF_CTRL_PARAMETER          
PARAMETER CLASS: 44     MML_SESSION                 
PARAMETER CLASS: 45     NTN_FEATURE_AND_ATTRI       
PARAMETER CLASS: 46     PCU_TELECOM_PARAMETERS      
PARAMETER CLASS: 47     V5_PSTN_MAPPING_PARAM       
PARAMETER CLASS: 48     V5_PSTN_MAPPING_PARAM_2     
PARAMETER CLASS: 49     GB_INTERFACE                
PARAMETER CLASS: 50     REPORT_FORMING              
PARAMETER CLASS: 51     AAL2_SIG_PARAMETERS         
PARAMETER CLASS: 52     SIP_SIGNALLING_PARAM        
PARAMETER CLASS: 53     MSC_SERVER_PARAMETERS       
PARAMETER CLASS: 54     TCPIP_PARAMETERS            
PARAMETER CLASS: 55     LCS_PARAMETERS              
PARAMETER CLASS: 56     STLOG_FACILITIES            
PARAMETER CLASS: 57     IIN_ATTRIBUTES              
PARAMETER CLASS: 58     OAM_SECURITY                
PARAMETER CLASS: 59     UMA_PARAMS                  
PARAMETER CLASS: 60     MANAGEMENT_PROTOCOLS        
PARAMETER CLASS: 61     IN_ATTRIBUTES               
PARAMETER CLASS: 62     OLCM                        
PARAMETER CLASS: 63     SIEMENS_INAP                
PARAMETER CLASS: 64     SERVICE_ATTRIBUTES          
PARAMETER CLASS: 66     WEB_SERVICE_ATTRIBUTES      
PARAMETER CLASS: 67     AUX_PARAMETERS              
PARAMETER CLASS: 68     GSM_RAILWAY                 
PARAMETER CLASS: 69     TROUBLESHOOTING             
FIN!!!!