Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'DIG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'NRD' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'SRD' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'SAD' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'RT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'NB' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'DST' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 3 
   Variable 'TON' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 4 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 4 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\67_oMSS_announcement_parameters\oMSS_announcement_parameters_.tel', line 4 
   Variable 'z' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Connected
MSSVEN02: Connected
############
# MSSVEN02 #
############
###########################
# announcement_parameters #
###########################
#######
# FIN #
#######
MSSVEN02: Disconnected
