Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 2 
   Variable 'filename2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 2 
   Variable 'ASOC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 2 
   Variable 'ASOC_NAME' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 2 
   Variable 'FEBU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'CHU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'CGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'NCGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'TCGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'TDIR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'NBCRCT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'STATE' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'CKTNOWO' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 3 
   Variable 'COMCAL' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'handle2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'a' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'b' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'PORC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'CKTOOS' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'm1' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_IP_Interface\oMSS_Cloud_IP_Interface_V2.tel', line 4 
   Variable 'm2' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Already connected
#######
# OMU #
#######
OMU 0
OMU 1
#######
# STU #
#######
STU 0
STU 1
#######
# CMU #
#######
CMU 0
CMU 1
#######
# CMM #
#######
CMM 0
CMM 1
########
# IPDU #
########
IPDU 0
IPDU 1
IPDU 2
IPDU 3
IPDU 4
IPDU 5
IPDU 6
IPDU 7
IPDU 8
IPDU 9
IPDU 10
IPDU 11
########
# GISU #
########
GISU 0
GISU 1
GISU 2
GISU 3
GISU 4
GISU 5
GISU 6
GISU 7
GISU 8
GISU 9
GISU 10
GISU 11
GISU 12
GISU 13
GISU 14
GISU 15
GISU 16
GISU 17
GISU 18
GISU 19
GISU 20
GISU 21
GISU 22
GISU 23
GISU 24
GISU 25
GISU 26
GISU 27
GISU 28
GISU 29
GISU 30
GISU 31
GISU 32
GISU 33
GISU 34
GISU 35
GISU 36
GISU 37
GISU 38
GISU 39
GISU 40
GISU 41
GISU 42
GISU 43
GISU 44
GISU 45
GISU 46
GISU 47
GISU 48
GISU 49
GISU 50
GISU 51
GISU 52
GISU 53
GISU 54
GISU 55
GISU 56
GISU 57
GISU 58
GISU 59
GISU 60
GISU 61
GISU 62
GISU 63
GISU 64
GISU 65
GISU 66
GISU 67
GISU 68
GISU 69
GISU 70
GISU 71
GISU 72
GISU 73
GISU 74
GISU 75
GISU 76
GISU 77
GISU 78
GISU 79
GISU 80
GISU 81
GISU 82
GISU 83
GISU 84
GISU 85
#######
# CHU #
#######
CHU 0-0
CHU 0-1
CHU 1-0
CHU 1-1
CHU 2-0
CHU 2-1
CHU 3-0
CHU 3-1
########
# VLRU #
########
VLRU 0-0
VLRU 0-1
VLRU 1-0
VLRU 1-1
VLRU 2-0
VLRU 2-1
VLRU 3-0
VLRU 3-1
VLRU 4-0
VLRU 4-1
VLRU 5-0
VLRU 5-1
VLRU 6-0
VLRU 6-1
VLRU 7-0
VLRU 7-1
VLRU 8-0
VLRU 8-1
VLRU 9-0
VLRU 9-1
VLRU 10-0
VLRU 10-1
VLRU 11-0
VLRU 11-1
VLRU 12-0
VLRU 12-1
VLRU 13-0
VLRU 13-1
VLRU 14-0
VLRU 14-1
VLRU 15-0
VLRU 15-1
VLRU 16-0
VLRU 16-1
VLRU 17-0
VLRU 17-1
VLRU 18-0
VLRU 18-1
VLRU 19-0
VLRU 19-1
FIN!!!!