Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\59_oMSS_eos_attribute_subanalysis\oMSS_eos_attribute_subanalysis.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\59_oMSS_eos_attribute_subanalysis\oMSS_eos_attribute_subanalysis.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\59_oMSS_eos_attribute_subanalysis\oMSS_eos_attribute_subanalysis.tel', line 2 
   Variable 'FLAG' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
#############################
# eos_attribute_subanalysis #
#############################
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
   CAUSECK 
   AIMSICK 
   AIMSICK1 
   AIMSICK2 
   AIMSICK4 
   AEMLPPCK 
   RIMCKCFU 
   RIMCKCFW 
   CDNCKCFN 
   NPSCK 
   ODCCK 
   NPSVIOCS 
   NPSCKROA 
   IGORCK 
   CBTYPECK 
   OBLIGATORY */
*1/16- SUB ANALYSIS CAUSECK
*2/16- SUB ANALYSIS AIMSICK
*3/16- SUB ANALYSIS AIMSICK1
*4/16- SUB ANALYSIS AIMSICK2
*5/16- SUB ANALYSIS AIMSICK4
*6/16- SUB ANALYSIS AEMLPPCK
*7/16- SUB ANALYSIS RIMCKCFU
*8/16- SUB ANALYSIS RIMCKCFW
*9/16- SUB ANALYSIS CDNCKCFN
*10/16- SUB ANALYSIS NPSCK
*11/16- SUB ANALYSIS ODCCK
*12/16- SUB ANALYSIS NPSVIOCS
*13/16- SUB ANALYSIS NPSCKROA
*14/16- SUB ANALYSIS IGORCK
*15/16- SUB ANALYSIS CBTYPECK

ZRQI:EOS:NAME=CAUSECK:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
2C                                            MTRRRES  : FINAL RESULT
271                                           AIMSICK1 : SUBANALYSIS
272                                           AIMSICK2 : SUBANALYSIS
274                                           AIMSICK4 : SUBANALYSIS
275                                           ANN275E  : FINAL RESULT
804                                           AEMLPPCK : SUBANALYSIS
100D                                          RIMCKCFU : SUBANALYSIS
100E                                          RIMCKCFU : SUBANALYSIS
100F                                          CDNCKCFN : SUBANALYSIS
1010                                          CDNCKCFN : SUBANALYSIS
1011                                          RIMCKCFW : SUBANALYSIS
1012                                          RIMCKCFW : SUBANALYSIS
1013                                          RIMCKCFW : SUBANALYSIS
1014                                          RIMCKCFW : SUBANALYSIS
102C                                          RIMCKCFW : SUBANALYSIS
102D                                          RIMCKCFW : SUBANALYSIS
102E                                          RIMCKCFW : SUBANALYSIS
102F                                          RIMCKCFW : SUBANALYSIS
1030                                          CBTYPECK : SUBANALYSIS
1035                                          RIMCKCFW : SUBANALYSIS
1036                                          RIMCKCFW : SUBANALYSIS
1037                                          RIMCKCFW : SUBANALYSIS
1038                                          RIMCKCFW : SUBANALYSIS
1039                                          RIMCKCFW : SUBANALYSIS
103A                                          RIMCKCFW : SUBANALYSIS
*SUB ANALYSIS CAUSECK tiene 27 tuplas

ZRQI:EOS:NAME=AIMSICK:;
DEFAULT RESULT:                               PORTADOS : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  PORTADOS : FINAL RESULT
7                                             TREEMVNO : FINAL RESULT
*SUB ANALYSIS AIMSICK tiene 3 tuplas

ZRQI:EOS:NAME=AIMSICK1:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
0                                             ANN271E  : FINAL RESULT
1                                             ANN271W  : FINAL RESULT
2                                             ANN271W  : FINAL RESULT
*SUB ANALYSIS AIMSICK1 tiene 5 tuplas

ZRQI:EOS:NAME=AIMSICK2:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
0                                             ANN272E  : FINAL RESULT
1                                             ANN272W  : FINAL RESULT
2                                             ANN272W  : FINAL RESULT
*SUB ANALYSIS AIMSICK2 tiene 5 tuplas

ZRQI:EOS:NAME=AIMSICK4:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
0                                             ANN274E  : FINAL RESULT
1                                             ANN274W  : FINAL RESULT
2                                             ANN274W  : FINAL RESULT
*SUB ANALYSIS AIMSICK4 tiene 5 tuplas

ZRQI:EOS:NAME=AEMLPPCK:;
DEFAULT RESULT:                               NOPRICAL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  NOPRICAL : FINAL RESULT
EMLPP PRIORITY LEVEL A                        PRICALL  : FINAL RESULT
EMLPP PRIORITY LEVEL B                        PRICALL  : FINAL RESULT
EMLPP PRIORITY LEVEL 0                        PRICALL  : FINAL RESULT
EMLPP PRIORITY LEVEL 1                        PRICALL  : FINAL RESULT
*SUB ANALYSIS AEMLPPCK tiene 6 tuplas

ZRQI:EOS:NAME=RIMCKCFU:;
DEFAULT RESULT:                               CFROAM   : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  CFROAM   : FINAL RESULT
0                                             CFSTOPCO : FINAL RESULT
1                                             CFSTOPCO : FINAL RESULT
2                                             CFSTOPCO : FINAL RESULT
11                                            CFSTOPCO : FINAL RESULT
12                                            CFSTOPCO : FINAL RESULT
14                                            CFSTOPCO : FINAL RESULT
16                                            CFSTOPCO : FINAL RESULT
*SUB ANALYSIS RIMCKCFU tiene 9 tuplas

ZRQI:EOS:NAME=RIMCKCFW:;
DEFAULT RESULT:                               CFROAM   : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  CFROAM   : FINAL RESULT
0                                             CFRN009  : FINAL RESULT
1                                             CFRN009  : FINAL RESULT
2                                             CFRN009  : FINAL RESULT
11                                            CFAVANT  : FINAL RESULT
12                                            CFMOVIST : FINAL RESULT
14                                            CFTIGO   : FINAL RESULT
16                                            CFWOM    : FINAL RESULT
*SUB ANALYSIS RIMCKCFW tiene 9 tuplas

ZRQI:EOS:NAME=CDNCKCFN:;
DEFAULT RESULT:                               RIMCKCFW : SUBANALYSIS
RESULT OF UNKNOWN ATTRIBUTE:                  RIMCKCFW : SUBANALYSIS
INT    573112984935                           TREE40   : FINAL RESULT
INT    573112998001                           TREE40   : FINAL RESULT
INT    573112998002                           TREE40   : FINAL RESULT
INT    573112998003                           TREE40   : FINAL RESULT
INT    573112998004                           TREE40   : FINAL RESULT
INT    573102159897                           TREE40   : FINAL RESULT
INT    573103154501                           TREE40   : FINAL RESULT
INT    573103154502                           TREE40   : FINAL RESULT
INT    573103804501                           TREE40   : FINAL RESULT
INT    573103804502                           TREE40   : FINAL RESULT
INT    573103804503                           TREE40   : FINAL RESULT
*SUB ANALYSIS CDNCKCFN tiene 13 tuplas

ZRQI:EOS:NAME=NPSCK:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
QUERY DONE NOT KNOWN TO BE PORTED             NATIVOS  : FINAL RESULT
QUERY DONE PORTED OUT                         PORTADOS : FINAL RESULT
QUERY DONE PORTED BETWEEN FOREIGN NETS        AIMSICK  : SUBANALYSIS
*SUB ANALYSIS NPSCK tiene 5 tuplas

ZRQI:EOS:NAME=ODCCK:;
DEFAULT RESULT:                               NPSCK    : SUBANALYSIS
RESULT OF UNKNOWN ATTRIBUTE:                  NPSCK    : SUBANALYSIS
43                                            STOPCALL : FINAL RESULT
50                                            MIXTOS50 : FINAL RESULT
60                                            MIXTOS60 : FINAL RESULT
70                                            NPSVIOCS : SUBANALYSIS
110                                           NPSCKROA : SUBANALYSIS
111                                           STOPCALL : FINAL RESULT
112                                           STOPCALL : FINAL RESULT
114                                           STOPCALL : FINAL RESULT
116                                           STOPCALL : FINAL RESULT
*SUB ANALYSIS ODCCK tiene 11 tuplas

ZRQI:EOS:NAME=NPSVIOCS:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
QUERY DONE NOT KNOWN TO BE PORTED             VIVNNOCS : FINAL RESULT
QUERY DONE PORTED OUT                         VINNPOCS : FINAL RESULT
QUERY DONE PORTED BETWEEN FOREIGN NETS        VINNPOCS : FINAL RESULT
*SUB ANALYSIS NPSVIOCS tiene 5 tuplas

ZRQI:EOS:NAME=NPSCKROA:;
DEFAULT RESULT:                               STOPCALL : FINAL RESULT
RESULT OF UNKNOWN ATTRIBUTE:                  STOPCALL : FINAL RESULT
QUERY DONE NOT KNOWN TO BE PORTED             NATIROAM : FINAL RESULT
QUERY DONE PORTED OUT                         PORTROAM : FINAL RESULT
QUERY DONE PORTED BETWEEN FOREIGN NETS        PORTROAM : FINAL RESULT
*SUB ANALYSIS NPSCKROA tiene 5 tuplas

ZRQI:EOS:NAME=IGORCK:;
DEFAULT RESULT:                               ODCCK    : SUBANALYSIS
RESULT OF UNKNOWN ATTRIBUTE:                  ODCCK    : SUBANALYSIS
2                                             DEFIJOS  : FINAL RESULT
*SUB ANALYSIS IGORCK tiene 3 tuplas

ZRQI:EOS:NAME=CBTYPECK:;
DEFAULT RESULT:                               IGORCK   : SUBANALYSIS
RESULT OF UNKNOWN ATTRIBUTE:                  IGORCK   : SUBANALYSIS
RESTRICTED/UNRESTRICTED DIGITAL BEARER        STOPCALL : FINAL RESULT
MULTIMEDIA BEARER                             STOPCALL : FINAL RESULT
*SUB ANALYSIS CBTYPECK tiene 4 tuplas
FIN!!!!