Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
#################################
# user_plane_analysis_final_res #
#################################
RESULT NAME                   : PUPUPD0
RESULT NAME                   : PUPSTOP
RESULT NAME                   : SBNIPV4D
RESULT NAME                   : SBNSTOP
RESULT NAME                   : CMNSTOP
RESULT NAME                   : SUPSTOP
RESULT NAME                   : SAISTOP
RESULT NAME                   : ICBSTOP
RESULT NAME                   : CMNINACD
RESULT NAME                   : SUPUPD0
RESULT NAME                   : SAIFORWD
RESULT NAME                   : ICBIPV4D
RESULT NAME                   : ICBIPV4
FIN!!!!