Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\25_oMSS_cdr_saving_parameters\oMSS_cdr_saving_parameters.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Connected
MSSVEN02: Connected
############
# MSSVEN02 #
############
#########################
# cdr_saving_parameters #
#########################
FIN!!!!MSSVEN02: Disconnected
