Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\73_oMSS_MeasurementControl\oMSS_MeasurementControl_.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
#######################
# Measurement Control #
#######################
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS135 OID:135
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS180 OID:180
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS182 OID:182
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS184 OID:184
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS185 OID:185
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS186 OID:186
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS188 OID:188
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS18C OID:188
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS191 OID:191
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS233 OID:233
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
MEAS: AMEAS183 OID:183
#############################################
# PROTOCOL TRAFFIC AND CAPACITY MEASUREMENT #
#############################################
############################
# GSM MEASUREMENT HANDLING #
############################
####################
# LOAD OBSERVATION #
####################
#######################
# TRAFFIC MEASUREMENT #
#######################
Semantic error, sending break character...
Sending <CTRL-Y>
Sending <CTRL-C>
###################
# FIELD REPORTING #
###################
##################
# SS7 STATISTICS #
##################
FIN!!!!