Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\100_oMSS_time_controlled_routing\oMSS_time_controlled_routing.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\100_oMSS_time_controlled_routing\oMSS_time_controlled_routing.tel', line 2 
   Variable 'temp' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Already connected
############
# MSSARA02 #
############
###########################
# time_controlled_routing #
###########################
Existen 6 TIME CONTROL NUMBER
TCN 2 DEST: SPR2176 DEST1: ANNDILO
TCN 2 DEST: SPR2176 DEST1: ANNDILO
TCN 3 DEST: MIXTOTRF2 DEST1: MIXTOTRF
TCN 5 DEST: SPR1031 DEST1: SPR1012
TCN 6 DEST: SPR9004 DEST1: TRATG2MS2FO
TCN 7 DEST: TREE002NATTG DEST1: TREE002NAT
TCN 8 DEST: SPR9005 DEST1: TRATG2MS2FO
FIN!!!!