Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Megaco_ping\oMSS_MEGACO_PING.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Megaco_ping\oMSS_MEGACO_PING.tel', line 3 
   Variable 'OPIP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Megaco_ping\oMSS_MEGACO_PING.tel', line 3 
   Variable 'OSIP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Megaco_ping\oMSS_MEGACO_PING.tel', line 3 
   Variable 'PIP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Megaco_ping\oMSS_MEGACO_PING.tel', line 3 
   Variable 'SIP' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Already connected
#####################
#  Media Gateway's  #
#####################
0       MGAR4MSAR2V00        GISU 6       11    REGISTERED           0/0 
1       MGAR4MSAR2V01        GISU 1       4    REGISTERED           0/0 
2       MGAR4MSAR2V02        GISU 2       5    REGISTERED           0/0 
3       MGAR4MSAR2V03        GISU 3       6    REGISTERED           0/0 
4       MGAR4MSAR2V04        GISU 4       7    REGISTERED           0/0 
5       MGAR4MSAR2V05        GISU 0       11    REGISTERED           0/0 
MGW NAME......................MGAR4MSAR2V04   
MGW ADDRESS...................10.40.15.135                           
PORT NUMBER...................8015
IPDU 7
E.164 AESA....................573103154402
LOCAL PORT....................2945
ZOYL:IPDU,7;

LOADING PROGRAM VERSION 10.2-0

MSS       MSSARA02                  2022-10-26  09:33:17

INTERROGATING SOURCE IP ADDRESSES FOR SCTP

UNIT: IPDU-7 
   PRIMARY SOURCE IPV4 ADDRESS  : 10.40.172.5                                
   SECONDARY SOURCE IPV4 ADDRESS: 10.41.172.5                                

COMMAND EXECUTED


SCTP CONFIGURATION HANDLING COMMAND <OY_>
<  ###############################
# SIGTRAN ASOCIACIONES - ZOYI #
###############################
MGAR4NA0                          0   M3UA        CLIENT
MGAR4NA1                          1   M3UA        CLIENT
STPVE                             2   M3UA        CLIENT
STPBU                             3   M3UA        CLIENT
ASOCIACION NUMERO 0:  MGAR4NA0
      0    IPDU-11         1 SIGTRAN          ASP-ACTIVE          
      1    IPDU-4          1 SIGTRAN          ASP-ACTIVE          
      2    IPDU-5          1 SIGTRAN          ASP-ACTIVE          
      3    IPDU-6          1 SIGTRAN          ASP-ACTIVE          
      4    IPDU-7          1 SIGTRAN          ASP-ACTIVE          
      5    IPDU-8          4 SIGTRAN          ASP-ACTIVE          
      6    IPDU-9          1 SIGTRAN          ASP-ACTIVE          
      7    IPDU-10         1 SIGTRAN          ASP-ACTIVE          
REGISTRATION REQUEST . . . :  NO 
ASOCIACION NUMERO 1:  MGAR4NA1
      0    IPDU-11         2 SIGTRAN          ASP-ACTIVE          
      1    IPDU-4          2 SIGTRAN          ASP-ACTIVE          
      2    IPDU-5          2 SIGTRAN          ASP-ACTIVE          
      3    IPDU-6          2 SIGTRAN          ASP-ACTIVE          
      4    IPDU-7          2 SIGTRAN          ASP-ACTIVE          
      5    IPDU-8          3 SIGTRAN          ASP-ACTIVE          
      6    IPDU-9          2 SIGTRAN          ASP-ACTIVE          
      7    IPDU-10         2 SIGTRAN          ASP-ACTIVE          
REGISTRATION REQUEST . . . :  NO 
ASOCIACION NUMERO 2:  STPVE
MSSARA02: Disconnected
MSSARA02: Disconnected
