Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\45_oMSS_unit_pool_handling\oMSS_unit_pool_handling.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\45_oMSS_unit_pool_handling\oMSS_unit_pool_handling.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\45_oMSS_unit_pool_handling\oMSS_unit_pool_handling.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\45_oMSS_unit_pool_handling\oMSS_unit_pool_handling.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
######################
# unit_pool_handling #
######################
FIN!!!!