Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\16_oMSS_in_trigger_key_definition\oMSS_in_trigger_key_definition.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
#############################
# in_trigger_key_definition #
#############################
1*- 50 HOMINGTRG
2*- 60 CHOMINGTRG
3*- 100 STARHO1528D3
4*- 101 STARHOM1528
5*- 102 TOMIA1528V
6*- 103 TOMIA1528VA
7*- 104 TOMIR1528V
8*- 105 TOMII1528V
9*- 106 TOMIR1528VA
10*- 107 TOMII1528VA
11*- 108 TOMIR1528VB
12*- 109 TOMII1528VB
13*- 200 LLAMADAXB500
14*- 201 SRBTVE01TRG1
15*- 202 SRBTVE01TRG2
16*- 300 CCNOCSDP2
17*- 301 CCNOCSDP3
18*- 400 VPNHUAWEIDP2
19*- 401 VPNHUAWEIDP3
FIN!!!!