Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\17_oMSS_in_service_set_definition\oMSS_in_service_set_definition.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
#############################
# in_service_set_definition #
#############################
1*- 25 SRBT
2*- 196 VPNHUAWEIDP2
3*- 197 VPNHUAWEIDP3
4*- 205 LLAMADAXB500
5*- 1000 STARHO1528D3
6*- 1001 STARHOM1528
7*- 1002 TOMIA1528V
8*- 1003 TOMIA1528VA
9*- 1050 HOMINGSET
10*- 1060 CHOMINGSSET
11*- 1700 CCNOCSDP2
12*- 1701 CCNOCSDP3
FIN!!!!