Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE_V2.tel', line 18 
   Variable 'DEST' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE_V2.tel', line 18 
   Variable 'SDEST' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE_V2.tel', line 19 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE\oMSS_SIG_ROU_CGR_SUBDEST_DEST_TREE_V2.tel', line 19 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Connected
MSSING02: Connected
NA0   03C5/00965       MS2ME             AV      03E5/00997        AV-EX   7
NA0   03C8/00968       MS3ME             AV      03E5/00997        AV-EX   7
NA0   03E2/00994       MS5ME             AV      03E5/00997        AV-EX   7
NA0   03E5/00997       STPME             AV      03E5/00997        AV-EX   7
NA0   03E7/00999       MS6ME             UA      03E5/00997        UA-INR  7
NA0   03EA/01002       MSMG2             AV      03E5/00997        AV-EX   7
NA0   03EC/01004       MSMG1             AV      03E5/00997        AV-EX   7
NA0   06A0/01696       MSAR1             AV      03E5/00997        AV-EX   7
NA0   06A3/01699       MSVE1             AV      03E5/00997        AV-EX   7
NA0   0709/01801       MS5VE             AV      03E5/00997        AV-EX   7
NA0   0727/01831       MSTR1             AV      03E5/00997        AV-EX   7
NA0   072B/01835       MS6VE             AV      03E5/00997        AV-EX   7
NA0   072C/01836       MS7VE             AV      03E5/00997        AV-EX   7
NA0   072F/01839       MSTR2             AV      03E5/00997        AV-EX   7
NA0   0761/01889       MS3PR             AV      03E5/00997        AV-EX   7
NA0   0791/01937       MS4VE             AV      03E5/00997        AV-EX   7
NA0   0794/01940       MS3VE             AV      03E5/00997        AV-EX   7
NA0   0796/01942       MS2VE             AV      03E5/00997        AV-EX   7
NA0   07A7/01959       MSVE2             AV      03E5/00997        AV-EX   7
NA0   07AF/01967       MS5AR             AV      03E5/00997        AV-EX   7
NA0   07B2/01970       MSAR2             AV      03E5/00997        AV-EX   7
NA0   07B4/01972       MS6AR             AV      03E5/00997        AV-EX   7
NA0   07B9/01977       MS7AR             AV      03E5/00997        AV-EX   7
NA0   07BB/01979       MS1TO             AV      03E5/00997        AV-EX   7
NA0   07BE/01982       MS2TO             AV      03E5/00997        AV-EX   7
NA0   07C8/01992       MSTR3             AV      03E5/00997        AV-EX   7
NA0   07DE/02014       MS3AR             AV      03E5/00997        AV-EX   7
NA0   07E1/02017       MS4AR             AV      03E5/00997        AV-EX   7
NA0   082D/02093       MSIN1             AV      03E5/00997        AV-EX   7
NA0   0996/02454       MGIN2             AV      0996/02454        AV-EX   7
NA0   0997/02455       MS1PS             UA      03E5/00997        UA-INR  7
NA0   099A/02458       MSIN2             -     OWN SP AS STP
NA0   0BC7/03015       MS2CL             AV      03E5/00997        AV-EX   7
NA0   0BCA/03018       MS3CL             AV      03E5/00997        AV-EX   7
NA0   0BE7/03047       MS4CL             AV      03E5/00997        AV-EX   7
NA0   0BEA/03050       MS1IN             AV      03E5/00997        AV-EX   7
NA0   0BED/03053       STPIN             AV      0BED/03053        AV-EX   7
NA0   1551/05457       MS1SI             AV      03E5/00997        AV-EX   7
NA0   1556/05462       MS2SI             UA      03E5/00997        UA-INR  7
NA0   17B2/06066       MSAK1             AV      03E5/00997        AV-EX   7
NA0   17C1/06081       MS3BA             AV      03E5/00997        AV-EX   7
NA0   17C3/06083       MSSK2             AV      03E5/00997        AV-EX   7
NA0   17DE/06110       MS1CA             AV      03E5/00997        AV-EX   7
NA0   17E6/06118       MS4BA             AV      03E5/00997        AV-EX   7
NA0   17EA/06122       MS1AK             AV      03E5/00997        AV-EX   7
NA0   17ED/06125       MS2AK             AV      03E5/00997        AV-EX   7
NA0   1BC4/07108       MS1PE             AV      03E5/00997        AV-EX   7
NA0   1BC6/07110       MS2PE             AV      03E5/00997        AV-EX   7
NA0   1BCE/07118       MSPE1             AV      03E5/00997        AV-EX   7
NA0   1BD4/07124       MS3PE             AV      03E5/00997        AV-EX   7
NA0   1FCA/08138       MS1BU             AV      03E5/00997        AV-EX   7
NA0   1FCD/08141       MS2BU             AV      03E5/00997        AV-EX   7
NA0   1FD4/08148       MS3BU             UA      03E5/00997        UA-INR  7
NA0   1FD6/08150       MSBU1             AV      03E5/00997        AV-EX   7
NA0   3C4A/15434       MSMA1             AV      03E5/00997        AV-EX   7
NA0   3F1A/16154       CPCOS             AV      03E5/00997        AV-EX   7
NA0   3F29/16169       CPCOR             AV      03E5/00997        AV-EX   7
NA0   3FAA/16298       CPCOC             AV      03E5/00997        AV-EX   7

MSS: MSSING02 - OWN POINT CODE: 099A
ZNRI:NA0,1FD4:;

LOADING PROGRAM VERSION 8.38-0

MSS       MSSING02                  2023-06-01  08:14:03

INTERROGATING SIGNALLING POINT DATA

NET  SP CODE H/D         NAME              RS STATE  PAR SET
---  ------------------  ----------------  --------  -------
NA0    1FD4/08148        MS3BU               UA        6
LOAD SHARING BETWEEN SIGNALLING ROUTES ALLOWED
SCREENING GROUPS: AASG 0, ADSG 0, OOSG 0, ODSG 0

ROUTES: SP CODE H/D         NAME              STATE   PRIO
        ------------------  ----------------  ------  ----
          03E5/00997        STPME             UA-INR    7    
          0BED/03053        STPIN             UA-INR    7    



COMMAND EXECUTED


SIGNALLING ROUTE SET DATA HANDLING COMMAND <NR_>
<  ZRCI:;

LOADING PROGRAM VERSION 16.26-0

MSS       MSSING02                  2023-06-01  08:14:04

CIRCUIT GROUP(S)

CGR       NCGR              TYPE      DIR       TREE      NBCRCT    STATE     

152       TONES             SPE       BI        -         31        WO-EX     
2602      IPI23ARA          BICC      BI        90        1054      WO-EX     
2603      IPI24ARA          BICC      BI        90        1054      WO-EX     
2604      IPI25ARA          BICC      BI        90        310       WO-EX     
2605      IPI26ARA          BICC      BI        90        620       WO-EX     
2606      IPI27ARA          BICC      BI        90        620       WO-EX     
2611      IPI22VEA          BICC      BI        90        1024      WO-EX     
2612      IPI23VEA          BICC      BI        90        1024      WO-EX     
2613      IPI24VEA          BICC      BI        90        1024      WO-EX     
2614      IPI25VEA          BICC      BI        90        1024      WO-EX     
2615      IPI26VEA          BICC      BI        90        1024      WO-EX     
2616      IPI27VEA          BICC      BI        90        1024      WO-EX     
2621      IPI22BUA          BICC      BI        90        1024      WO-EX     
2622      IPI23BUA          BICC      BI        90        1024      BA-SY     
2623      IPI21TOA          BICC      BI        90        1024      WO-EX     
2624      IPI22TOA          BICC      BI        90        1024      WO-EX     
2625      IPI23PRA          BICC      BI        90        1024      WO-EX     
2630      IPI22CLA          BICC      BI        90        2048      WO-EX     
2631      IPI23CLA          BICC      BI        90        2048      WO-EX     
2632      IPI24CLA          BICC      BI        90        2048      WO-EX     
2633      IPI21INA          BICC      BI        90        2048      WO-EX     
2634      IPI21PSA          BICC      BI        90        2048      BA-SY     
2635      IPI21PEA          BICC      BI        90        2048      WO-EX     
2636      IPI22PEA          BICC      BI        90        2048      WO-EX     
2640      IPI22MEA          BICC      BI        90        2048      WO-EX     
2641      IPI23MEA          BICC      BI        90        2048      WO-EX     
2643      IPI25MEA          BICC      BI        90        2048      WO-EX     
2644      IPI26MEA          BICC      BI        90        2048      BA-SY     
2651      IPI23BAA          BICC      BI        90        2048      WO-EX     
2653      IPI21AKA          BICC      BI        90        1024      WO-EX     
2654      IPI22AKA          BICC      BI        90        1024      WO-EX     
2655      IPI21CAA          BICC      BI        90        1024      WO-EX     
2656      IPI21SIA          BICC      BI        90        1024      WO-EX     
2657      IPI22SIA          BICC      BI        90        1024      BA-SY     
2800      IPI2AR1A          BICC      BI        90        2048      WO-EX     
2820      IPI2VE1A          BICC      BI        90        2048      WO-EX     
2830      IPI2TR1A          BICC      BI        90        2048      WO-EX     
2831      IPI2TR2A          BICC      BI        90        2048      WO-EX     
2840      IPI2BU1A          BICC      BI        90        2048      WO-EX     
2850      IPI2MG1A          BICC      BI        90        2048      WO-EX     
2854      IPI2MG2A          BICC      BI        90        2048      WO-EX     
2858      IPI2TR3A          BICC      BI        90        2048      WO-EX     
2859      IPI2AR2A          BICC      BI        90        2048      WO-EX     
2860      IPI2IN1A          BICC      BI        90        2048      WO-EX     
2870      IPI2PE1A          BICC      BI        90        2048      WO-EX     
2884      IPI2VE2A          BICC      BI        90        2048      WO-EX     
2890      IPI2AK1A          BICC      BI        90        1024      WO-EX     
2891      IPI2AK2A          BICC      BI        90        2048      WO-EX     
2910      IPI2MA1A          BICC      BI        90        1024      WO-EX     

COMMAND EXECUTED


CIRCUIT GROUP HANDLING COMMAND <RC_>
<  CGR: 2622 NCGR: IPI23BUA
ROU: 2622
ZRIR:ROU=2622:;

LOADING PROGRAM VERSION 16.11-0

MSS       MSSING02                  2023-06-01  08:14:08

/*** DIGIT ANALYSES NOT FOUND ***/

COMMAND EXECUTED



 DIGIT ANALYSIS INTERROGATION COMMAND <RI_>
<  ZRIH:CGR=2622:;

LOADING PROGRAM VERSION 16.11-0

MSS       MSSING02                  2023-06-01  08:14:23

TREE=   90  ATYPE=N  TON=INT  
CGR   NCGR                                                                  
2622  IPI23BUA                                                              

DIGITS                   AL NDEST        CHI CNT NSDEST       CORG  NCHA   
00444                     0 TREE002INT   2   N   SPR9002      0     CHARGE      
573212980&-1              0 IMRNCFTR01   2   N   SPR4001      0     CHARGE      
573212982&-3              0 IMRNCFMG01   2   N   SPR4001      0     CHARGE      
573212984&&-7             0 IMRNCFTR01   2   N   SPR4001      0     CHARGE      
573212988&&-9             0 IMRNCFTRI1   2   N   SPR4001      0     CHARGE      
573212990&-1              0 IMRNCFTR01   2   N   SPR4001      0     CHARGE      
573212992&-3              0 IMRNCFMG01   2   N   SPR4001      0     CHARGE      
573212994&-5              0 IMRNCFTR01   2   N   SPR4001      0     CHARGE      
573212996                 0 IMRNCFTRI1   2   N   SPR4001      0     CHARGE      
573222990&&-5             0 IMRNCFTRI1   2   N   SPR4001      0     CHARGE      
573226290&&-2             0 IMRNCFAK01   2   N   SPR4001      0     CHARGE      
573226293&&-5             0 IMRNCFMG03   2   N   SPR4001      0     CHARGE      
573226296&&-8             0 IMRNCFMG04   2   N   SPR4001      0     CHARGE      
573226299&&573226304      0 IMRNCFMG05   2   N   SPR4001      0     CHARGE      
9910                      0 RBTPLAY      1   N   IPMSS02CAL   0     NOCHARGE    

TREE=   90  ATYPE=N  TON=NAT  
CGR   NCGR                                                                  
2622  IPI23BUA                                                              

DIGITS                   AL NDEST        CHI CNT NSDEST       CORG  NCHA   
018000160&&-4             0 TREE002NAT   2   N   SPR9001      0     CHARGE      
01800091&-3&&-7&-9        0 TREE002NAT   2   N   SPR9001      0     CHARGE      
01901444                  0 TREE002NAT   2   N   SPR9001      0     CHARGE      
031&&-8                   0 TREE002NAT   2   N   SPR9001      0     CHARGE      
03910                     0 TREE002NAT   2   N   SPR9001      0     CHARGE      
310&&-4                   0 TREE050NAT   2   N   SPR9003      0     CHARGE      
320&&-2                   0 TREE050NAT   2   N   SPR9003      0     CHARGE      
3232&&-5                  0 TREE050NAT   2   N   SPR9003      0     CHARGE      
601&-2&-4&-5              0 TREE002NAT   2   N   SPR9001      0     CHARGE      
6067552&-3                0 TELMEXERMIT2 2   N   IPMSSING01   0     CHARGE      
60675540                  0 TELMEXERMIT2 2   N   IPMSSING01   0     CHARGE      
606                      0 TREE002NAT   2   N   SPR9001      0     CHARGE      
607&-8                    0 TREE002NAT   2   N   SPR9001      0     CHARGE      
9915                      0 TREE086INFRA 2   N   SPR1086      0     CHARGE      
997&-8                    0 INT998SBC    2   N   SPR9001      0     CHARGE      

TREE=   90  ATYPE=N  TON=SUB  
CGR   NCGR                                                                  
2622  IPI23BUA                                                              

DIGITS                   AL NDEST        CHI CNT NSDEST       CORG  NCHA   
B229                      0 SCB229OCC    2   N   SPR2178      0     CHARGE      
B230                      0 TRANIVRB230  2   N   SSRTRIB230   0     CHARGE      
                          1 TRANIVRB230  2   N   SSRALKB230   0     CHARGE      
B552                      0 RBTACCESS    2   N   IPMSS02CAL   0     CHARGE      
                          1 RBTACCESS    1   N   PRECANN0135  0     NOCHARGE    
B888                      0 AD9915INTFBA 2   N   FBTONE       0     CHARGE      
                          1 AD9915INTFBA 1   N   PRECONEXINT  0     NOCHARGE    
BC124C                    0 TREE002NAT   2   N   SPR9001      0     CHARGE      
BC200C                    0 IMRNCFXCLOUD 2   N   IPMSSALK02   0     CHARGE      
                          1 IMRNCFXCLOUD 2   N   IPMSSTRI03   0     CHARGE      
BC333C                    0 TEST333MGCF  2   N   IPMSSING01   0     CHARGE      
                          1 TEST333MGCF  2   N   IPMSSMGA02   0     CHARGE      
BC411C2159894             0 TREE002NAT   2   N   SPR9001      0     CHARGE      
BC411C3102159894          0 TREE002NAT   2   N   SPR9001      0     CHARGE      
BC998C                    0 BC998CINT    2   N   SPR1635      0     CHARGE      

TREE=   90  ATYPE=N  TON=NET  
CGR   NCGR                                                                  
2622  IPI23BUA                                                              

DIGITS                   AL NDEST        CHI CNT NSDEST       CORG  NCHA   
9910                      0 RBTPLAY      1   N   IPMSS02CAL   0     NOCHARGE    

TREE=   90  ATYPE=N  TON=CON  
CGR   NCGR                                                                  
2622  IPI23BUA                                                              

DIGITS                   AL NDEST        CHI CNT NSDEST       CORG  NCHA   
132                       0 SPR1028      2   N   SPR1028      0     CHARGE      
3323                      0 CELMOBNTV    2   N   SPR1557      0     CHARGE      
3763                      0 PLINMOBNTV   2   N   SPR1557      0     CHARGE      

COMMAND EXECUTED



 DIGIT ANALYSIS INTERROGATION COMMAND <RI_>
<  MSSING02: Closing..
MSSING02: Disconnected
Hora inicio de macro: 2023-06-01  08:12:58
Hora fin de macro: 2023-06-01  08:14:24
FIN!!!!