Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
incoming_call_control_parameter###################################
# incoming_call_control_parameter #
###################################
FIN!!!!