Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter_V2.tel', line 3 
   Variable 'ARABIP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\43_oMSS_incoming_call_control_parameter\oMSS_incoming_call_control_parameter_V2.tel', line 3 
   Variable 'CDR' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
###################################
# incoming_call_control_parameter #
###################################
# Name	OWN	CLIS	NCLIC	REROU
1*- MAS	Y Y N Y
2*- HANDOVER	N N Y N
3*- MONITORINGCALL	N Y N Y
4*- SCP	N Y N Y
5*- MSPWR1	N Y N Y
6*- MSPWR2	N Y N Y
7*- EXTIP	N Y N Y
8*- CCBSRECALL	Y N N N
9*- SSAP	N Y N Y
10*- BASICINPSTNPBX	N Y N N
11*- TIGO	N Y N N
12*- ETB2MSS	N Y N N
13*- MOVISTAR	N Y N Y
14*- WOM	N Y N Y
15*- SIPSSR	N Y N Y
16*- INTERMSC	Y Y N Y
17*- INTERMSS	Y Y N Y
18*- IMSSIP	N Y N Y

FIN!!!!