Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\64_oMSS_special_routes__gsm_end\oMSS_special_routes__gsm_end_.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\64_oMSS_special_routes__gsm_end\oMSS_special_routes__gsm_end_.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\64_oMSS_special_routes__gsm_end\oMSS_special_routes__gsm_end_.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\64_oMSS_special_routes__gsm_end\oMSS_special_routes__gsm_end_.tel', line 2 
   Variable 'FLAG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\64_oMSS_special_routes__gsm_end\oMSS_special_routes__gsm_end_.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\64_oMSS_special_routes__gsm_end\oMSS_special_routes__gsm_end_.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
############################
# special_routes__gsm_end_ #
############################
ZRPI:SRT=GSMEND;

LOADING PROGRAM VERSION 26.5-0


 SPECIAL ROUTE FOR GSM END
 OUTROUTE        STP            SPR
 SIGNALLING
                                           
 OMCG0             1             00001          
COMMAND EXECUTED


GSM SPECIAL ROUTE HANDLING COMMAND <RP_>
<  FIN!!!!