Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\85_oMSS_ccbs_parameters_in_msc\oMSS_ccbs_parameters_in_msc.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\85_oMSS_ccbs_parameters_in_msc\oMSS_ccbs_parameters_in_msc.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\85_oMSS_ccbs_parameters_in_msc\oMSS_ccbs_parameters_in_msc.tel', line 2 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\85_oMSS_ccbs_parameters_in_msc\oMSS_ccbs_parameters_in_msc.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\85_oMSS_ccbs_parameters_in_msc\oMSS_ccbs_parameters_in_msc.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Connected
MSSARA02: Connected

** Echo error detected **
Mismatched echo: [MAIN LEVEL COMMAND <___>
<  ]
Expected   echo: [ZDCD;]
############
# MSSARA02 #
############
##########################
# ccbs_parameters_in_msc #
##########################
FIN!!!!MSSARA02: Disconnected
