Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\11_oMSS_gsm_nw_and_ne_specific_numbers\oMSS_gsm_nw_and_ne_specific_numbers.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
gsm_nw_and_ne_specific_numbers
##################################
# gsm_nw_and_ne_specific_numbers #
##################################
FIN!!!!