Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\95_oMSS_licence_and_feature_handling\oMSS_licence_and_feature_Inventory.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.


############
# MSSVEN02 #
############
ACCESING 1: MSSVEN02
MSSVEN02: Connected
MSSVEN02: Connected
El acceso al MSS: MSSVEN02 esta OK
MSSVEN02, ____CMSSLK0300006000____, ____6000_MSS_Cloud_Capacity_Pack_on/off_LK__, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____5000000
MSSVEN02, ____CMSSLK0600006005____, ____6005_CS_FallBack_capacity_LK____________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____5000000
MSSVEN02, ____CMSSLK0300006005____, ____6005_CS_FallBack_on/off_LK______________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____5000000
MSSVEN02, ____CMSSLK0300006011____, ____6011_Camel_on/off_LK____________________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN02, ____CMSSLK0300006015____, ____6015_Enhanced_subscriber_exp_on/off_LK__, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN02, ____CMSSLK0300006017____, ____6017_Multi_user_support_on/off_LK_______, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN02, ____CMSSLK0300064209____, ____64209_CAMEL:SuppressT-CSI_on/off_CLK____, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN02, ____CMSSLK0300006057____, ____6057_OLCM_on/off_LK_____________________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN02, ____CMSSLK0309014664____, ____9014664_Resource_prior_mapping_MGCF_CLK_, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
FEA MSSVEN02, ____385, ____Enhanced_VLR_Filtering_and_Categorizing_, ____ON, ____5000000, 
FEA MSSVEN02, ____224, ____VLR_Capacity_for_Super_Charger__________, ____ON, ____5000000, 
FEA MSSVEN02, ____688, ____Video_Call_Forwarding_in_2G_____________, ____ON, ____5000000, 
FEA MSSVEN02, ____1196, ____RNC_in_multiple_PLMN____________________, ____ON, ____5000000, 
FEA MSSVEN02, ____1333, ____T38_in_MSS______________________________, ____ON, ____5000000, 
FEA MSSVEN02, ____1433, ____Optimized_MGW_selection_over_SIPI_______, ____ON, ____5000000, 
FEA MSSVEN02, ____3722, ____Extended_SA_and_Cell_capacity_in_MSS____, ____ON, ____5000000, 
FEA MSSVEN02, ____3921, ____Extended_LA/RNC_capacity_in_MSS_________, ____ON, ____5000000, 
FEA MSSVEN02, ____1691, ____SMS_support_in_SGs_interface____________, ____ON, ____5000000, 
FEA MSSVEN02, ____1935, ____Full_CSFB_support_in_SGs_interface______, ____ON, ____5000000, 
FEA MSSVEN02, ____223, ____VLR_Camel_Ph4_Capacity__________________, ____ON, ____5000000, 
FEA MSSVEN02, ____466, ____MSC_CAMEL_Ph3_support___________________, ____ON, , 
FEA MSSVEN02, ____467, ____MSC_CAMEL_Ph4_support___________________, ____ON, , 
FEA MSSVEN02, ____3934, ____INSU_CDR_FOR_CAMEL______________________, ____ON, , 
FEA MSSVEN02, ____583, ____MSC_Video_Ringback_Tone_support_________, ____ON, , 
FEA MSSVEN02, ____1499, ____SRBT_for_A_party________________________, ____ON, , 
FEA MSSVEN02, ____2088, ____Music_On_Hold___________________________, ____ON, , 
FEA MSSVEN02, ____2261, ____IN_Controlled_Ring_Back_Tone_Service_(RB, ____ON, , 
FEA MSSVEN02, ____2262, ____Multilingual_Announcements______________, ____ON, , 
FEA MSSVEN02, ____2267, ____MSS_controlled_SRBT_____________________, ____ON, , 
FEA MSSVEN02, ____4691, ____MSS_based_advertisement_service_________, ____ON, , 
FEA MSSVEN02, ____1603, ____SMS_MULTISIM_HLR________________________, ____ON, , 
FEA MSSVEN02, ____1656, ____SMS_MULTISIM_LDAP_______________________, ____ON, , 
FEA MSSVEN02, ____2170, ____MultiSIM_Phase_3________________________, ____ON, , 
FEA MSSVEN02, ____2264, ____Same_CLI_for_Multiple_Subscribers_______, ____ON, , 
FEA MSSVEN02, ____3442, ____LDAP_based_common_CLI___________________, ____ON, , 
FEA MSSVEN02, ____6155, ____Support_group_MSISDN_presenting_in_IDP__, ____ON, , 
FEA MSSVEN02, ____2201, ____CAMEL:_Suppress_T-CSI_in_SRI_based_on_ca, ____ON, , 
FEA MSSVEN02, ____468, ____Dynamic_Delivery_Function_Status________, ____ON, , 
FEA MSSVEN02, ____571, ____OLCM_SFTP_Support_______________________, ____ON, , 
FEA MSSVEN02, ____50036, ____Resource_priority_header_mapping_(Ph1)__, ____ON, , 
MSSVEN02: Closing..
MSSVEN02: Disconnected

############
# MSSVEN01 #
############
ACCESING 2: MSSVEN01
MSSVEN01: Connected
MSSVEN01: Connected
El acceso al MSS: MSSVEN01 esta OK
MSSVEN01, ____MSGLIC61384_________, ____L.1384_MSS_Camel_4_LK___________________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC61381_________, ____L.1381_MSS_Camel_3_LK___________________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC64130_________, ____L.4130_LTE_SMS_over_SGS_I/F_LK__________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC61249_________, ____L.1249_MSS_Basic_SW_capacity_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC31322_________, ____L.1322_eMLPP_LK_________________________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____C.1249______________, ____L.1637_IPDU_based_M3UA_LB_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34242_________, ____L.4242_Load_Balancer_for_H.248_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34241_________, ____L.4241_Load_Balancer_for_SIP_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34715_________, ____L.4715_Advanced_Location_Services_LK____, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31614_________, ____L.1614_Balanced_Signalling_Traffic_LK___, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31660_________, ____L.1660_SRVCC_for_held_calls_LK__________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____1
MSSVEN01, ____MSGLIC31531_________, ____L.1531_CSFB_Overlay_LK__________________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31443_________, ____L.1443_MSS_IP_Based_Iu-CS_Interface_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31326_________, ____L.1326_Multipoint_A-interface_LK________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31312_________, ____L.1312_Multipoint_Iu-interface_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31470_________, ____L.1470_Multipoint_Adv_KIT_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34247_________, ____L.4247_MSS_A_over_IP_with_TC_in_MGW_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31470_________, ____L.1470_Multipoint_Adv_KIT_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31326_________, ____L.1326_Multipoint_A-interface_LK________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34247_________, ____L.4247_MSS_A_over_IP_with_TC_in_MGW_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31421_________, ____L.1421_MSS_Multiple_Isolated_IP_NW_LK___, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31416_________, ____L.1416_PBX_Support_Using_IUA_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31312_________, ____L.1312_Multipoint_Iu-interface_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31404_________, ____L.1404_VLR_filtering,_IMSI_list_LK______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34251_________, ____L.4251_Identical_IMEI_support_in_MSS_LK_, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31530_________, ____L.1530_SGs_I/F_voice_conncetivity_LK____, ____Comcel, ____ACTIVE_UNLIMITED, ____50000
MSSVEN01, ____MSGLIC61381_________, ____L.1381_MSS_Camel_3_LK___________________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSVEN01, ____MSGLIC61249_________, ____L.1249_MSS_Basic_SW_capacity_LK_________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSVEN01, ____MSGLIC64130_________, ____L.4130_LTE_SMS_over_SGS_I/F_LK__________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSVEN01, ____MSGLIC31104_________, ____L.1104_Multiple-PLMN_Inter-PLMN_HO_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____1
MSSVEN01, ____MSGLIC63006_________, ____L.3006_SRVCC_capacity_license_LK________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____20000
MSSVEN01, ____MSGLIC33392_________, ____L.3392_MSS_G.729AB_Codec_LK_____________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN01, ____MSGLIC34177_________, ____L.4177_CS_Allocation_and_Retention_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN01, ____MSGLIC9014664_______, ____L.9014664_Resource_priority_mapping_MGCF, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
FEA MSSVEN01, ____223, ____VLR_Camel_Ph4_Capacity__________________, ____ON, ____2000000, 
FEA MSSVEN01, ____467, ____MSC_CAMEL_Ph4_support___________________, ____ON, ____2000000, 
FEA MSSVEN01, ____222, ____VLR_Camel_Ph3_Capacity__________________, ____ON, ____2800000, 
FEA MSSVEN01, ____466, ____MSC_CAMEL_Ph3_support___________________, ____ON, ____2800000, 
FEA MSSVEN01, ____1691, ____SMS_support_in_SGs_interface____________, ____ON, ____2800000, 
FEA MSSVEN01, ____221, ____VLR_Subscriber_Capacity_________________, ____ON, ____2800000, 
FEA MSSVEN01, ____2156, ____eMLPP___________________________________, ____ON, ____1, 
FEA MSSVEN01, ____3479, ____IPDU_based_M3UA_Load_Balancer___________, ____ON, ____1, 
FEA MSSVEN01, ____1473, ____H248_Load_Balancer_in_MSS_______________, ____ON, ____1, 
FEA MSSVEN01, ____1462, ____SIP_load_balancer_______________________, ____ON, ____1, 
FEA MSSVEN01, ____2298, ____Advanced_Location_Services______________, ____ON, ____1, 
FEA MSSVEN01, ____4275, ____Balanced_distribution_of_SS7_traffic____, ____ON, ____1, 
FEA MSSVEN01, ____4574, ____MSC_server_Assisted_mid-call_feature_sup, ____ON, ____1, 
FEA MSSVEN01, ____1267, ____Iu_CS_interface_over_IP_________________, ____ON, ____1, 
FEA MSSVEN01, ____1460, ____AoIP_TC_in_MGW_support__________________, ____ON, ____2, 
FEA MSSVEN01, ____1121, ____MSS_multiple_isolated_IP_networks_______, ____ON, ____1, 
FEA MSSVEN01, ____899, ____IUA_____________________________________, ____ON, ____1, 
FEA MSSVEN01, ____2247, ____VLR_filtering,_IMSI_list_to_file________, ____ON, ____1, 
FEA MSSVEN01, ____2165, ____Identical_IMEI_support_in_MSS___________, ____ON, ____1, 
FEA MSSVEN01, ____3496, ____CSFB_counter_enhancement________________, ____ON, ____70000, 
FEA MSSVEN01, ____2172, ____Multiple-PLMN_and_Inter-PLMN_Handover_Su, ____ON, ____1, 
FEA MSSVEN01, ____856, ____G.729A__________________________________, ____ON, , 
FEA MSSVEN01, ____2265, ____CS_Allocation_and_Retention_(ARP)_______, ____ON, , 
FEA MSSVEN01, ____50036, ____Resource_priority_header_mapping_(Ph1)__, ____ON, , 
MSSVEN01: Closing..
MSSVEN01: Disconnected

############
# MSSING02 #
############
ACCESING 3: MSSING02
MSSING02: Connected
MSSING02: Connected
El acceso al MSS: MSSING02 esta OK
MSSING02, ____CMSSLK0300006000____, ____6000_MSS_Cloud_Capacity_Pack_on/off_LK__, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____5000000
MSSING02, ____CMSSLK0600006005____, ____6005_CS_FallBack_capacity_LK____________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____5000000
MSSING02, ____CMSSLK0300006005____, ____6005_CS_FallBack_on/off_LK______________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____5000000
MSSING02, ____CMSSLK0300006011____, ____6011_Camel_on/off_LK____________________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSING02, ____CMSSLK0300006015____, ____6015_Enhanced_subscriber_exp_on/off_LK__, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSING02, ____CMSSLK0300006017____, ____6017_Multi_user_support_on/off_LK_______, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSING02, ____CMSSLK0300064209____, ____64209_CAMEL:SuppressT-CSI_on/off_CLK____, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSING02, ____CMSSLK0300006057____, ____6057_OLCM_on/off_LK_____________________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
FEA MSSING02, ____385, ____Enhanced_VLR_Filtering_and_Categorizing_, ____ON, ____5000000, 
FEA MSSING02, ____224, ____VLR_Capacity_for_Super_Charger__________, ____ON, ____5000000, 
FEA MSSING02, ____688, ____Video_Call_Forwarding_in_2G_____________, ____ON, ____5000000, 
FEA MSSING02, ____1196, ____RNC_in_multiple_PLMN____________________, ____ON, ____5000000, 
FEA MSSING02, ____1333, ____T38_in_MSS______________________________, ____ON, ____5000000, 
FEA MSSING02, ____1433, ____Optimized_MGW_selection_over_SIPI_______, ____ON, ____5000000, 
FEA MSSING02, ____3722, ____Extended_SA_and_Cell_capacity_in_MSS____, ____ON, ____5000000, 
FEA MSSING02, ____3921, ____Extended_LA/RNC_capacity_in_MSS_________, ____ON, ____5000000, 
FEA MSSING02, ____1691, ____SMS_support_in_SGs_interface____________, ____ON, ____5000000, 
FEA MSSING02, ____1935, ____Full_CSFB_support_in_SGs_interface______, ____ON, ____5000000, 
FEA MSSING02, ____223, ____VLR_Camel_Ph4_Capacity__________________, ____ON, ____5000000, 
FEA MSSING02, ____466, ____MSC_CAMEL_Ph3_support___________________, ____ON, , 
FEA MSSING02, ____467, ____MSC_CAMEL_Ph4_support___________________, ____ON, , 
FEA MSSING02, ____3934, ____INSU_CDR_FOR_CAMEL______________________, ____ON, , 
FEA MSSING02, ____583, ____MSC_Video_Ringback_Tone_support_________, ____ON, , 
FEA MSSING02, ____1499, ____SRBT_for_A_party________________________, ____ON, , 
FEA MSSING02, ____2088, ____Music_On_Hold___________________________, ____ON, , 
FEA MSSING02, ____2261, ____IN_Controlled_Ring_Back_Tone_Service_(RB, ____ON, , 
FEA MSSING02, ____2262, ____Multilingual_Announcements______________, ____ON, , 
FEA MSSING02, ____2267, ____MSS_controlled_SRBT_____________________, ____ON, , 
FEA MSSING02, ____4691, ____MSS_based_advertisement_service_________, ____ON, , 
FEA MSSING02, ____1603, ____SMS_MULTISIM_HLR________________________, ____ON, , 
FEA MSSING02, ____1656, ____SMS_MULTISIM_LDAP_______________________, ____ON, , 
FEA MSSING02, ____2170, ____MultiSIM_Phase_3________________________, ____ON, , 
FEA MSSING02, ____2264, ____Same_CLI_for_Multiple_Subscribers_______, ____ON, , 
FEA MSSING02, ____3442, ____LDAP_based_common_CLI___________________, ____ON, , 
FEA MSSING02, ____6155, ____Support_group_MSISDN_presenting_in_IDP__, ____ON, , 
FEA MSSING02, ____2201, ____CAMEL:_Suppress_T-CSI_in_SRI_based_on_ca, ____ON, , 
FEA MSSING02, ____468, ____Dynamic_Delivery_Function_Status________, ____ON, , 
FEA MSSING02, ____571, ____OLCM_SFTP_Support_______________________, ____ON, , 
MSSING02: Closing..
MSSING02: Disconnected

############
# MSSING01 #
############
ACCESING 4: MSSING01
MSSING01: Connected
MSSING01: Connected
El acceso al MSS: MSSING01 esta OK
MSSING01, ____MSGLIC31312_________, ____L.1312_Multipoint_Iu-interface_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31470_________, ____L.1470_Multipoint_Adv_KIT_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31326_________, ____L.1326_Multipoint_A-interface_LK________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC34247_________, ____L.4247_MSS_A_over_IP_with_TC_in_MGW_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31421_________, ____L.1421_MSS_Multiple_Isolated_IP_NW_LK___, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31416_________, ____L.1416_PBX_Support_Using_IUA_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC61249_________, ____L.1249_MSS_Basic_SW_capacity_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSING01, ____MSGLIC61384_________, ____L.1384_MSS_Camel_4_LK___________________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSING01, ____MSGLIC31443_________, ____L.1443_MSS_IP_Based_Iu-CS_Interface_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC34715_________, ____L.4715_Advanced_Location_Services_LK____, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC64130_________, ____L.4130_LTE_SMS_over_SGS_I/F_LK__________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSING01, ____MSGLIC34241_________, ____L.4241_Load_Balancer_for_SIP_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31322_________, ____L.1322_eMLPP_LK_________________________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31530_________, ____L.1530_SGs_I/F_voice_conncetivity_LK____, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31614_________, ____L.1614_Balanced_Signalling_Traffic_LK___, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC34246_________, ____L.4246_Load_Balancer_for_M3UA_LK________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC34242_________, ____L.4242_Load_Balancer_for_H.248_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31637_________, ____L.1637_IPDU_based_M3UA_LB_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC61381_________, ____L.1381_MSS_Camel_3_LK___________________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSING01, ____MSGLIC31531_________, ____L.1531_CSFB_Overlay_LK__________________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31433_________, ____L.1433_High_IO_Capacity_in_CHU__________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC34209_________, ____L.4209_CAMEL:SuppressT-CSI_in_SRI_LK____, ____Comcel, ____ACTIVE_UNLIMITED, ____1
MSSING01, ____MSGLIC34251_________, ____L.4251_Identical_IMEI_support_in_MSS_LK_, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC33323_________, ____L.3323_IN_Attribute_Analysis_LK_________, ____Comcel, ____ACTIVE_UNLIMITED, ____35000
MSSING01, ____MSGLIC61249_________, ____L.1249_MSS_Basic_SW_capacity_LK_________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSING01, ____MSGLIC61381_________, ____L.1381_MSS_Camel_3_LK___________________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSING01, ____MSGLIC64130_________, ____L.4130_LTE_SMS_over_SGS_I/F_LK__________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSING01, ____MSGLIC33392_________, ____L.3392_G.729A/B_Codec_in_MSS____________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31465_________, ____L.1465_DTMF_transport_over_RTP_in_MSS___, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31478_________, ____L.1478_Virtual_circuits_support_with_SIP, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____1
MSSING01, ____MSGLIC31465_________, ____L.1465_MSS_DTMF_transport_over_RTP_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____600000
MSSING01, ____MSGLIC31104_________, ____L.1104_Multiple-PLMN_Inter-PLMN_HO_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____1
MSSING01, ____MSGLIC63006_________, ____L.3006_SRVCC_capacity_license_LK________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____15000
MSSING01, ____MSGLIC34177_________, ____L.4177_CS_Allocation_and_Retention_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSING01, ____MSGLIC9014664_______, ____L.9014664_Resource_priority_mapping_MGCF, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
FEA MSSING01, ____1460, ____AoIP_TC_in_MGW_support__________________, ____ON, ____1, 
FEA MSSING01, ____1121, ____MSS_multiple_isolated_IP_networks_______, ____ON, ____1, 
FEA MSSING01, ____899, ____IUA_____________________________________, ____ON, ____1, 
FEA MSSING01, ____221, ____VLR_Subscriber_Capacity_________________, ____ON, ____3400000, 
FEA MSSING01, ____223, ____VLR_Camel_Ph4_Capacity__________________, ____ON, ____2000000, 
FEA MSSING01, ____467, ____MSC_CAMEL_Ph4_support___________________, ____ON, ____2000000, 
FEA MSSING01, ____1267, ____Iu_CS_interface_over_IP_________________, ____ON, ____1, 
FEA MSSING01, ____2298, ____Advanced_Location_Services______________, ____ON, ____1, 
FEA MSSING01, ____1691, ____SMS_support_in_SGs_interface____________, ____ON, ____2800000, 
FEA MSSING01, ____1462, ____SIP_load_balancer_______________________, ____ON, ____1, 
FEA MSSING01, ____2156, ____eMLPP___________________________________, ____ON, ____1, 
FEA MSSING01, ____1935, ____Full_CSFB_support_in_SGs_interface______, ____ON, ____1, 
FEA MSSING01, ____3440, ____CSMT_Flag_and_A_Iu_repaging_____________, ____ON, ____1, 
FEA MSSING01, ____3459, ____CS_Fallback_Release_9_Update____________, ____ON, ____1, 
FEA MSSING01, ____3496, ____CSFB_counter_enhancement________________, ____ON, ____1, 
FEA MSSING01, ____5444, ____CSFB_MT_Call_enhancement________________, ____ON, ____1, 
FEA MSSING01, ____19933, ____PSI_paging_over_SGs_for_national_roamers, ____ON, ____1, 
FEA MSSING01, ____4275, ____Balanced_distribution_of_SS7_traffic____, ____ON, ____1, 
FEA MSSING01, ____1473, ____H248_Load_Balancer_in_MSS_______________, ____ON, ____1, 
FEA MSSING01, ____3479, ____IPDU_based_M3UA_Load_Balancer___________, ____ON, ____1, 
FEA MSSING01, ____222, ____VLR_Camel_Ph3_Capacity__________________, ____ON, ____2800000, 
FEA MSSING01, ____466, ____MSC_CAMEL_Ph3_support___________________, ____ON, ____2800000, 
FEA MSSING01, ____3602, ____SGs_Overlay_MSS_support_________________, ____ON, ____1, 
FEA MSSING01, ____1040, ____Charging_block_writing_enhancement______, ____ON, ____1, 
FEA MSSING01, ____2201, ____CAMEL:_Suppress_T-CSI_in_SRI_based_on_ca, ____ON, ____1, 
FEA MSSING01, ____2165, ____Identical_IMEI_support_in_MSS___________, ____ON, ____1, 
FEA MSSING01, ____2152, ____IN_Attribute_Analysis___________________, ____ON, ____50000, 
FEA MSSING01, ____856, ____G.729A__________________________________, ____ON, ____1, 
FEA MSSING01, ____2265, ____CS_Allocation_and_Retention_(ARP)_______, ____ON, , 
FEA MSSING01, ____50036, ____Resource_priority_header_mapping_(Ph1)__, ____ON, , 
MSSING01: Closing..
MSSING01: Disconnected

############
# MSSARA02 #
############
ACCESING 5: MSSARA02
MSSARA02: Connected
MSSARA02: Connected
El acceso al MSS: MSSARA02 esta OK
MSSARA02, ____CMSSLK0600006000____, ____6000_MSS_Cloud_CapacityPack_capacity_LK_, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____5000000
MSSARA02, ____CMSSLK0600006005____, ____6005_CS_FallBack_capacity_LK____________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____5000000
MSSARA02, ____CMSSLK0300006005____, ____6005_CS_FallBack_on/off_LK______________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____5000000
MSSARA02, ____CMSSLK0300006011____, ____6011_Camel_on/off_LK____________________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSARA02, ____CMSSLK0300006015____, ____6015_Enhanced_subscriber_exp_on/off_LK__, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSARA02, ____CMSSLK0300006017____, ____6017_Multi_user_support_on/off_LK_______, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSARA02, ____CMSSLK0300006057____, ____6057_OLCM_on/off_LK_____________________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSARA02, ____CMSSLK0300006000____, ____6000_MSS_Cloud_Capacity_Pack_on/off_LK__, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSARA02, ____CMSSLK0300064209____, ____64209_CAMEL:SuppressT-CSI_on/off_CLK____, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
FEA MSSARA02, ____221, ____VLR_Subscriber_Capacity_________________, ____ON, ____5000000, 
FEA MSSARA02, ____224, ____VLR_Capacity_for_Super_Charger__________, ____ON, ____5000000, 
FEA MSSARA02, ____688, ____Video_Call_Forwarding_in_2G_____________, ____ON, ____5000000, 
FEA MSSARA02, ____1196, ____RNC_in_multiple_PLMN____________________, ____ON, ____5000000, 
FEA MSSARA02, ____1333, ____T38_in_MSS______________________________, ____ON, ____5000000, 
FEA MSSARA02, ____1433, ____Optimized_MGW_selection_over_SIPI_______, ____ON, ____5000000, 
FEA MSSARA02, ____3722, ____Extended_SA_and_Cell_capacity_in_MSS____, ____ON, ____5000000, 
FEA MSSARA02, ____3921, ____Extended_LA/RNC_capacity_in_MSS_________, ____ON, ____5000000, 
FEA MSSARA02, ____1691, ____SMS_support_in_SGs_interface____________, ____ON, ____5000000, 
FEA MSSARA02, ____1935, ____Full_CSFB_support_in_SGs_interface______, ____ON, ____5000000, 
FEA MSSARA02, ____223, ____VLR_Camel_Ph4_Capacity__________________, ____ON, ____5000000, 
FEA MSSARA02, ____466, ____MSC_CAMEL_Ph3_support___________________, ____ON, , 
FEA MSSARA02, ____467, ____MSC_CAMEL_Ph4_support___________________, ____ON, , 
FEA MSSARA02, ____3934, ____INSU_CDR_FOR_CAMEL______________________, ____ON, , 
FEA MSSARA02, ____583, ____MSC_Video_Ringback_Tone_support_________, ____ON, , 
FEA MSSARA02, ____1499, ____SRBT_for_A_party________________________, ____ON, , 
FEA MSSARA02, ____2088, ____Music_On_Hold___________________________, ____ON, , 
FEA MSSARA02, ____2261, ____IN_Controlled_Ring_Back_Tone_Service_(RB, ____ON, , 
FEA MSSARA02, ____2262, ____Multilingual_Announcements______________, ____ON, , 
FEA MSSARA02, ____2267, ____MSS_controlled_SRBT_____________________, ____ON, , 
FEA MSSARA02, ____4691, ____MSS_based_advertisement_service_________, ____ON, , 
FEA MSSARA02, ____1603, ____SMS_MULTISIM_HLR________________________, ____ON, , 
FEA MSSARA02, ____1656, ____SMS_MULTISIM_LDAP_______________________, ____ON, , 
FEA MSSARA02, ____2170, ____MultiSIM_Phase_3________________________, ____ON, , 
FEA MSSARA02, ____2264, ____Same_CLI_for_Multiple_Subscribers_______, ____ON, , 
FEA MSSARA02, ____3442, ____LDAP_based_common_CLI___________________, ____ON, , 
FEA MSSARA02, ____6155, ____Support_group_MSISDN_presenting_in_IDP__, ____ON, , 
FEA MSSARA02, ____468, ____Dynamic_Delivery_Function_Status________, ____ON, , 
FEA MSSARA02, ____571, ____OLCM_SFTP_Support_______________________, ____ON, , 
FEA MSSARA02, ____385, ____Enhanced_VLR_Filtering_and_Categorizing_, ____ON, , 
FEA MSSARA02, ____550, ____SIP_Protocol_Measurement________________, ____ON, , 
FEA MSSARA02, ____576, ____VMSC_Answer_Call_Ratio_Meas._in_MSS_____, ____ON, , 
FEA MSSARA02, ____585, ____HO_Number_Allocated_based_on_Loc._Area__, ____ON, , 
FEA MSSARA02, ____795, ____SGSN_Addresses_in_Several_Signalling_Net, ____ON, , 
FEA MSSARA02, ____796, ____PLMN_specific_SS-code_support_in_MSC/VLR, ____ON, , 
FEA MSSARA02, ____797, ____LU_per_LAC_Report_______________________, ____ON, , 
FEA MSSARA02, ____807, ____IN_UI_during_Call_Setup_________________, ____ON, , 
FEA MSSARA02, ____811, ____M3UA_Association_Set_Measurement________, ____ON, , 
FEA MSSARA02, ____844, ____Number_Modif_Enhancement_Capacity_______, ____ON, , 
FEA MSSARA02, ____845, ____Number_Modif._Enhancement_Activation____, ____ON, , 
FEA MSSARA02, ____855, ____G.723.1_________________________________, ____ON, , 
FEA MSSARA02, ____856, ____G.729A__________________________________, ____ON, , 
FEA MSSARA02, ____857, ____iLBC____________________________________, ____ON, , 
FEA MSSARA02, ____859, ____VMGW_TCAT_MEAS__________________________, ____ON, , 
FEA MSSARA02, ____899, ____IUA_____________________________________, ____ON, , 
FEA MSSARA02, ____910, ____Generate_CDR_for_CAP_Internal_UI________, ____ON, , 
FEA MSSARA02, ____911, ____Add_info_to_CDR_CAP_External_UI_________, ____ON, , 
FEA MSSARA02, ____912, ____ACM_CPG_Connects_CAP_External_IP________, ____ON, , 
FEA MSSARA02, ____957, ____M3UA_Load_Monitoring____________________, ____ON, , 
FEA MSSARA02, ____985, ____DX_200_DNS_host_file_MML_management_____, ____ON, , 
FEA MSSARA02, ____1016, ____MSS_Context_utilization_measurement_____, ____ON, , 
FEA MSSARA02, ____1025, ____SIP_over_SCTP_support___________________, ____ON, , 
FEA MSSARA02, ____1035, ____SIP_DTMF_codec__________________________, ____ON, , 
FEA MSSARA02, ____1038, ____Emergency_Call_Routing__________________, ____ON, , 
FEA MSSARA02, ____1039, ____Routing_Category_in_Backward_Release____, ____ON, , 
FEA MSSARA02, ____1040, ____Charging_block_writing_enhancement______, ____ON, , 
FEA MSSARA02, ____1057, ____IPSec_for_management_plane______________, ____ON, , 
FEA MSSARA02, ____1058, ____IPSec_for_control_plane_________________, ____ON, , 
FEA MSSARA02, ____1103, ____Extended_Alternative_Count______________, ____ON, , 
FEA MSSARA02, ____1121, ____MSS_multiple_isolated_IP_networks_______, ____ON, , 
FEA MSSARA02, ____1201, ____SCCP_load_sharing_across_128_point_codes, ____ON, , 
FEA MSSARA02, ____1215, ____SIP_virtual_circuit_support_____________, ____ON, , 
FEA MSSARA02, ____1248, ____Forced_Password_Change_After_First_Login, ____ON, , 
FEA MSSARA02, ____1267, ____Iu_CS_interface_over_IP_________________, ____ON, , 
FEA MSSARA02, ____1460, ____AoIP_TC_in_MGW_support__________________, ____ON, , 
FEA MSSARA02, ____1462, ____SIP_load_balancer_______________________, ____ON, , 
FEA MSSARA02, ____1473, ____H248_Load_Balancer_in_MSS_______________, ____ON, , 
FEA MSSARA02, ____1558, ____IP_Realm_IW_support_____________________, ____ON, , 
FEA MSSARA02, ____1657, ____A_party_CNAP____________________________, ____ON, , 
FEA MSSARA02, ____1698, ____B_party_CNAP_framework__________________, ____ON, , 
FEA MSSARA02, ____1780, ____IP_Realm_SLA_support____________________, ____ON, , 
FEA MSSARA02, ____1857, ____Out_of_band_DTMF_support_in_SIP_________, ____ON, , 
FEA MSSARA02, ____1878, ____Location_change_detection_______________, ____ON, , 
FEA MSSARA02, ____1879, ____Equipment_change_detection______________, ____ON, , 
FEA MSSARA02, ____1895, ____FRAUD_PREVENTION________________________, ____ON, , 
FEA MSSARA02, ____1955, ____Call_bases_G.711_encoding_law_in_MSS____, ____ON, , 
FEA MSSARA02, ____1963, ____Gateway_IP_address_supervision__________, ____ON, , 
FEA MSSARA02, ____1981, ____I_BTS_RNC_capacity_in_MSC_server________, ____ON, , 
FEA MSSARA02, ____2112, ____Call_Hold_Announcement_Suppression______, ____ON, , 
FEA MSSARA02, ____2127, ____Inband_DTMF_Suppression_________________, ____ON, , 
FEA MSSARA02, ____2152, ____IN_Attribute_Analysis___________________, ____ON, , 
FEA MSSARA02, ____2156, ____eMLPP___________________________________, ____ON, , 
FEA MSSARA02, ____2157, ____ICBNC_Load_Sharing______________________, ____ON, , 
FEA MSSARA02, ____2159, ____Call_Routing_Optimization_______________, ____ON, , 
FEA MSSARA02, ____2161, ____Multiple_OWN_GT_Addresses_______________, ____ON, , 
FEA MSSARA02, ____2163, ____Traffic_measurements_per_BSC/RNC________, ____ON, , 
FEA MSSARA02, ____2164, ____Extension_of_Routing_Object_Names_______, ____ON, , 
FEA MSSARA02, ____2165, ____Identical_IMEI_support_in_MSS___________, ____ON, , 
FEA MSSARA02, ____2168, ____Flexible_Analyses_______________________, ____ON, , 
FEA MSSARA02, ____2171, ____SIP_between_MSS_________________________, ____ON, , 
FEA MSSARA02, ____2172, ____Multiple-PLMN_and_Inter-PLMN_Handover_Su, ____ON, , 
FEA MSSARA02, ____2175, ____Handling_UE_Specific_Behavior___________, ____ON, , 
FEA MSSARA02, ____2176, ____Data_Retention_in_VLR___________________, ____ON, , 
FEA MSSARA02, ____2178, ____Support_of_A5/3_algorithm_______________, ____ON, , 
FEA MSSARA02, ____2187, ____Length_Based_Number_Formatting__________, ____ON, , 
FEA MSSARA02, ____2189, ____eCall_112_support_in_MSS________________, ____ON, , 
FEA MSSARA02, ____2194, ____A_or_ACPN_sent_to_PSTN_or_PBX___________, ____ON, , 
FEA MSSARA02, ____2196, ____CAMEL_Information_in_attribute_analysis_, ____ON, , 
FEA MSSARA02, ____2198, ____Advanced_IN_announcement_handling_______, ____ON, , 
FEA MSSARA02, ____2199, ____Call_Dur_Round_up_on_CAMEL_or_SINAP_____, ____ON, , 
FEA MSSARA02, ____2204, ____IMEISV_support__________________________, ____ON, , 
FEA MSSARA02, ____2221, ____PBX_Support_for_MSC_Server_and_MGW______, ____ON, , 
FEA MSSARA02, ____2225, ____MSS/IP_PBX_UNI__________________________, ____ON, , 
FEA MSSARA02, ____2229, ____Different_TTs_for_SMS_and_calls_________, ____ON, , 
FEA MSSARA02, ____2232, ____Priority_Handling_and_Routing_based_on_C, ____ON, , 
FEA MSSARA02, ____2234, ____Forbid_called_users_DTMF_transfer_______, ____ON, , 
FEA MSSARA02, ____2238, ____Immediate_CDR_Transfer_for_All_Subscribe, ____ON, , 
FEA MSSARA02, ____2240, ____Inter_MSC_Handover_Billing_Enhancement__, ____ON, , 
FEA MSSARA02, ____2241, ____Call_Duration_Round_up_in_CDR___________, ____ON, , 
FEA MSSARA02, ____2244, ____Subscriber_Segmentation_in_Dual_Band____, ____ON, , 
FEA MSSARA02, ____2246, ____2G_Subscriber_Access_Control_to_3G_Netwo, ____ON, , 
FEA MSSARA02, ____2247, ____VLR_filtering,_IMSI_list_to_file________, ____ON, , 
FEA MSSARA02, ____2248, ____Automatic_Device_Detection______________, ____ON, , 
FEA MSSARA02, ____2252, ____Service_Restriction_____________________, ____ON, , 
FEA MSSARA02, ____2258, ____Terminal_Management_Support_for_Nokia_Te, ____ON, , 
FEA MSSARA02, ____2259, ____Suppression_of_Divert_Indication________, ____ON, , 
FEA MSSARA02, ____2260, ____Exact_Mobile_Subscriber_Category________, ____ON, , 
FEA MSSARA02, ____2265, ____CS_Allocation_and_Retention_(ARP)_______, ____ON, , 
FEA MSSARA02, ____2266, ____Video_Audio_Fallback____________________, ____ON, , 
FEA MSSARA02, ____2294, ____Emergency_call_triggering_for_ETSI_marke, ____ON, , 
FEA MSSARA02, ____2295, ____New_clear_code_-_cause_code_mapping_due_, ____ON, , 
FEA MSSARA02, ____2296, ____LCS-ClientExternalID_support____________, ____ON, , 
FEA MSSARA02, ____2297, ____Privacy_and_deferred_MT-LR_support______, ____ON, , 
FEA MSSARA02, ____2298, ____Advanced_Location_Services______________, ____ON, , 
FEA MSSARA02, ____2303, ____Comfort_Message_________________________, ____ON, , 
FEA MSSARA02, ____2304, ____Comfort_Tone____________________________, ____ON, , 
FEA MSSARA02, ____2308, ____Subscribers_per_LAC_enhancements________, ____ON, , 
FEA MSSARA02, ____2309, ____Video_Call_Statistics___________________, ____ON, , 
FEA MSSARA02, ____2312, ____Call_Transfer_Supplement_Kit____________, ____ON, , 
FEA MSSARA02, ____2314, ____IM_CN_-_CS_Interworking_________________, ____ON, , 
FEA MSSARA02, ____2317, ____SDP-less_INVITE_for_3PCC________________, ____ON, , 
FEA MSSARA02, ____3153, ____Automatic_Call_Rerouting________________, ____ON, , 
FEA MSSARA02, ____3179, ____SIP_History_Info________________________, ____ON, , 
FEA MSSARA02, ____3207, ____Enhancement_to_Subscriber_Data_Feed_____, ____ON, , 
FEA MSSARA02, ____3208, ____SMS_Paging_Enhancement_SMSMT_and_LUP____, ____ON, , 
FEA MSSARA02, ____3279, ____Congestion_counter_in_CGR_measurement___, ____ON, , 
FEA MSSARA02, ____3284, ____DYNAMIC_PAYLOAD_NUMBER_BLACK_LIST_______, ____ON, , 
FEA MSSARA02, ____3458, ____Skip_ACM_after_CONNECT__________________, ____ON, , 
FEA MSSARA02, ____3479, ____IPDU_based_M3UA_Load_Balancer___________, ____ON, , 
FEA MSSARA02, ____3489, ____ADD_LAC_CI_TO_ASN_______________________, ____ON, , 
FEA MSSARA02, ____3727, ____Traffic_Category_Measurement_Enhancement, ____ON, , 
FEA MSSARA02, ____3746, ____TRANSIT_CHU_BYPASS_LIC__________________, ____ON, , 
FEA MSSARA02, ____4275, ____Balanced_distribution_of_SS7_traffic____, ____ON, , 
FEA MSSARA02, ____4671, ____Digit_analysis_integrity_check__________, ____ON, , 
FEA MSSARA02, ____4696, ____Collect_Call_interworking_with_NVS______, ____ON, , 
FEA MSSARA02, ____5163, ____Mapping_between_ICID_and_GCR____________, ____ON, , 
FEA MSSARA02, ____18142, ____A5_3_algorithm_support_enhancement______, ____ON, , 
FEA MSSARA02, ____2201, ____CAMEL:_Suppress_T-CSI_in_SRI_based_on_ca, ____ON, , 
MSSARA02: Closing..
MSSARA02: Disconnected

############
# MSSVEN01 #
############
ACCESING 6: MSSVEN01
MSSVEN01: Connected
MSSVEN01: Connected
El acceso al MSS: MSSVEN01 esta OK
MSSVEN01, ____MSGLIC61384_________, ____L.1384_MSS_Camel_4_LK___________________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC61381_________, ____L.1381_MSS_Camel_3_LK___________________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC64130_________, ____L.4130_LTE_SMS_over_SGS_I/F_LK__________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC61249_________, ____L.1249_MSS_Basic_SW_capacity_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____2000000
MSSVEN01, ____MSGLIC31322_________, ____L.1322_eMLPP_LK_________________________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____C.1249______________, ____L.1637_IPDU_based_M3UA_LB_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34242_________, ____L.4242_Load_Balancer_for_H.248_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34241_________, ____L.4241_Load_Balancer_for_SIP_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34715_________, ____L.4715_Advanced_Location_Services_LK____, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31614_________, ____L.1614_Balanced_Signalling_Traffic_LK___, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31660_________, ____L.1660_SRVCC_for_held_calls_LK__________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____1
MSSVEN01, ____MSGLIC31531_________, ____L.1531_CSFB_Overlay_LK__________________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31443_________, ____L.1443_MSS_IP_Based_Iu-CS_Interface_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31326_________, ____L.1326_Multipoint_A-interface_LK________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31312_________, ____L.1312_Multipoint_Iu-interface_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31470_________, ____L.1470_Multipoint_Adv_KIT_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34247_________, ____L.4247_MSS_A_over_IP_with_TC_in_MGW_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31470_________, ____L.1470_Multipoint_Adv_KIT_LK____________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31326_________, ____L.1326_Multipoint_A-interface_LK________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34247_________, ____L.4247_MSS_A_over_IP_with_TC_in_MGW_LK__, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31421_________, ____L.1421_MSS_Multiple_Isolated_IP_NW_LK___, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31416_________, ____L.1416_PBX_Support_Using_IUA_LK_________, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31312_________, ____L.1312_Multipoint_Iu-interface_LK_______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31404_________, ____L.1404_VLR_filtering,_IMSI_list_LK______, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC34251_________, ____L.4251_Identical_IMEI_support_in_MSS_LK_, ____Comcel, ____ACTIVE_LIMITED, ____1
MSSVEN01, ____MSGLIC31530_________, ____L.1530_SGs_I/F_voice_conncetivity_LK____, ____Comcel, ____ACTIVE_UNLIMITED, ____50000
MSSVEN01, ____MSGLIC61381_________, ____L.1381_MSS_Camel_3_LK___________________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSVEN01, ____MSGLIC61249_________, ____L.1249_MSS_Basic_SW_capacity_LK_________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSVEN01, ____MSGLIC64130_________, ____L.4130_LTE_SMS_over_SGS_I/F_LK__________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____800000
MSSVEN01, ____MSGLIC31104_________, ____L.1104_Multiple-PLMN_Inter-PLMN_HO_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, ____1
MSSVEN01, ____MSGLIC63006_________, ____L.3006_SRVCC_capacity_license_LK________, ____COMCEL_S.A., ____ACTIVE_LIMITED, ____20000
MSSVEN01, ____MSGLIC33392_________, ____L.3392_MSS_G.729AB_Codec_LK_____________, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN01, ____MSGLIC34177_________, ____L.4177_CS_Allocation_and_Retention_LK___, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
MSSVEN01, ____MSGLIC9014664_______, ____L.9014664_Resource_priority_mapping_MGCF, ____COMCEL_S.A., ____ACTIVE_UNLIMITED, 
FEA MSSVEN01, ____223, ____VLR_Camel_Ph4_Capacity__________________, ____ON, ____2000000, 
FEA MSSVEN01, ____467, ____MSC_CAMEL_Ph4_support___________________, ____ON, ____2000000, 
FEA MSSVEN01, ____222, ____VLR_Camel_Ph3_Capacity__________________, ____ON, ____2800000, 
FEA MSSVEN01, ____466, ____MSC_CAMEL_Ph3_support___________________, ____ON, ____2800000, 
FEA MSSVEN01, ____1691, ____SMS_support_in_SGs_interface____________, ____ON, ____2800000, 
FEA MSSVEN01, ____221, ____VLR_Subscriber_Capacity_________________, ____ON, ____2800000, 
FEA MSSVEN01, ____2156, ____eMLPP___________________________________, ____ON, ____1, 
FEA MSSVEN01, ____3479, ____IPDU_based_M3UA_Load_Balancer___________, ____ON, ____1, 
FEA MSSVEN01, ____1473, ____H248_Load_Balancer_in_MSS_______________, ____ON, ____1, 
FEA MSSVEN01, ____1462, ____SIP_load_balancer_______________________, ____ON, ____1, 
FEA MSSVEN01, ____2298, ____Advanced_Location_Services______________, ____ON, ____1, 
FEA MSSVEN01, ____4275, ____Balanced_distribution_of_SS7_traffic____, ____ON, ____1, 
FEA MSSVEN01, ____4574, ____MSC_server_Assisted_mid-call_feature_sup, ____ON, ____1, 
FEA MSSVEN01, ____1267, ____Iu_CS_interface_over_IP_________________, ____ON, ____1, 
FEA MSSVEN01, ____1460, ____AoIP_TC_in_MGW_support__________________, ____ON, ____2, 
FEA MSSVEN01, ____1121, ____MSS_multiple_isolated_IP_networks_______, ____ON, ____1, 
FEA MSSVEN01, ____899, ____IUA_____________________________________, ____ON, ____1, 
FEA MSSVEN01, ____2247, ____VLR_filtering,_IMSI_list_to_file________, ____ON, ____1, 
FEA MSSVEN01, ____2165, ____Identical_IMEI_support_in_MSS___________, ____ON, ____1, 
FEA MSSVEN01, ____3496, ____CSFB_counter_enhancement________________, ____ON, ____70000, 
FEA MSSVEN01, ____2172, ____Multiple-PLMN_and_Inter-PLMN_Handover_Su, ____ON, ____1, 
FEA MSSVEN01, ____856, ____G.729A__________________________________, ____ON, , 
FEA MSSVEN01, ____2265, ____CS_Allocation_and_Retention_(ARP)_______, ____ON, , 
FEA MSSVEN01, ____50036, ____Resource_priority_header_mapping_(Ph1)__, ____ON, , 
MSSVEN01: Closing..
MSSVEN01: Disconnected

Hora inicio de macro: 2023-11-02  11:11:20
Hora fin de macro: 2023-11-02  11:12:10
FIN: Macro ejecutada