Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\65_oMSS_routes\oMSS_routes_.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\65_oMSS_routes\oMSS_routes_.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\65_oMSS_routes\oMSS_routes_.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\65_oMSS_routes\oMSS_routes_.tel', line 2 
   Variable 'FLAG' declared but its value is never used

Got no compile errors.

