Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\47_oMSS_sccp_parameter_set\oMSS_sccp_parameter_set.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\47_oMSS_sccp_parameter_set\oMSS_sccp_parameter_set.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\47_oMSS_sccp_parameter_set\oMSS_sccp_parameter_set.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
######################
# sccp_parameter_set #
######################
ZOCI;
1*- SET NUMBER: 00000       SET NAME: BLUE 
2*- SET NUMBER: 00001       SET NAME: A-INT
3*- SET NUMBER: 00002       SET NAME: WHITE
4*- SET NUMBER: 00003       SET NAME: 3GPAR
5*- SET NUMBER: 00004       SET NAME: 3GHOP
6*- SET NUMBER: 00005       SET NAME: GMLC 
7*- SET NUMBER: 00006       SET NAME: AMGW 
ZOCJ;
1*- SET NUMBER: 00000       SET NAME: GENER
2*- SET NUMBER: 00001       SET NAME: A-INT
FIN!!!!