Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\62_oMSS_special_routes__hlr_enquiry\oMSS_special_routes__hlr_enquiry_.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\62_oMSS_special_routes__hlr_enquiry\oMSS_special_routes__hlr_enquiry_.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\62_oMSS_special_routes__hlr_enquiry\oMSS_special_routes__hlr_enquiry_.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\62_oMSS_special_routes__hlr_enquiry\oMSS_special_routes__hlr_enquiry_.tel', line 2 
   Variable 'FLAG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\62_oMSS_special_routes__hlr_enquiry\oMSS_special_routes__hlr_enquiry_.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\62_oMSS_special_routes__hlr_enquiry\oMSS_special_routes__hlr_enquiry_.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
################################
# special_routes__hlr_enquiry_ #
################################
ZRPI:SRT=HLRENQ;

LOADING PROGRAM VERSION 26.5-0

 SPECIAL ROUTE FOR HLR ENQUIRY

 SPR     STP  NETWORK      SIGNALLING          TREE  CORG     CLI ORII
                           POINT CODE
 00002    1   NA0               -              00000   0      OFF OFF 

         STPAP       STCSI  SSSET 

         NOT EXIST   OFF    OFF   


 SPR     STP  NETWORK      SIGNALLING          TREE  CORG     CLI ORII
                           POINT CODE
 00035    1   NA0               -              00000   0      OFF OFF 

         STPAP       STCSI  SSSET 

         NOT EXIST   ON     OFF   


 SPR     STP  NETWORK      SIGNALLING          TREE  CORG     CLI ORII
                           POINT CODE
 00099    4   NA0               -              00000   0      OFF OFF 

         STPAP       STCSI  SSSET 

         NOT EXIST   OFF    OFF   



COMMAND EXECUTED


GSM SPECIAL ROUTE HANDLING COMMAND <RP_>
<  FIN!!!!