Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\103_oMSS_outgoing_call_barring_analysis\oMSS_outgoing_call_barring_analysis.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\103_oMSS_outgoing_call_barring_analysis\oMSS_outgoing_call_barring_analysis.tel', line 2 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\103_oMSS_outgoing_call_barring_analysis\oMSS_outgoing_call_barring_analysis.tel', line 3 
   Variable 'z' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Already connected
############
# MSSARA02 #
############
##################################
# outgoing_call_barring_analysis #
##################################
BAOC    
BOIC    
BOIH    
BOS4    
BOS2    
BOS1    
BAOC    
BOIC    
BOIH    
Existen %d tuplas
FIN!!!!