Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Productivos_CGR_Circuits\oMSS_MSS_Proctivos_CGR_Circuitos.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Productivos_CGR_Circuits\oMSS_MSS_Proctivos_CGR_Circuitos.tel', line 2 
   Variable 'GT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Productivos_CGR_Circuits\oMSS_MSS_Proctivos_CGR_Circuitos.tel', line 20 
   Variable 'RES' declared but its value is never used
Code generation...

Got no compile errors.

############
# MSS04VEN #
############
ACCESING 24: MSS04VEN
MSS04VEN: Connected
MSS04VEN: Connected
CGR: 2880
MSS04VEN: Closing..
MSS04VEN: Disconnected
############
# MSS05ARA #
############
ACCESING 25: MSS05ARA
MSS05ARA: Connected
MSS05ARA: Connected
MSS05ARA: Closing..
MSS05ARA: Disconnected
############
# MSS05MED #
############
ACCESING 26: MSS05MED
MSS05MED: Connected
MSS05MED: Connected
CGR: 2880
MSS05MED: Closing..
MSS05MED: Disconnected
############
# MSS05VEN #
############
ACCESING 27: MSS05VEN
MSS05VEN: Connected
MSS05VEN: Connected
CGR: 2880
MSS05VEN: Closing..
MSS05VEN: Disconnected
############
# MSS06ARA #
############
ACCESING 28: MSS06ARA
MSS06ARA: Connected
MSS06ARA: Connected
CGR: 2880
MSS06ARA: Closing..
MSS06ARA: Disconnected
############
# MSS06MED #
############
ACCESING 29: MSS06MED
MSS06MED: Connected
MSS06MED: Connected
CGR: 2880
MSS06MED: Closing..
MSS06MED: Disconnected
############
# MSS06VEN #
############
ACCESING 30: MSS06VEN
MSS06VEN: Connected
MSS06VEN: Connected
CGR: 2880
MSS06VEN: Closing..
MSS06VEN: Disconnected
############
# MSS07ARA #
############
ACCESING 31: MSS07ARA
MSS07ARA: Connected
MSS07ARA: Connected
CGR: 2880
MSS07ARA: Closing..
MSS07ARA: Disconnected
############
# MSS07VEN #
############
ACCESING 32: MSS07VEN
MSS07VEN: Connected
MSS07VEN: Connected
CGR: 2880
MSS07VEN: Closing..
MSS07VEN: Disconnected
############
# MSSALK01 #
############
ACCESING 33: MSSALK01
MSSALK01: Connected
MSSALK01: Connected
CGR: 2880
MSSALK01: Closing..
MSSALK01: Disconnected
############
# MSSALK02 #
############
ACCESING 34: MSSALK02
MSSALK02: Connected
MSSALK02: Connected
CGR: 2880
MSSALK02: Closing..
MSSALK02: Disconnected
############
# MSSARA01 #
############
ACCESING 35: MSSARA01
MSSARA01: Connected
MSSARA01: Connected
CGR: 2880
MSSARA01: Closing..
MSSARA01: Disconnected
############
# MSSBUC01 #
############
ACCESING 36: MSSBUC01
MSSBUC01: Connected
MSSBUC01: Connected
CGR: 2880
MSSBUC01: Closing..
MSSBUC01: Disconnected
############
# MSSING01 #
############
ACCESING 37: MSSING01
MSSING01: Connected
MSSING01: Connected
CGR: 2880
MSSING01: Closing..
MSSING01: Disconnected
############
# MSSMAR01 #
############
ACCESING 38: MSSMAR01
MSSMAR01: Connected
MSSMAR01: Connected
CGR: 2880
MSSMAR01: Closing..
MSSMAR01: Disconnected
############
# MSSMGA01 #
############
ACCESING 39: MSSMGA01
MSSMGA01: Connected
MSSMGA01: Connected
CGR: 2880
MSSMGA01: Closing..
MSSMGA01: Disconnected
############
# MSSPER01 #
############
ACCESING 40: MSSPER01
MSSPER01: Connected
MSSPER01: Connected
CGR: 2880
MSSPER01: Closing..
MSSPER01: Disconnected
############
# MSSTRI01 #
############
ACCESING 41: MSSTRI01
MSSTRI01: Connected
MSSTRI01: Connected
CGR: 2880
MSSTRI01: Closing..
MSSTRI01: Disconnected
############
# MSSTRI02 #
############
ACCESING 42: MSSTRI02
MSSTRI02: Connected
MSSTRI02: Connected
CGR: 2880
MSSTRI02: Closing..
MSSTRI02: Disconnected
############
# MSSTRI03 #
############
ACCESING 43: MSSTRI03
MSSTRI03: Connected
MSSTRI03: Connected
CGR: 2880
MSSTRI03: Closing..
MSSTRI03: Disconnected
############
# MSSVEN01 #
############
ACCESING 44: MSSVEN01
MSSVEN01: Connected
MSSVEN01: Connected
Prompt not found, sending 1. revival...
Sending <\r>
Prompt not found, sending 2. revival...
Sending <\r>
Prompt not found, sending 3. revival...
Sending <\r>
Prompt not found, sending 4. revival...
Sending <CTRL-C>
Sending <CTRL-Y>
MSSVEN01: Closing..
MSSVEN01: Disconnected
############
# MSSMGA02 #
############
ACCESING 45: MSSMGA02
MSSMGA02: Connected
MSSMGA02: Connected
CGR: 2880
MSSMGA02: Closing..
MSSMGA02: Disconnected
############
# MSS01ALK #
############
ACCESING 46: MSS01ALK
MSS01ALK: Connected
MSS01ALK: Connected
CGR: 2880
MSS01ALK: Closing..
MSS01ALK: Disconnected
Hora inicio de macro: 2022-11-01  19:14:04
Hora fin de macro: 2022-11-01  19:19:51
FIN!!!!