Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\90_oMSS_change_unit_info\oMSS_change_unit_info.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\90_oMSS_change_unit_info\oMSS_change_unit_info.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\90_oMSS_change_unit_info\oMSS_change_unit_info.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\90_oMSS_change_unit_info\oMSS_change_unit_info.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Connected
MSSING02: Connected
############
# MSSING02 #
############
####################
# change_unit_info #
####################
FIN!!!!