Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS GoLive\oMSS_GoLive.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSARA02: Already connected

############
# MSSARA02 #
############

#########
# CDR's #
#########

##########################
# CHU-0: CDR'S & WDU/VDU #
##########################
CHU: 0 existen 2000 files trasferred
WDU-00  WO-BU    -                    - 
WDU-01  WO-BU    -                    - 
VDS-00  WO-BU    -                    - 
VDS-01  WO-BU    -                    - 
VDS-02  WO-BU    -                    - 
VDS-03  WO-BU    -                    - 
VDS-04  WO-BU    -                    - 
VDS-05  WO-BU    -                    - 
VDS-06  WO-BU    -                    - 
VDS-07  WO-BU    -                    - 
VDS-08  WO-BU    -                    - 
VDS-09  WO-BU    -                    - 
VDS-10  WO-BU    -                    - 
VDS-11  WO-BU    -                    - 
VDS-12  WO-BU    -                    - 
VDS-13  WO-BU    -                    - 
VDS-14  WO-BU    -                    - 
VDS-15  WO-BU    -                    - 

##########################
# CHU-1: CDR'S & WDU/VDU #
##########################
CHU: 1 existen 2000 files trasferred
WDU-00  WO-BU    -                    - 
WDU-01  WO-BU    -                    - 
VDS-00  WO-BU    -                    - 
VDS-01  WO-BU    -                    - 
VDS-02  WO-BU    -                    - 
VDS-03  WO-BU    -                    - 
VDS-04  WO-BU    -                    - 
VDS-05  WO-BU    -                    - 
VDS-06  WO-BU    -                    - 
VDS-07  WO-BU    -                    - 
VDS-08  WO-BU    -                    - 
VDS-09  WO-BU    -                    - 
VDS-10  WO-BU    -                    - 
VDS-11  WO-BU    -                    - 
VDS-12  WO-BU    -                    - 
VDS-13  WO-BU    -                    - 
VDS-14  WO-BU    -                    - 
VDS-15  WO-BU    -                    - 

##########################
# CHU-2: CDR'S & WDU/VDU #
##########################
CHU: 2 existen 2000 files trasferred
WDU-00  WO-BU    -                    - 
WDU-01  WO-BU    -                    - 
VDS-00  WO-BU    -                    - 
VDS-01  WO-BU    -                    - 
VDS-02  WO-BU    -                    - 
VDS-03  WO-BU    -                    - 
VDS-04  WO-BU    -                    - 
VDS-05  WO-BU    -                    - 
VDS-06  WO-BU    -                    - 
VDS-07  WO-BU    -                    - 
VDS-08  WO-BU    -                    - 
VDS-09  WO-BU    -                    - 
VDS-10  WO-BU    -                    - 
VDS-11  WO-BU    -                    - 
VDS-12  WO-BU    -                    - 
VDS-13  WO-BU    -                    - 
VDS-14  WO-BU    -                    - 
VDS-15  WO-BU    -                    - 

##########################
# CHU-3: CDR'S & WDU/VDU #
##########################
CHU: 3 existen 2000 files trasferred
WDU-00  WO-BU    -                    - 
WDU-01  WO-BU    -                    - 
VDS-00  WO-BU    -                    - 
VDS-01  WO-BU    -                    - 
VDS-02  WO-BU    -                    - 
VDS-03  WO-BU    -                    - 
VDS-04  WO-BU    -                    - 
VDS-05  WO-BU    -                    - 
VDS-06  WO-BU    -                    - 
VDS-07  WO-BU    -                    - 
VDS-08  WO-BU    -                    - 
VDS-09  WO-BU    -                    - 
VDS-10  WO-BU    -                    - 
VDS-11  WO-BU    -                    - 
VDS-12  WO-BU    -                    - 
VDS-13  WO-BU    -                    - 
VDS-14  WO-BU    -                    - 
VDS-15  WO-BU    -                    - 

MACRO IS OVER

