Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_CGRoMSS_Remotos_Origen\oMSS_MSS_Revision_de_CGR_en_MSS_extremo_lejano_hacia_nuevo_MSS.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
MSSING02 Colecting CGR's Information: Name, Ckts, CGR Stat
MSSING02 Colecting CGR's OPC
##############################################
CGR: 2602 CGR-NAME: IPI23ARA CKTS: 1054 SPC: 07DE CGR-STAT: WO-EX
CGR: 2603 CGR-NAME: IPI24ARA CKTS: 1054 SPC: 07E1 CGR-STAT: WO-EX
CGR: 2604 CGR-NAME: IPI25ARA CKTS: 310 SPC: 07AF CGR-STAT: WO-EX
CGR: 2605 CGR-NAME: IPI26ARA CKTS: 620 SPC: 07B4 CGR-STAT: WO-EX
CGR: 2606 CGR-NAME: IPI27ARA CKTS: 620 SPC: 07B9 CGR-STAT: WO-EX
CGR: 2611 CGR-NAME: IPI22VEA CKTS: 1024 SPC: 0796 CGR-STAT: WO-EX
CGR: 2612 CGR-NAME: IPI23VEA CKTS: 1024 SPC: 0794 CGR-STAT: WO-EX
CGR: 2613 CGR-NAME: IPI24VEA CKTS: 1024 SPC: 0791 CGR-STAT: WO-EX
CGR: 2614 CGR-NAME: IPI25VEA CKTS: 1024 SPC: 0709 CGR-STAT: WO-EX
CGR: 2615 CGR-NAME: IPI26VEA CKTS: 1024 SPC: 072B CGR-STAT: WO-EX
CGR: 2616 CGR-NAME: IPI27VEA CKTS: 1024 SPC: 072C CGR-STAT: WO-EX
CGR: 2621 CGR-NAME: IPI22BUA CKTS: 1024 SPC: 1FCD CGR-STAT: WO-EX
CGR: 2623 CGR-NAME: IPI21TOA CKTS: 1024 SPC: 07BB CGR-STAT: WO-EX
CGR: 2624 CGR-NAME: IPI22TOA CKTS: 1024 SPC: 07BE CGR-STAT: WO-EX
CGR: 2625 CGR-NAME: IPI23PRA CKTS: 1024 SPC: 0761 CGR-STAT: WO-EX
CGR: 2630 CGR-NAME: IPI22CLA CKTS: 2048 SPC: 0BC7 CGR-STAT: WO-EX
CGR: 2631 CGR-NAME: IPI23CLA CKTS: 2048 SPC: 0BCA CGR-STAT: WO-EX
CGR: 2632 CGR-NAME: IPI24CLA CKTS: 2048 SPC: 0BE7 CGR-STAT: WO-EX
CGR: 2633 CGR-NAME: IPI21INA CKTS: 2048 SPC: 0BEA CGR-STAT: WO-EX
CGR: 2635 CGR-NAME: IPI21PEA CKTS: 2048 SPC: 1BC4 CGR-STAT: WO-EX
CGR: 2636 CGR-NAME: IPI22PEA CKTS: 2048 SPC: 1BC6 CGR-STAT: WO-EX
CGR: 2640 CGR-NAME: IPI22MEA CKTS: 2048 SPC: 03C5 CGR-STAT: WO-EX
CGR: 2641 CGR-NAME: IPI23MEA CKTS: 2048 SPC: 03C8 CGR-STAT: WO-EX
CGR: 2643 CGR-NAME: IPI25MEA CKTS: 2048 SPC: 03E2 CGR-STAT: WO-EX
CGR: 2644 CGR-NAME: IPI26MEA CKTS: 2048 SPC: 03E7 CGR-STAT: BA-SY
CGR: 2651 CGR-NAME: IPI23BAA CKTS: 2048 SPC: 17C1 CGR-STAT: WO-EX
CGR: 2653 CGR-NAME: IPI21AKA CKTS: 1024 SPC: 17EA CGR-STAT: WO-EX
CGR: 2654 CGR-NAME: IPI22AKA CKTS: 1024 SPC: 17ED CGR-STAT: WO-EX
CGR: 2655 CGR-NAME: IPI21CAA CKTS: 1024 SPC: 17DE CGR-STAT: WO-EX
CGR: 2656 CGR-NAME: IPI21SIA CKTS: 1024 SPC: 1551 CGR-STAT: WO-EX
CGR: 2657 CGR-NAME: IPI22SIA CKTS: 1 SPC: 1556 CGR-STAT: BA-SY
CGR: 2800 CGR-NAME: IPI2AR1A CKTS: 2048 SPC: 06A0 CGR-STAT: WO-EX
CGR: 2820 CGR-NAME: IPI2VE1A CKTS: 2048 SPC: 06A3 CGR-STAT: WO-EX
CGR: 2830 CGR-NAME: IPI2TR1A CKTS: 2048 SPC: 0727 CGR-STAT: WO-EX
CGR: 2831 CGR-NAME: IPI2TR2A CKTS: 2048 SPC: 072F CGR-STAT: WO-EX
CGR: 2840 CGR-NAME: IPI2BU1A CKTS: 2048 SPC: 1FD6 CGR-STAT: WO-EX
CGR: 2850 CGR-NAME: IPI2MG1A CKTS: 2048 SPC: 03EC CGR-STAT: WO-EX
CGR: 2854 CGR-NAME: IPI2MG2A CKTS: 2048 SPC: 03EA CGR-STAT: WO-EX
CGR: 2858 CGR-NAME: IPI2TR3A CKTS: 2048 SPC: 07C8 CGR-STAT: WO-EX
CGR: 2859 CGR-NAME: IPI2AR2A CKTS: 2048 SPC: 07B2 CGR-STAT: WO-EX
CGR: 2860 CGR-NAME: IPI2IN1A CKTS: 2048 SPC: 082D CGR-STAT: WO-EX
CGR: 2870 CGR-NAME: IPI2PE1A CKTS: 2048 SPC: 1BCE CGR-STAT: WO-EX
CGR: 2884 CGR-NAME: IPI2VE2A CKTS: 2048 SPC: 07A7 CGR-STAT: WO-EX
CGR: 2890 CGR-NAME: IPI2AK1A CKTS: 1024 SPC: 17B2 CGR-STAT: WO-EX
CGR: 2891 CGR-NAME: IPI2AK2A CKTS: 2048 SPC: 17C3 CGR-STAT: WO-EX
CGR: 2910 CGR-NAME: IPI2MA1A CKTS: 1024 SPC: 3C4A CGR-STAT: WO-EX
MSSING02 Colecting OWN OPC

MSS_ORIGEN: MSIN2 SPC: 099A
############
# MSS01ING #
############
ACCESING 1: MSS01ING
MSS01ING: Connecting...
MSS01ING: Connected
Acceso probado a MSS: MSS01ING
MSS01ING Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**************************************************************
CGR 2855 SPC 099A
****MSS: MSS01ING Colecting OPC 

MSS_REMOTO: MSIN1 SPC: 0BEA
MSS: MSS01ING CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS01ING: Closing..
MSS01ING: Disconnected
############
# MSS01PER #
############
ACCESING 2: MSS01PER
MSS01PER: Connecting...
MSS01PER: Connected
Acceso probado a MSS: MSS01PER
MSS01PER Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************
CGR 2855 SPC 099A
****MSS: MSS01PER Colecting OPC 

MSS_REMOTO: MSPE1 SPC: 1BC4
MSS: MSS01PER CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS01PER: Closing..
MSS01PER: Disconnected
############
# MSS01SIN #
############
ACCESING 3: MSS01SIN
MSS01SIN: Connecting...
MSS01SIN: Connected
Acceso probado a MSS: MSS01SIN
MSS01SIN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************************
CGR 2855 SPC 099A
*****MSS: MSS01SIN Colecting OPC 

MSS_REMOTO: MSSI1 SPC: 1551
MSS: MSS01SIN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS01SIN: Closing..
MSS01SIN: Disconnected
############
# MSS01TOB #
############
ACCESING 4: MSS01TOB
MSS01TOB: Connecting...
MSS01TOB: Connected
Acceso probado a MSS: MSS01TOB
MSS01TOB Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
***********************************************************
CGR 2855 SPC 099A
*****MSS: MSS01TOB Colecting OPC 

MSS_REMOTO: MSTO1 SPC: 07BB
MSS: MSS01TOB CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS01TOB: Closing..
MSS01TOB: Disconnected
############
# MSS02ALK #
############
ACCESING 5: MSS02ALK
MSS02ALK: Connecting...
MSS02ALK: Connected
Acceso probado a MSS: MSS02ALK
MSS02ALK Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************
CGR 2855 SPC 099A
******MSS: MSS02ALK Colecting OPC 

MSS_REMOTO: MSAK2 SPC: 17ED
MSS: MSS02ALK CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS02ALK: Closing..
MSS02ALK: Disconnected
############
# MSS02BUC #
############
ACCESING 6: MSS02BUC
MSS02BUC: Connecting...
MSS02BUC: Connected
Acceso probado a MSS: MSS02BUC
MSS02BUC Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************
CGR 2855 SPC 099A
*****MSS: MSS02BUC Colecting OPC 

MSS_REMOTO: MSBU2 SPC: 1FCD
MSS: MSS02BUC CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS02BUC: Closing..
MSS02BUC: Disconnected
############
# MSS02CAL #
############
ACCESING 7: MSS02CAL
MSS02CAL: Connecting...
MSS02CAL: Connected
Acceso probado a MSS: MSS02CAL
MSS02CAL Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************************
CGR 2855 SPC 099A
*****MSS: MSS02CAL Colecting OPC 

MSS_REMOTO: MSCA2 SPC: 0BC7
MSS: MSS02CAL CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS02CAL: Closing..
MSS02CAL: Disconnected
############
# MSS02MED #
############
ACCESING 8: MSS02MED
MSS02MED: Connecting...
MSS02MED: Connected
Acceso probado a MSS: MSS02MED
MSS02MED Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**************************************************************
CGR 2855 SPC 099A
*****MSS: MSS02MED Colecting OPC 

MSS_REMOTO: MSME2 SPC: 03C5
MSS: MSS02MED CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS02MED: Closing..
MSS02MED: Disconnected
############
# MSS02PER #
############
ACCESING 9: MSS02PER
MSS02PER: Connecting...
MSS02PER: Connected
Acceso probado a MSS: MSS02PER
MSS02PER Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************
CGR 2855 SPC 099A
*****MSS: MSS02PER Colecting OPC 

MSS_REMOTO: MSPE2 SPC: 1BC6
MSS: MSS02PER CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS02PER: Closing..
MSS02PER: Disconnected
############
# MSS02TOB #
############
ACCESING 10: MSS02TOB
MSS02TOB: Connecting...
MSS02TOB: Connected
Acceso probado a MSS: MSS02TOB
MSS02TOB Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**************************************************************
CGR 2855 SPC 099A
****MSS: MSS02TOB Colecting OPC 

MSS_REMOTO: MSTO2 SPC: 07BE
MSS: MSS02TOB CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS02TOB: Closing..
MSS02TOB: Disconnected
############
# MSS02VEN #
############
ACCESING 11: MSS02VEN
MSS02VEN: Connecting...
MSS02VEN: Connected
Acceso probado a MSS: MSS02VEN
MSS02VEN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**************************************************************
CGR 2855 SPC 099A
******MSS: MSS02VEN Colecting OPC 

MSS_REMOTO: MSVE2 SPC: 0796
MSS: MSS02VEN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS02VEN: Closing..
MSS02VEN: Disconnected
############
# MSS03ARA #
############
ACCESING 12: MSS03ARA
MSS03ARA: Connecting...
MSS03ARA: Connected
Acceso probado a MSS: MSS03ARA
MSS03ARA Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**********************************************************
CGR 2855 SPC 099A
******MSS: MSS03ARA Colecting OPC 

MSS_REMOTO: MSAR3 SPC: 07DE
MSS: MSS03ARA CGR 2855 CGR_STAT WO-EX CKT_TOT: 1054 CKTS_OOS: 0 
MSS03ARA: Closing..
MSS03ARA: Disconnected
############
# MSS03BAR #
############
ACCESING 13: MSS03BAR
MSS03BAR: Connecting...
MSS03BAR: Connected
Acceso probado a MSS: MSS03BAR
MSS03BAR Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
********************************************************
CGR 2855 SPC 099A
****MSS: MSS03BAR Colecting OPC 

MSS_REMOTO: MSBA3 SPC: 17C1
MSS: MSS03BAR CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS03BAR: Closing..
MSS03BAR: Disconnected
############
# MSS03CAL #
############
ACCESING 14: MSS03CAL
MSS03CAL: Connecting...
MSS03CAL: Connected
Acceso probado a MSS: MSS03CAL
MSS03CAL Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
******************************************************************
CGR 2855 SPC 099A
****MSS: MSS03CAL Colecting OPC 

MSS_REMOTO: MSCA3 SPC: 0BCA
MSS: MSS03CAL CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS03CAL: Closing..
MSS03CAL: Disconnected
############
# MSS03MED #
############
ACCESING 15: MSS03MED
MSS03MED: Connecting...
MSS03MED: Connected
Acceso probado a MSS: MSS03MED
MSS03MED Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
***********************************************************************
CGR 2855 SPC 099A
*****MSS: MSS03MED Colecting OPC 

MSS_REMOTO: MSME3 SPC: 03C8
MSS: MSS03MED CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS03MED: Closing..
MSS03MED: Disconnected
############
# MSS03PRA #
############
ACCESING 16: MSS03PRA
MSS03PRA: Connecting...
MSS03PRA: Connected
Acceso probado a MSS: MSS03PRA
MSS03PRA Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
****************************************************************
CGR 2855 SPC 099A
*****MSS: MSS03PRA Colecting OPC 

MSS_REMOTO: MSPR3 SPC: 0761
MSS: MSS03PRA CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS03PRA: Closing..
MSS03PRA: Disconnected
############
# MSS03VEN #
############
ACCESING 17: MSS03VEN
MSS03VEN: Connecting...
MSS03VEN: Connected
Acceso probado a MSS: MSS03VEN
MSS03VEN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************************
CGR 2855 SPC 099A
******MSS: MSS03VEN Colecting OPC 

MSS_REMOTO: MSVE3 SPC: 0794
MSS: MSS03VEN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS03VEN: Closing..
MSS03VEN: Disconnected
############
# MSS04ARA #
############
ACCESING 18: MSS04ARA
MSS04ARA: Connecting...
MSS04ARA: Connected
Acceso probado a MSS: MSS04ARA
MSS04ARA Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
******************************************************************
CGR 2855 SPC 099A
*****MSS: MSS04ARA Colecting OPC 

MSS_REMOTO: MSAR4 SPC: 07E1
MSS: MSS04ARA CGR 2855 CGR_STAT WO-EX CKT_TOT: 1054 CKTS_OOS: 0 
MSS04ARA: Closing..
MSS04ARA: Disconnected
############
# MSS04CAL #
############
ACCESING 19: MSS04CAL
MSS04CAL: Connecting...
MSS04CAL: Connected
Acceso probado a MSS: MSS04CAL
MSS04CAL Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
***************************************************************
CGR 2855 SPC 099A
****MSS: MSS04CAL Colecting OPC 

MSS_REMOTO: MSCL4 SPC: 0BE7
MSS: MSS04CAL CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS04CAL: Closing..
MSS04CAL: Disconnected
############
# MSS04VEN #
############
ACCESING 20: MSS04VEN
MSS04VEN: Connecting...
MSS04VEN: Connected
Acceso probado a MSS: MSS04VEN
MSS04VEN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************************
CGR 2855 SPC 099A
******MSS: MSS04VEN Colecting OPC 

MSS_REMOTO: MSVE4 SPC: 0791
MSS: MSS04VEN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS04VEN: Closing..
MSS04VEN: Disconnected
############
# MSS05ARA #
############
ACCESING 21: MSS05ARA
MSS05ARA: Connecting...
MSS05ARA: Connected
Acceso probado a MSS: MSS05ARA
MSS05ARA Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*******************************************************************
CGR 2855 SPC 099A
****MSS: MSS05ARA Colecting OPC 

MSS_REMOTO: MSAR5 SPC: 07AF
MSS: MSS05ARA CGR 2855 CGR_STAT WO-EX CKT_TOT: 310 CKTS_OOS: 0 
MSS05ARA: Closing..
MSS05ARA: Disconnected
############
# MSS05MED #
############
ACCESING 22: MSS05MED
MSS05MED: Connecting...
MSS05MED: Connected
Acceso probado a MSS: MSS05MED
MSS05MED Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**************************************************************
CGR 2855 SPC 099A
******MSS: MSS05MED Colecting OPC 

MSS_REMOTO: MSME5 SPC: 03E2
MSS: MSS05MED CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSS05MED: Closing..
MSS05MED: Disconnected
############
# MSS05VEN #
############
ACCESING 23: MSS05VEN
MSS05VEN: Connecting...
MSS05VEN: Connected
Acceso probado a MSS: MSS05VEN
MSS05VEN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************************
CGR 2855 SPC 099A
******MSS: MSS05VEN Colecting OPC 

MSS_REMOTO: MSVE5 SPC: 0709
MSS: MSS05VEN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS05VEN: Closing..
MSS05VEN: Disconnected
############
# MSS06ARA #
############
ACCESING 24: MSS06ARA
MSS06ARA: Connecting...
MSS06ARA: Connected
Acceso probado a MSS: MSS06ARA
MSS06ARA Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************
CGR 2855 SPC 099A
******MSS: MSS06ARA Colecting OPC 

MSS_REMOTO: MSAR6 SPC: 07B4
MSS: MSS06ARA CGR 2855 CGR_STAT WO-EX CKT_TOT: 620 CKTS_OOS: 0 
MSS06ARA: Closing..
MSS06ARA: Disconnected
############
# MSS06MED #
############
ACCESING 25: MSS06MED
MSS06MED: Connecting...
Closing all connections
MSS06MED: Disconnected
MSSING02: Disconnected
MSS06MED: Disconnected
Sin acceso a MSS: MSS06MED
############
# MSS06VEN #
############
ACCESING 26: MSS06VEN
MSS06VEN: Connecting...
MSS06VEN: Connected
Acceso probado a MSS: MSS06VEN
MSS06VEN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**********************************************************
CGR 2855 SPC 099A
*****MSS: MSS06VEN Colecting OPC 

MSS_REMOTO: MSVE6 SPC: 072B
MSS: MSS06VEN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS06VEN: Closing..
MSS06VEN: Disconnected
############
# MSS07ARA #
############
ACCESING 27: MSS07ARA
MSS07ARA: Connecting...
MSS07ARA: Connected
Acceso probado a MSS: MSS07ARA
MSS07ARA Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
***********************************************************
CGR 2855 SPC 099A
*****MSS: MSS07ARA Colecting OPC 

MSS_REMOTO: MSAR7 SPC: 07B9
MSS: MSS07ARA CGR 2855 CGR_STAT WO-EX CKT_TOT: 620 CKTS_OOS: 0 
MSS07ARA: Closing..
MSS07ARA: Disconnected
############
# MSS07VEN #
############
ACCESING 28: MSS07VEN
MSS07VEN: Connecting...
MSS07VEN: Connected
Acceso probado a MSS: MSS07VEN
MSS07VEN Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*************************************************************
CGR 2855 SPC 099A
******MSS: MSS07VEN Colecting OPC 

MSS_REMOTO: MSVE7 SPC: 072C
MSS: MSS07VEN CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS07VEN: Closing..
MSS07VEN: Disconnected
############
# MSSALK01 #
############
ACCESING 29: MSSALK01
MSSALK01: Connecting...
MSSALK01: Connected
Acceso probado a MSS: MSSALK01
MSSALK01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
******************************************************
CGR 2855 SPC 099A
************MSS: MSSALK01 Colecting OPC 

MSS_REMOTO: MSAK1 SPC: 17B2
MSS: MSSALK01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSSALK01: Closing..
MSSALK01: Disconnected
############
# MSSALK02 #
############
ACCESING 30: MSSALK02
MSSALK02: Connecting...
MSSALK02: Connected
Acceso probado a MSS: MSSALK02
MSSALK02 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*****************************************************
CGR 2855 SPC 099A
**********MSS: MSSALK02 Colecting OPC 

MSS_REMOTO: MSAK2 SPC: 17C3
MSS: MSSALK02 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSALK02: Closing..
MSSALK02: Disconnected
############
# MSSARA01 #
############
ACCESING 31: MSSARA01
MSSARA01: Connecting...
MSSARA01: Connected
Acceso probado a MSS: MSSARA01
MSSARA01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
********************************************************
CGR 2855 SPC 099A
********MSS: MSSARA01 Colecting OPC 

MSS_REMOTO: MSAR1 SPC: 06A0
MSS: MSSARA01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSARA01: Closing..
MSSARA01: Disconnected
############
# MSSBUC01 #
############
ACCESING 32: MSSBUC01
MSSBUC01: Connecting...
MSSBUC01: Connected
Acceso probado a MSS: MSSBUC01
MSSBUC01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*********************************************************
CGR 2855 SPC 099A
**********MSS: MSSBUC01 Colecting OPC 

MSS_REMOTO: MSBU1 SPC: 1FD6
MSS: MSSBUC01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSBUC01: Closing..
MSSBUC01: Disconnected
############
# MSSING01 #
############
ACCESING 33: MSSING01
MSSING01: Connecting...
MSSING01: Connected
Acceso probado a MSS: MSSING01
MSSING01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
***************************************************************
CGR 2857 SPC 099A
*******MSS: MSSING01 Colecting OPC 

MSS_REMOTO: MSIN1 SPC: 082D
MSS: MSSING01 CGR 2857 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSING01: Closing..
MSSING01: Disconnected
############
# MSSMAR01 #
############
ACCESING 34: MSSMAR01
MSSMAR01: Connecting...
MSSMAR01: Connected
Acceso probado a MSS: MSSMAR01
MSSMAR01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
********************************************************
CGR 2855 SPC 099A
**********MSS: MSSMAR01 Colecting OPC 

MSS_REMOTO: MSMA1 SPC: 3C4A
MSS: MSSMAR01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSSMAR01: Closing..
MSSMAR01: Disconnected
############
# MSSMGA01 #
############
ACCESING 35: MSSMGA01
MSSMGA01: Connecting...
MSSMGA01: Connected
Acceso probado a MSS: MSSMGA01
MSSMGA01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
********************************************************
CGR 2857 SPC 099A
*********MSS: MSSMGA01 Colecting OPC 

MSS_REMOTO: MSMG1 SPC: 03EC
MSS: MSSMGA01 CGR 2857 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSMGA01: Closing..
MSSMGA01: Disconnected
############
# MSSPER01 #
############
ACCESING 36: MSSPER01
MSSPER01: Connecting...
MSSPER01: Connected
Acceso probado a MSS: MSSPER01
MSSPER01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*******************************************************
CGR 2855 SPC 099A
*********MSS: MSSPER01 Colecting OPC 

MSS_REMOTO: MSPE1 SPC: 1BCE
MSS: MSSPER01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSPER01: Closing..
MSSPER01: Disconnected
############
# MSSTRI01 #
############
ACCESING 37: MSSTRI01
MSSTRI01: Connecting...
MSSTRI01: Connected
Acceso probado a MSS: MSSTRI01
MSSTRI01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*********************************************************
CGR 2855 SPC 099A
**********MSS: MSSTRI01 Colecting OPC 

MSS_REMOTO: MSTR1 SPC: 0727
MSS: MSSTRI01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSTRI01: Closing..
MSSTRI01: Disconnected
############
# MSSTRI02 #
############
ACCESING 38: MSSTRI02
MSSTRI02: Connecting...
MSSTRI02: Connected
Acceso probado a MSS: MSSTRI02
MSSTRI02 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
**********************************************
CGR 2855 SPC 099A
*********MSS: MSSTRI02 Colecting OPC 

MSS_REMOTO: MSTR2 SPC: 072F
MSS: MSSTRI02 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSTRI02: Closing..
MSSTRI02: Disconnected
############
# MSSTRI03 #
############
ACCESING 39: MSSTRI03
MSSTRI03: Connecting...
MSSTRI03: Connected
Acceso probado a MSS: MSSTRI03
MSSTRI03 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************************************
CGR 2855 SPC 099A
*******MSS: MSSTRI03 Colecting OPC 

MSS_REMOTO: MSTR3 SPC: 07C8
MSS: MSSTRI03 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSTRI03: Closing..
MSSTRI03: Disconnected
############
# MSSVEN01 #
############
ACCESING 40: MSSVEN01
MSSVEN01: Connecting...
MSSVEN01: Connected
Acceso probado a MSS: MSSVEN01
MSSVEN01 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
********************************************************
CGR 2855 SPC 099A
***********MSS: MSSVEN01 Colecting OPC 

MSS_REMOTO: MSVE1 SPC: 06A3
MSS: MSSVEN01 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSVEN01: Closing..
MSSVEN01: Disconnected
############
# MSSMGA02 #
############
ACCESING 41: MSSMGA02
MSSMGA02: Connecting...
MSSMGA02: Connected
Acceso probado a MSS: MSSMGA02
MSSMGA02 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************
CGR 2855 SPC 099A
*********MSS: MSSMGA02 Colecting OPC 

MSS_REMOTO: MSMG2 SPC: 03EA
MSS: MSSMGA02 CGR 2855 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSMGA02: Closing..
MSSMGA02: Disconnected
############
# MSS01ALK #
############
ACCESING 42: MSS01ALK
MSS01ALK: Connecting...
MSS01ALK: Connected
Acceso probado a MSS: MSS01ALK
MSS01ALK Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
************************************************************
CGR 2855 SPC 099A
*****MSS: MSS01ALK Colecting OPC 

MSS_REMOTO: MSAK1 SPC: 17EA
MSS: MSS01ALK CGR 2855 CGR_STAT WO-EX CKT_TOT: 1024 CKTS_OOS: 0 
MSS01ALK: Closing..
MSS01ALK: Disconnected
############
# MSSARA02 #
############
ACCESING 43: MSSARA02
MSSARA02: Connecting...
MSSARA02: Connected
Acceso probado a MSS: MSSARA02
MSSARA02 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
*****************************************
CGR 2862 SPC 099A
*****MSS: MSSARA02 Colecting OPC 

MSS_REMOTO: MSAR2 SPC: 07B2
MSS: MSSARA02 CGR 2862 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSARA02: Closing..
MSSARA02: Disconnected
############
# MSSVEN02 #
############
ACCESING 44: MSSVEN02
MSSVEN02: Connecting...
MSSVEN02: Connected
Acceso probado a MSS: MSSVEN02
MSSVEN02 Colecting CGR's that match MSS MSSING02 OPC 099A
Buscando CGRs que match SPC 099A
******************************************
CGR 2862 SPC 099A
****MSS: MSSVEN02 Colecting OPC 

MSS_REMOTO: MSVE2 SPC: 07A7
MSS: MSSVEN02 CGR 2862 CGR_STAT WO-EX CKT_TOT: 2048 CKTS_OOS: 0 
MSSVEN02: Closing..
MSSVEN02: Disconnected
### Mismo MSS
############
# MSS01CAR #
############
ACCESING 46: MSS01CAR
MSS01CAR: Connecting...
MSS01CAR: Connected
MSS01CAR: Disconnected
MSS01CAR: Disconnected
Closing all connections
MSS01CAR: Disconnected
Sin acceso a MSS: MSS01CAR
##########################
# Imprimiendo resultados #
##########################
MSS: MSS01ING SPC: 0BEA CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS01PER SPC: 1BC4 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS01SIN SPC: 1551 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS01TOB SPC: 07BB CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS02ALK SPC: 17ED CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS02BUC SPC: 1FCD CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS02CAL SPC: 0BC7 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS02MED SPC: 03C5 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS02PER SPC: 1BC6 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS02TOB SPC: 07BE CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS02VEN SPC: 0796 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS03ARA SPC: 07DE CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1054 CKTS_OOS: 0
MSS: MSS03BAR SPC: 17C1 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS03CAL SPC: 0BCA CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS03MED SPC: 03C8 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS03PRA SPC: 0761 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS03VEN SPC: 0794 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS04ARA SPC: 07E1 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1054 CKTS_OOS: 0
MSS: MSS04CAL SPC: 0BE7 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS04VEN SPC: 0791 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS05ARA SPC: 07AF CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 310 CKTS_OOS: 0
MSS: MSS05MED SPC: 03E2 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS05VEN SPC: 0709 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS06ARA SPC: 07B4 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 620 CKTS_OOS: 0
Sin acceso a MSS MSS06MED
MSS: MSS06VEN SPC: 072B CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSS07ARA SPC: 07B9 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 620 CKTS_OOS: 0
MSS: MSS07VEN SPC: 072C CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSSALK01 SPC: 17B2 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSSALK02 SPC: 17C3 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSARA01 SPC: 06A0 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSBUC01 SPC: 1FD6 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSING01 SPC: 082D CGR: 2857 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSMAR01 SPC: 3C4A CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSSMGA01 SPC: 03EC CGR: 2857 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSPER01 SPC: 1BCE CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSTRI01 SPC: 0727 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSTRI02 SPC: 072F CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSTRI03 SPC: 07C8 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSVEN01 SPC: 06A3 CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSMGA02 SPC: 03EA CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSS01ALK SPC: 17EA CGR: 2855 CGR-STAT: WO-EX CKT_TOT: 1024 CKTS_OOS: 0
MSS: MSSARA02 SPC: 07B2 CGR: 2862 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
MSS: MSSVEN02 SPC: 07A7 CGR: 2862 CGR-STAT: WO-EX CKT_TOT: 2048 CKTS_OOS: 0
Sin acceso a MSS MSS01CAR
Hora inicio de macro: 2023-06-02  14:13:18
Hora fin de macro: 2023-06-02  15:01:55
FIN!!!!