Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\RAN-UTRAN\2G\oMSS_2G_BSC_BTS_CHECK\oMSS_BSC_BTS_V6.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSS05VEN: Already connected

############
# MSS05VEN #
############

#################
# BSC - IP/SCTP #
#################

#########################
# ASSOCIATIONS SET NAME #
#########################
MGVEB                             0   M3UA        SERVER
MGVEBNA1                          1   M3UA        SERVER
MGVEC                             2   M3UA        SERVER
MGVECNA1                          3   M3UA        SERVER
STPVE                             4   M3UA        CLIENT
STPBU                             5   M3UA        CLIENT
MSBU2                            10   M3UA        CLIENT
