Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 3 
   Variable 'filter' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 3 
   Variable 'file' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 4 
   Variable 'file_handle' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 4 
   Variable 'cuenta' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 5 
   Variable 'r' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 5 
   Variable 'g' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 5 
   Variable 'b' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 43 
   Variable 'CICENT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 44 
   Variable 'r' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 44 
   Variable 'g' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_BORRADO_GISUs\oMSS_Borrado_CIC_CGR_GISU\oMSS_Borrado_GISUs_DE_CGR_V4.tel', line 44 
   Variable 'b' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Connected
MSSVEN02: Connected
############
# MSSVEN02 #
############
1*- CGR: 2602 NCGR: IPV23ARA NBCRCT:225
2*- CGR: 2603 NCGR: IPV24ARA NBCRCT:1986
3*- CGR: 2604 NCGR: IPV25ARA NBCRCT:2017
4*- CGR: 2605 NCGR: IPV26ARA NBCRCT:1924
5*- CGR: 2606 NCGR: IPV27ARA NBCRCT:1924
6*- CGR: 2611 NCGR: IPV22VEA NBCRCT:1986
7*- CGR: 2612 NCGR: IPV23VEA NBCRCT:1955
8*- CGR: 2613 NCGR: IPV24VEA NBCRCT:1986
9*- CGR: 2614 NCGR: IPV25VEA NBCRCT:1893
10*- CGR: 2615 NCGR: IPV26VEA NBCRCT:1955
11*- CGR: 2616 NCGR: IPV27VEA NBCRCT:1955
12*- CGR: 2621 NCGR: IPV22BUA NBCRCT:931
13*- CGR: 2623 NCGR: IPV21TOA NBCRCT:931
14*- CGR: 2624 NCGR: IPV22TOA NBCRCT:1024
15*- CGR: 2625 NCGR: IPV23PRA NBCRCT:1955
16*- CGR: 2630 NCGR: IPV22CLA NBCRCT:1024
17*- CGR: 2631 NCGR: IPV23CLA NBCRCT:869
18*- CGR: 2632 NCGR: IPV24CLA NBCRCT:993
19*- CGR: 2633 NCGR: IPV21INA NBCRCT:962
20*- CGR: 2635 NCGR: IPV21PEA NBCRCT:1024
21*- CGR: 2636 NCGR: IPV22PEA NBCRCT:962
22*- CGR: 2640 NCGR: IPV22MEA NBCRCT:993
23*- CGR: 2641 NCGR: IPV23MEA NBCRCT:962
24*- CGR: 2643 NCGR: IPV25MEA NBCRCT:900
25*- CGR: 2644 NCGR: IPV26MEA NBCRCT:1024
26*- CGR: 2651 NCGR: IPV23BAA NBCRCT:962
27*- CGR: 2653 NCGR: IPV21AKA NBCRCT:993
28*- CGR: 2654 NCGR: IPV22AKA NBCRCT:1024
29*- CGR: 2655 NCGR: IPV21CAA NBCRCT:869
30*- CGR: 2656 NCGR: IPV21SIA NBCRCT:1024
31*- CGR: 2657 NCGR: IPV22SIA NBCRCT:869
32*- CGR: 2800 NCGR: IPV2AR1A NBCRCT:2017
33*- CGR: 2820 NCGR: IPV2VE1A NBCRCT:1893
34*- CGR: 2830 NCGR: IPV2TR1A NBCRCT:1893
35*- CGR: 2831 NCGR: IPV2TR2A NBCRCT:1986
36*- CGR: 2840 NCGR: IPV2BU1A NBCRCT:1986
37*- CGR: 2850 NCGR: IPV2MG1A NBCRCT:1893
38*- CGR: 2854 NCGR: IPV2MG2A NBCRCT:1955
39*- CGR: 2858 NCGR: IPV2TR3A NBCRCT:1924
40*- CGR: 2859 NCGR: IPV2AR2A NBCRCT:1924
41*- CGR: 2860 NCGR: IPV2IN1A NBCRCT:1955
42*- CGR: 2862 NCGR: IPV2IN2A NBCRCT:1986
43*- CGR: 2870 NCGR: IPV2PE1A NBCRCT:1924
44*- CGR: 2890 NCGR: IPV2AK1A NBCRCT:962
45*- CGR: 2891 NCGR: IPV2AK2A NBCRCT:1955
46*- CGR: 2910 NCGR: IPV2MA1A NBCRCT:1024

*1/46*-CGR: 2602 NCGR: IPV23ARA NBCRCT:225
#############
# CGR: 2602 #
#############
SPC 07DE
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*2/46*-CGR: 2603 NCGR: IPV24ARA NBCRCT:1986
#############
# CGR: 2603 #
#############
SPC 07E1
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*3/46*-CGR: 2604 NCGR: IPV25ARA NBCRCT:2017
#############
# CGR: 2604 #
#############
SPC 07AF
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*4/46*-CGR: 2605 NCGR: IPV26ARA NBCRCT:1924
#############
# CGR: 2605 #
#############
SPC 07B4
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*5/46*-CGR: 2606 NCGR: IPV27ARA NBCRCT:1924
#############
# CGR: 2606 #
#############
SPC 07B9
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*6/46*-CGR: 2611 NCGR: IPV22VEA NBCRCT:1986
#############
# CGR: 2611 #
#############
SPC 0796
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*7/46*-CGR: 2612 NCGR: IPV23VEA NBCRCT:1955
#############
# CGR: 2612 #
#############
SPC 0794
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*8/46*-CGR: 2613 NCGR: IPV24VEA NBCRCT:1986
#############
# CGR: 2613 #
#############
SPC 0791
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*9/46*-CGR: 2614 NCGR: IPV25VEA NBCRCT:1893
#############
# CGR: 2614 #
#############
SPC 0709
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*10/46*-CGR: 2615 NCGR: IPV26VEA NBCRCT:1955
#############
# CGR: 2615 #
#############
SPC 072B
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*11/46*-CGR: 2616 NCGR: IPV27VEA NBCRCT:1955
#############
# CGR: 2616 #
#############
SPC 072C
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*12/46*-CGR: 2621 NCGR: IPV22BUA NBCRCT:931
#############
# CGR: 2621 #
#############
SPC 1FCD
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*13/46*-CGR: 2623 NCGR: IPV21TOA NBCRCT:931
#############
# CGR: 2623 #
#############
SPC 07BB
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*14/46*-CGR: 2624 NCGR: IPV22TOA NBCRCT:1024
#############
# CGR: 2624 #
#############
SPC 07BE
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*15/46*-CGR: 2625 NCGR: IPV23PRA NBCRCT:1955
#############
# CGR: 2625 #
#############
SPC 0761
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*16/46*-CGR: 2630 NCGR: IPV22CLA NBCRCT:1024
#############
# CGR: 2630 #
#############
SPC 0BC7
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*17/46*-CGR: 2631 NCGR: IPV23CLA NBCRCT:869
#############
# CGR: 2631 #
#############
SPC 0BCA
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*18/46*-CGR: 2632 NCGR: IPV24CLA NBCRCT:993
#############
# CGR: 2632 #
#############
SPC 0BE7
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*19/46*-CGR: 2633 NCGR: IPV21INA NBCRCT:962
#############
# CGR: 2633 #
#############
SPC 0BEA
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*20/46*-CGR: 2635 NCGR: IPV21PEA NBCRCT:1024
#############
# CGR: 2635 #
#############
SPC 1BC4
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*21/46*-CGR: 2636 NCGR: IPV22PEA NBCRCT:962
#############
# CGR: 2636 #
#############
SPC 1BC6
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*22/46*-CGR: 2640 NCGR: IPV22MEA NBCRCT:993
#############
# CGR: 2640 #
#############
SPC 03C5
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*23/46*-CGR: 2641 NCGR: IPV23MEA NBCRCT:962
#############
# CGR: 2641 #
#############
SPC 03C8
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*24/46*-CGR: 2643 NCGR: IPV25MEA NBCRCT:900
#############
# CGR: 2643 #
#############
SPC 03E2
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*25/46*-CGR: 2644 NCGR: IPV26MEA NBCRCT:1024
#############
# CGR: 2644 #
#############
SPC 03E7
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*26/46*-CGR: 2651 NCGR: IPV23BAA NBCRCT:962
#############
# CGR: 2651 #
#############
SPC 17C1
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*27/46*-CGR: 2653 NCGR: IPV21AKA NBCRCT:993
#############
# CGR: 2653 #
#############
SPC 17EA
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*28/46*-CGR: 2654 NCGR: IPV22AKA NBCRCT:1024
#############
# CGR: 2654 #
#############
SPC 17ED
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*29/46*-CGR: 2655 NCGR: IPV21CAA NBCRCT:869
#############
# CGR: 2655 #
#############
SPC 17DE
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*30/46*-CGR: 2656 NCGR: IPV21SIA NBCRCT:1024
#############
# CGR: 2656 #
#############
SPC 1551
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*31/46*-CGR: 2657 NCGR: IPV22SIA NBCRCT:869
#############
# CGR: 2657 #
#############
SPC 1556
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*32/46*-CGR: 2800 NCGR: IPV2AR1A NBCRCT:2017
#############
# CGR: 2800 #
#############
SPC 06A0
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*33/46*-CGR: 2820 NCGR: IPV2VE1A NBCRCT:1893
#############
# CGR: 2820 #
#############
SPC 06A3
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*34/46*-CGR: 2830 NCGR: IPV2TR1A NBCRCT:1893
#############
# CGR: 2830 #
#############
SPC 0727
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*35/46*-CGR: 2831 NCGR: IPV2TR2A NBCRCT:1986
#############
# CGR: 2831 #
#############
SPC 072F
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*36/46*-CGR: 2840 NCGR: IPV2BU1A NBCRCT:1986
#############
# CGR: 2840 #
#############
SPC 1FD6
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*37/46*-CGR: 2850 NCGR: IPV2MG1A NBCRCT:1893
#############
# CGR: 2850 #
#############
SPC 03EC
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*38/46*-CGR: 2854 NCGR: IPV2MG2A NBCRCT:1955
#############
# CGR: 2854 #
#############
SPC 03EA
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*39/46*-CGR: 2858 NCGR: IPV2TR3A NBCRCT:1924
#############
# CGR: 2858 #
#############
SPC 07C8
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*40/46*-CGR: 2859 NCGR: IPV2AR2A NBCRCT:1924
#############
# CGR: 2859 #
#############
SPC 07B2
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*41/46*-CGR: 2860 NCGR: IPV2IN1A NBCRCT:1955
#############
# CGR: 2860 #
#############
SPC 082D
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*42/46*-CGR: 2862 NCGR: IPV2IN2A NBCRCT:1986
#############
# CGR: 2862 #
#############
SPC 099A
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*43/46*-CGR: 2870 NCGR: IPV2PE1A NBCRCT:1924
#############
# CGR: 2870 #
#############
SPC 1BCE
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*44/46*-CGR: 2890 NCGR: IPV2AK1A NBCRCT:962
#############
# CGR: 2890 #
#############
SPC 17B2
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*45/46*-CGR: 2891 NCGR: IPV2AK2A NBCRCT:1955
#############
# CGR: 2891 #
#############
SPC 17C3
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60

*46/46*-CGR: 2910 NCGR: IPV2MA1A NBCRCT:1024
#############
# CGR: 2910 #
#############
SPC 3C4A
Existen 0 CIC asociados al GISU 58
Existen 0 CIC asociados al GISU 59
Existen 0 CIC asociados al GISU 60
#######
# FIN #
#######
MSSVEN02: Disconnected
