Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\39_oMSS_a_interf_attrib_subanalysis_moc\oMSS_a_interf_attrib_subanalysis_moc.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\39_oMSS_a_interf_attrib_subanalysis_moc\oMSS_a_interf_attrib_subanalysis_moc.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\39_oMSS_a_interf_attrib_subanalysis_moc\oMSS_a_interf_attrib_subanalysis_moc.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\39_oMSS_a_interf_attrib_subanalysis_moc\oMSS_a_interf_attrib_subanalysis_moc.tel', line 3 
   Variable 'y' declared but its value is never used

Got no compile errors.

