Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\71_oMSS_analysis_trees\oMSS_analysis_trees_Contra_MSS_Referencia.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\71_oMSS_analysis_trees\oMSS_analysis_trees_Contra_MSS_Referencia.tel', line 6 
   Variable 'z1' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
##################
# analysis_trees #
##################

TREE,ATYPE,TON
1*- 2 N INT
2*- 2 N NAT
3*- 2 N SUB
4*- 8 N SUB
5*- 30 N NAT
6*- 40 N INT
7*- 40 N NAT
8*- 40 N SUB
9*- 40 N NET
10*- 40 N CON
11*- 40 N POR
12*- 48 N UNK
13*- 49 N NAT
14*- 50 N INT
15*- 50 N NAT
16*- 51 N INT
17*- 51 N NAT
18*- 52 N INT
19*- 52 N NAT
20*- 52 N SUB
21*- 60 N NAT
22*- 60 N NET
23*- 70 N NAT
24*- 86 N NAT
25*- 90 N INT
26*- 90 N NAT
27*- 90 N SUB
28*- 90 N NET
29*- 90 N CON
30*- 95 N NAT
31*- 110 N INT
32*- 110 N NAT
33*- 110 N SUB
34*- 110 N NET
35*- 120 N INT
36*- 120 N NAT
37*- 120 N SUB
38*- 120 N NET
39*- 123 N INT
40*- 123 N NAT
41*- 123 N SUB
42*- 129 N INT
43*- 129 N NAT
44*- 129 N SUB
45*- 129 N NET
46*- 130 N INT
47*- 130 N NAT
48*- 130 N SUB
49*- 130 N NET
50*- 140 N INT
51*- 140 N NAT
52*- 140 N SUB
53*- 140 N NET
54*- 143 N INT
55*- 143 N NAT
56*- 143 N SUB
57*- 143 N NET
58*- 150 N INT
59*- 150 N NAT
60*- 150 N SUB
61*- 150 N NET
62*- 153 N INT
63*- 153 N NAT
64*- 153 N SUB
65*- 153 N NET
66*- 156 N INT
67*- 156 N NAT
68*- 156 N SUB
69*- 156 N NET
70*- 157 N NAT
71*- 157 N SUB
72*- 160 N INT
73*- 160 N NAT
74*- 160 N SUB
75*- 160 N NET
76*- 163 N INT
77*- 163 N NAT
78*- 163 N SUB
79*- 163 N NET
80*- 164 N SUB
81*- 166 N INT
82*- 166 N NAT
83*- 166 N SUB
84*- 166 N NET
85*- 169 N INT
86*- 169 N NAT
87*- 169 N SUB
88*- 169 N NET
89*- 170 N INT
90*- 170 N NAT
91*- 170 N SUB
92*- 170 N NET
93*- 171 N INT
94*- 171 N NAT
95*- 171 N SUB
96*- 171 N NET
97*- 173 N INT
98*- 173 N NAT
99*- 173 N SUB
100*- 173 N NET
101*- 180 N INT
102*- 180 N NAT
103*- 180 N SUB
104*- 180 N NET
105*- 189 N SUB
106*- 190 N INT
107*- 190 N NAT
108*- 190 N SUB
109*- 190 N NET
110*- 193 N INT
111*- 193 N NAT
112*- 193 N SUB
113*- 193 N NET
114*- 196 N INT
115*- 196 N NAT
116*- 196 N SUB
117*- 196 N NET
118*- 197 N INT
119*- 197 N NAT
120*- 197 N SUB
121*- 197 N NET
122*- 199 N NAT
123*- 199 N SUB
124*- 200 N INT
125*- 200 N NAT
126*- 200 N SUB
127*- 200 N NET
128*- 210 N INT
129*- 210 N NAT
130*- 210 N SUB
131*- 210 N NET
132*- 211 N INT
133*- 211 N NAT
134*- 211 N SUB
135*- 212 N INT
136*- 212 N NAT
137*- 212 N SUB
138*- 213 N NAT
139*- 214 N INT
140*- 214 N NAT
141*- 214 N SUB
142*- 215 N NAT
143*- 217 N INT
144*- 217 N NAT
145*- 217 N SUB
146*- 219 N NAT
147*- 220 N INT
148*- 251 N NAT
149*- 252 N CON
150*- 253 N CON
151*- 301 N NAT
152*- 302 N NAT
153*- 302 N SUB
154*- 302 N UNK
155*- 303 N NAT
156*- 303 N UNK
157*- 304 N INT
158*- 304 N NAT
159*- 304 N SUB
160*- 305 N INT
161*- 305 N NAT
162*- 305 N SUB
163*- 306 N INT
164*- 400 N NAT
165*- 401 N NAT
166*- 402 N NAT
167*- 403 N NAT
168*- 404 N NAT
169*- 405 N NAT
170*- 406 N NAT
171*- 406 N SUB
172*- 407 N NAT
173*- 410 N NAT
174*- 500 N NAT
175*- 501 N INT
176*- 501 N NAT
177*- 501 N SUB
178*- 502 N NAT
179*- 503 N INT
180*- 503 N NAT
181*- 504 N INT
182*- 504 N NAT
183*- 504 N NET
184*- 505 N INT
185*- 505 N NAT
186*- 506 N INT
187*- 506 N NAT
188*- 508 N NAT
189*- 508 N SUB
190*- 509 N NAT
191*- 555 N INT
192*- 555 N NAT
193*- 596 N SUB
194*- 608 N SUB
195*- 708 N SUB
196*- 718 N SUB
197*- 1003 N NAT
198*- 1110 N INT
199*- 1216 N NAT
##########
# TREE 2 #
##########
1*- ZRIH:TREE=2,ATYPE=N,TON=INT;
004141&&-4                0 TIGOLDI      1   N   IPMSS03ARA   0     CHARGE      
0041450&&-6&-8&-9         0 TIGOLDI      1   N   IPMSS03ARA   0     CHARGE      
004146&&-9                0 TIGOLDI      1   N   IPMSS03ARA   0     CHARGE      
00420                     0 ICNLDI       1   N   IPMSS05ARA   0     CHARGE      
00430                     0 HABLDITRV1   1   N   IPMSSVEN01   0     CHARGE      
004331&&-9                0 TYSLDI       1   N   IPMSS03ARA   0     CHARGE      
00442                     0 ARIALDIAR5   1   N   IPMSS05ARA   0     CHARGE      
00444                     0 LDIOUTAMX    1   N   IPMSSTRI01   0     CHARGE      
004560&&-4                0 TELMELDI     1   N   IPMSS05ARA   0     CHARGE      
0045650&&-6&-8&-9         0 TELMELDI     1   N   IPMSS05ARA   0     CHARGE      
004566&&-9                0 TELMELDI     1   N   IPMSS05ARA   0     CHARGE      
004641&&-4                0 SSCOLLDI     1   N   IPMSS03ARA   0     CHARGE      
0046450&&-6&-8&-9         0 SSCOLLDI     1   N   IPMSS03ARA   0     CHARGE      
004646&&-9                0 SSCOLLDI     1   N   IPMSS03ARA   0     CHARGE      
004681&&-4                0 AVANTLDI     1   N   IPMSSARA01   0     CHARGE      
0046850&&-6&-8&-9         0 AVANTLDI     1   N   IPMSSARA01   0     CHARGE      
004686&&-9                0 AVANTLDI     1   N   IPMSSARA01   0     CHARGE      
00486                     0 CELVOLDI     1   N   IPMSS03ARA   0     CHARGE      
0050&&-4                  0 UNELDI1      1   N   IPMSSTRI02   0     CHARGE      
00550&&-6&-8&-9           0 UNELDI1      1   N   IPMSSTRI02   0     CHARGE      
0056&&-9                  0 UNELDI1      1   N   IPMSSTRI02   0     CHARGE      
0070&&-4                  0 ETBLDI       1   N   IPMSSARA01   0     CHARGE      
00750&&-6&-8&-9           0 ETBLDI       1   N   IPMSSARA01   0     CHARGE      
0076&&-9                  0 ETBLDI       1   N   IPMSSARA01   0     CHARGE      
0091&&-4                  0 TELECLDI     1   N   IPMSS03ARA   0     CHARGE      
00950&&-6&-8&-9           0 TELECLDI     1   N   IPMSS03ARA   0     CHARGE      
0096&&-9                  0 TELECLDI     1   N   IPMSS03ARA   0     CHARGE      
1&&8                      0 MSRNMSINTL3  1   N   IPMSS03PRA   0     CHARGE      
90&&-8                    0 MSRNMSINTL3  1   N   IPMSS03PRA   0     CHARGE      
990&&-6                   0 MSRNMSINTL3  1   N   IPMSS03PRA   0     CHARGE      
997&-8                    0 LDIOUTAMX    1   N   IPMSSTRI01   0     CHARGE      
BC998C                    0 LDIOUTAMX    1   N   IPMSSTRI01   0     CHARGE      
TREE 2 ATYPE N TON INT tiene 32 tuplas
2*- ZRIH:TREE=2,ATYPE=N,TON=NAT;
01800011&-2               0 ETBPSTFRE    1   N   IPMSSARA01   0     CHARGE      
018000160&&-4             0 SSCOLLDI     1   N   IPMSS03ARA   0     CHARGE      
01800018                  0 TMXPSTFRE    1   N   IPMSS05ARA   0     CHARGE      
01800019600&&-9           0 SSCOLLDI     1   N   IPMSS03ARA   0     CHARGE      
018000341818              0 WAVEOPER018  1   N   IPMSSTRI02   0     CHARGE      
018000343434              0 TELESCUELITA 1   N   DELLADDTELM  0     CHARGE      
018000344444              0 O18000TREE40 1   N   O18000TREE40 0     CHARGE      
018000345000              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
018000360&&-9             0 TRANS01800A5 1   N   IPMSS05ARA   0     CHARGE      
01800038&&-9              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
018000400&-1              0 EDATEPSTFREE 1   N   IPMSS02MED   0     CHARGE      
01800041&-2               0 UNELDIFRE    1   N   IPMSSTRI02   0     CHARGE      
018000442                 0 ARIALDIAR5   1   N   IPMSS05ARA   0     CHARGE      
01800051&-2               0 UNEPSTFREE   1   N   IPMSSTRI02   0     CHARGE      
01800091&-3&&-7&-9        0 TELPSTFRE    1   N   IPMSS03ARA   0     CHARGE      
01800300                  0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
018005                    0 UNEPSTFREE   1   N   IPMSSTRI02   0     CHARGE      
018007                    0 ETBPSTFRE    1   N   IPMSSARA01   0     CHARGE      
018008008                 0 ARIALDIAR5   1   N   IPMSS05ARA   0     CHARGE      
0180090&&-9               0 TELPSTFRE    1   N   IPMSS03ARA   0     CHARGE      
01900110&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900220&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900330&&-2&-9           0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900350                  0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900440&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900550&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900660&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900770&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900780                  0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
01900880&&-2              0 FREECALL     1   N   IPMSSTRI01   0     CHARGE      
019014400100              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400200              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400300              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400400              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400500              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400600              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400700              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014400800              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014440000              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014440077              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014440101              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014440222              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014440444              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014440554              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014440909              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014440999              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014441000              0 SETELSA2     1   N   IPMSS03ARA   0     CHARGE      
019014441010              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014441111              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014441122              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014441234              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014441444              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014442020              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014442222              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014442233              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014442422&-4           0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014442500&-5           0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014442525              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014443030              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014443333              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014443366              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014443434              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014443444              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014444040              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014444050&-5           0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014444297              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014444444              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014444455              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014445050              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014445555              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014446060              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014446666              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014446677              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014446699              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014446969              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014447171              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014447396              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014447770&-7           0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014447890              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014448404              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014448888              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014448920              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014448930              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014449060              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014449090              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
019014449898              0 PRVCONTENIDO 1   N   IPMSS03ARA   0     CHARGE      
019014449999              0 SETELSA1     1   N   IPMSS03VEN   0     CHARGE      
031200&&031212            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031213&&-6                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031217                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031218&&-9                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031220&&031230            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031231                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031232&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031236                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031237&&031249            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031250                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031251&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031256&&-9                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
03126                     0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031270                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031271                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031272&-3                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031274&-5                 0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031276&&031295            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031296                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031297&&031311            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031312&-3                 0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031314&&-6                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031317                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031318                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031319                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031320                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031321&-2                 0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031323&-4                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031325&-6                 0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031327&&031353            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031354                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031355                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031356                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031357&&031375            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031376                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031377&-8                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031379                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031380&&-3                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031384&-5                 0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031386&&031399            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03140&&-2                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0314371234                0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03143                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031440&-1                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031442                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031443&&031454            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031455                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031456&&031499            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03150&&-4                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031550&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031556&&-9                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
03156&&03160              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031610&&-2                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031613                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031614&&031623            0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031624                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031625&&-9                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031630&-1                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031632&&031642            0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031643                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031644&&031651            0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031652                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031653&&-8                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031659&&031661            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031662                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031663&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031666&-7                 0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031668&&-9                0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031670                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031671&&-3                0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031674                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031675                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031676&&031686            0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031687&&031691            0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031692                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031693                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031694&&-6                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031697                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031698&&-9                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0317                      0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03180                     0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318101019                0 MSOFT1TRIPST 1   N   IPMSSTRI02   0     CHARGE      
0318134200                0 TELMEXNEW456 1   N   IPMSSTRI02   0     CHARGE      
03181                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03182&-3                  0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318400&&0318413          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318414                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318415&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031842&&031860            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031861                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
031862&&-4                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318650&&-5               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318656                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318657&&0318705          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03187060&-1               0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
03187062&&-4              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03187065&&-9              0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
0318707&&0318750          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318751                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03187520&&-7              0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03187528&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318753&&0318765          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318766                   0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
0318767&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031877                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318780&&-4               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318785&-6                0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318787                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318788&&-9               0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318790&&0318800          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03188100&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03188110&&03188159        0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318816&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318820&-1                0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318822&&0318834          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318835                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318836&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031884&&-7                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318894                   0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
0318895&-6                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318897                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318898                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318899                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318900&&-5               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318906&&-9               0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318910&&-5               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318916&-7                0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318955                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318956&&0318974          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031897520&&-9             0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03189753&&03189765        0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03189766&&03189786        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03189787&&-9              0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
031898                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0318990&&-3               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03189940&-1               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03189942&&-9              0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
0318995&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031900&&031912            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0319130&&-7               0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
03191380&&-3              0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
03191384&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
0319139                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031914&&031923            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03192400&&-8              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03192409                  0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03192410&&03192458        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03192459                  0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03192460&&03192508        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
03192509                  0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
03192510&&03192599        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031926&&031999            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
031                      0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
032301                    0 SSCARA5      1   N   IPMSS05ARA   0     CHARGE      
032                      0 DEFAULPST032 1   N   IPMSS03CAL   0     CHARGE      
03300                     0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033011&-2                 0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033013704646              0 TIGOLDI      1   N   IPMSS03ARA   0     CHARGE      
033013                   0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033014&&-9                0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330210&&-2               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033022&-3                 0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330240&&-6               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
03302470&&-9              0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
0330248&&-9               0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
033025&&-7                0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
0330280&&-6               0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
0330410&&-8               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033042&&-4                0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330452&&-9               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033046                    0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330470&&-5               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330520                   0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
03305210&&-6              0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330522&&-5               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
03305260&&-6              0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033052670                 0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330526710&&-4            0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330527&-8                0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
03305290&&-9              0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0330530&&0330548          0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
03305700&&03305719        0 ETBMOBDEF    1   N   IPMSS03PRA   0     CHARGE      
0330572&&-8               0 ETBMOBDEF    1   N   IPMSS03PRA   0     CHARGE      
03305790&&-9              0 ETBMOBDEF    1   N   IPMSS03PRA   0     CHARGE      
033058                    0 ETBMOBDEF    1   N   IPMSS03PRA   0     CHARGE      
0330590&&-5               0 ETBMOBDEF    1   N   IPMSS03PRA   0     CHARGE      
033100487&&-9             0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033102150&&-8             0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
0331021590&&-7            0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
03310215980               0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159810&&-7          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159818              0 IVRRECARGA   1   N   IPMSS02VEN   0     CHARGE      
033102159819              0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159820              0 SCB230ORIMOD 1   N   IPMSS02VEN   0     CHARGE      
033102159835              0 SCB229DEF    1   N   IPMSS02VEN   0     CHARGE      
033102159836&&-9          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159840              0 WAV2TO018000 1   N   IPMSSMAR01   0     CHARGE      
033102159841              0 IVRINFRACEL  1   N   IPMSS02VEN   0     CHARGE      
033102159842&-3           0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159844&-5           0 INFRASRVCL   1   N   IPMSS03VEN   0     CHARGE      
033102159846&&-9          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159851              0 SACPRETELCCA 1   N   IPMSS05ARA   0     CHARGE      
033102159853              0 ATENTOSRVCL  1   N   IPMSS05ARA   0     CHARGE      
033102159854              0 IVRVENPREOCS 1   N   IPMSS06VEN   0     CHARGE      
033102159860&&-2          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159863              0 SERVCLIPRA   1   N   IPMSS03PRA   0     CHARGE      
033102159864              0 SACPRETELCCA 1   N   IPMSS05ARA   0     CHARGE      
033102159865              0 SACMILSIT    1   N   IPMSS03PRA   0     CHARGE      
033102159866&&-8          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159869              0 IVRSIPVEN    1   N   IPMSS02VEN   0     CHARGE      
033102159870&&-2          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159873&-4           0 SERVCLIPRA   1   N   IPMSS03PRA   0     CHARGE      
033102159875              0 TRATELME     1   N   IPMSS01TOB   0     CHARGE      
033102159876&&-9          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159890              0 WAVESCC753   1   N   IPMSSTRI02   0     CHARGE      
033102159891              0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159892              0 ATENTOSRVCL  1   N   IPMSS05ARA   0     CHARGE      
033102159893              0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033102159894              0 IVRSIPVEN    1   N   IPMSS02VEN   0     CHARGE      
033102159895&&-9          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
0331021599                0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
03310216&&-9              0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
0331022&&-9               0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
0331060&&-6               0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
03310670                  0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033106710&&-8             0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033106719000&&-5          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033106719006              0 SERVCLIPRA   1   N   IPMSS03PRA   0     CHARGE      
                          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
033106719015              0 SERVCLIPRA   1   N   IPMSS03PRA   0     CHARGE      
033106719016              0 INFRASRVCL   1   N   IPMSS03VEN   0     CHARGE      
033106719017&&-9          0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
0331067192&&-9            0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
03310672                  0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
0331070&&-3               0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
03310740&&-8              0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107490&-1              0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107492000&-1           0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107492002              0 IVRINFRACEL  1   N   IPMSS02VEN   0     CHARGE      
033107492003              0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107492004              0 IVRINFRACEL  1   N   IPMSS02VEN   0     CHARGE      
033107492005&-6           0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107492007&-8           0 SRVCLARA     1   N   IPMSS05ARA   0     CHARGE      
033107492009              0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
03310749201               0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107492020&-1           0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107492022              0 VENTAMULTI   1   N   IPMSS05ARA   0     CHARGE      
033107492023&&-9          0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
03310749203&&-9           0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
0331074921&&-9            0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033107493&&-9             0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
0331075&&-9               0 CLAROMOB     1   N   IPMSS05ARA   0     CHARGE      
033112984968              0 IVRSCAMX     1   N   IPMSS03ARA   0     CHARGE      
033112984981              0 SRVCLARA     1   N   IPMSS05ARA   0     CHARGE      
033112999820              0 TRANIVRB748  1   N   IPMSSTRI02   0     CHARGE      
033146990019              0 INFRASRVCL   1   N   IPMSS03VEN   0     CHARGE      
033146990025              0 INFRASRVCL   1   N   IPMSS03VEN   0     CHARGE      
03315&&-7                 0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
033182&&-8                0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
033192&&-7                0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
033206002002              0 SCB601ORIMOD 1   N   IPMSSPER01   0     CHARGE      
033236&&-9                0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
0332410&&-9               0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
033247&&-9                0 WOMMOB       1   N   IPMSS03ARA   0     CHARGE      
03324                    0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
033300                    0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
0333300&&-4               0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
0333305&&-8               0 LOVMOB       1   N   IPMSSTRI02   0     CHARGE      
033332                    0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0333340&&-4               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0333360&&-4               0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
0333365&-6                0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
03333670&&-4              0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
033502&&-8                0 AVANTMOB     1   N   IPMSSARA01   0     CHARGE      
0342004&&0342014          0 SSCARA5      1   N   IPMSS05ARA   0     CHARGE      
034                      0 DEFAULPST034 1   N   IPMSS02MED   0     CHARGE      
035400                    0 SSCARA5      1   N   IPMSS05ARA   0     CHARGE      
035                      0 DEFAULPST035 1   N   IPMSSMAR01   0     CHARGE      
036                       0 DEFAULPST036 1   N   IPMSS01PER   0     CHARGE      
037528                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037529400&&-9             0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375410&-1                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375551&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037555500&&037555999      0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375560&-3&-4             0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03755650&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375574                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03756000&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03756010&&-6              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03756400&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03756430&&03756443        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375650000&&0375653499    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037565350&&037565439      0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03756560&&-7              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375658                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03759091&&03759170        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375920000&&0375922699    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037592270&&037592879      0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03759288                  0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375930&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037594                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375950&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0375970&&-6               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03760100&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376011&-2                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376014&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03760190&&-5              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376035                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03760360&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376050&&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03760580&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376063&&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037607                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03761335&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376134&-5                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03761410&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376156&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03761612&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376162&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376171&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376183000&&0376183999    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376184&&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037619                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376230&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03762880&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376648&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03766500&&03766596        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03766610&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03766630&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376690&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03766940&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376695&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03768614&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376862&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376876&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376881                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376920&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376930                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03769355&&03769399        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037694&-5                 0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376960&&-4&-6&&-9        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0376970&&0376989          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03770100&&03770187        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
0377174                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03772330&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03775890&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
03788370&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
037                      0 DEFAULPST037 1   N   IPMSSBUC01   0     CHARGE      
038                       0 DEFAULPST038 1   N   IPMSS03ARA   0     CHARGE      
03910000&&-4              0 OMVSUMATIGO  1   N   IPMSSTRI02   0     CHARGE      
0391010&&-7               0 MOVISTMOB    1   N   IPMSS07VEN   0     CHARGE      
0391020&-1                0 TIGOMOB      1   N   IPMSSTRI01   0     CHARGE      
039107075&&-9             0 ETBMOBDEF    1   N   IPMSS03PRA   0     CHARGE      
10112                     0 ETBEMG1XY1   1   N   IPMSS03ARA   0     CHARGE      
113                       0 PUBLICAR     1   N   IPMSS03ARA   0     CHARGE      
114&-7                    0 ETBEMG1XY1   1   N   IPMSS03ARA   0     CHARGE      
122                       0 SPR2254      1   N   SPR2254      0     CHARGE      
143                       0 ETBEMG1XY1   1   N   IPMSS03ARA   0     CHARGE      
152                       0 ETBEMG1XY1   1   N   IPMSS03ARA   0     CHARGE      
164                       0 ALCANOS      1   N   ALCANO8420   0     CHARGE      
190                       0 TELNALPST    1   N   IPMSS05ARA   0     CHARGE      
2159811&&-4               0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
2159815&&-7               0 EXTENDEF     1   N   IPMSS04ARA   0     CHARGE      
2159823&-4                0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
2159860&&-2               0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
2159870&&-2               0 IVRSRVCL1    1   N   IPMSS04ARA   0     CHARGE      
3001&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
300900&&-9                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30091&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3011&&-9                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30210&&-2                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3022&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30410&&-8                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3042&&-4                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30452&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3046                      0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30470&&-5                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30520                     0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
305210&&-6                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30522&&-5                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
305260&&-6                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3052670                   0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30526710&&-4              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30527&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3053&&-6                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
305700&&305719            0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30572&&-8                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
305790&&-9                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3058                      0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
30590&&-5                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3102                      0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
31031570&&-5              0 PBXMOVILAR1  1   N   IPMSSARA01   0     CHARGE      
31031576&&31031580        0 PBXMOVILAR3  1   N   IPMSS03ARA   0     CHARGE      
31031581&&-6              0 PBXMOVILTR1  1   N   IPMSSTRI01   0     CHARGE      
3103                     0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3104&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3109399                   0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3112984927                0 SERORVRECL   1   N   IPMSS03VEN   0     CHARGE      
3112984933                0 SERORVRECL   1   N   IPMSS03VEN   0     CHARGE      
3112                     0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3113&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3122&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3132&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3142&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3152&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
31591&&-3                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
316                       0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
31700&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3172&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3182&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
31920&&-4                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
319250&&-6                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3192570&&-9               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
319258&&-9                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
31926&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3193&&-7                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3202                      0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32035039                  0 MSRNMSTR01   1   N   IPMSSTRI01   0     CHARGE      
32035040                  0 PBXMOVILAR3  1   N   IPMSS03ARA   0     CHARGE      
32035096&&-8              0 PBXMOVILAR1  1   N   IPMSSARA01   0     CHARGE      
3203509900                0 PBXMOVILAR1  1   N   IPMSSARA01   0     CHARGE      
3203                     0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3204&&-7                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32080&&-7                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
320880&&-8                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3208890&&-8               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32088990&&-4              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32088995&-6               0 PBXMOVILTR1  1   N   IPMSSTRI01   0     CHARGE      
3208899755                0 PBXMOVILTR1  1   N   IPMSSTRI01   0     CHARGE      
32088997                 0 PBXMOVILAR3  1   N   IPMSS03ARA   0     CHARGE      
32088998                  0 PBXMOVILAR3  1   N   IPMSS03ARA   0     CHARGE      
3208899900                0 PBXMOVILTR1  1   N   IPMSSTRI01   0     CHARGE      
3208899901&&-9            0 PBXMOVILAR3  1   N   IPMSS03ARA   0     CHARGE      
320889991&&-9             0 PBXMOVILTR1  1   N   IPMSSTRI01   0     CHARGE      
32089                     0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3209                      0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3212&&-9                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3222&&-9                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32320&&-4                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
323250&&-3                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32325401&&-5              0 PBXMOVILAR1  1   N   IPMSSARA01   0     CHARGE      
323254                   0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3232550&&-3               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32325540&&-4              0 PBXMOVILAR3  1   N   IPMSS03ARA   0     CHARGE      
32325545&&-9              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3232555&&-9               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
323256&&-9                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32326&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3233&-4                   0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32350&&-5                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
323560&&-2                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3235630&&-8               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32356390&&-2              0 ASISVIRTU    1   N   SPR2273      0     CHARGE      
32356393&&-9              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
323564&&-9                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32357&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
323590&&-8                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3235990&&-5               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32359960&&-3              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32359964&-5               0 PBXMOVILAR1  1   N   IPMSSARA01   0     CHARGE      
32359966&&-9              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32359970                  0 PBXMOVILAR1  1   N   IPMSSARA01   0     CHARGE      
32359971&&-9              0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3235998&&-9               0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3236&&-9                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
32410&&-9                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3242&&-9                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3300                      0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
33300&&-8                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
33320&-1                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
33340&&-4                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
33360&&-6                 0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
333670&&-4                0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
3502&&-8                  0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
60100&&-4                 0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601050&&-4                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6010550&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60105550                  0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601200&&601212            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601213&&-6                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601217                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601218&&-9                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601220&&601230            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601231                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
601232&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601236                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601237&&601249            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601250                    0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601251&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601256&&-9                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
60126                     0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601270                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601271                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601272&-3                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601274&-5                 0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601276&&601295            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601296                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601297&&601311            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601312&-3                 0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601314&&-6                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601317                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601318                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601319                    0 ETBCHICENPST 1   N   IPMSSARA01   0     CHARGE      
601320                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601321&-2                 0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601323&-4                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601325&-6                 0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601327&&601353            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601354                    0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
601355                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601356                    0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601357&&601375            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601376                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601377&-8                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601379                    0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601380&&-3                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601384&-5                 0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601386&&-9                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601390                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601391&&-9                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60140&&-2                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6014371234                0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
60143                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601440&-1                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601442                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601443&&601454            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601455                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601456&&601464            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6014654147                0 TESTCGRSIP   1   N   IPMSSTRI01   0     CHARGE      
601465                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601466&&601499            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60150&&-4                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601550&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601556&&-9                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
60156&&60160              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601610&&-2                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601613                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601614&&601623            0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601624                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601625&&-9                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601630&-1                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601632&&601642            0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601643                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601644&&601651            0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601652                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601653&&-8                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601659&&601661            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601662                    0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601663&&-5                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601666&-7                 0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601668&&-9                0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601670                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601671&&-3                0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601674                    0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601675                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601676&&601686            0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601687&&601691            0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601692                    0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601693                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601694&&-6                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601697                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601698&&-9                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601708&&-9                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601754                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6017                     0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60180                     0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018101019                0 MSOFT1TRIPST 1   N   IPMSSTRI02   0     CHARGE      
6018134200                0 TELMEXNEW456 1   N   IPMSSTRI02   0     CHARGE      
60181                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60182&-3                  0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018400&&6018413          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018414                   0 ETBCHINORPST 1   N   IPMSSARA01   0     CHARGE      
6018415&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601842&&601858            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018590&&-8               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60185990&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60185992&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601860                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601861                    0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
601862&&-4                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018650&&-5               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018656                   0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018657&&6018705          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60187060&-1               0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
60187062&&-4              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60187065&&-9              0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
6018707&&6018724          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018725&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6018730&&6018750          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018751                   0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60187520&&-7              0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60187528&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018753&&6018764          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60187657&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018765                  0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6018766                   0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
6018767&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601877                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018780&&-4               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018785&-6                0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018787                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018788&&-9               0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018790&&6018800          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60188100&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60188110&&60188159        0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018816&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018820&-1                0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018822&&6018834          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018835                   0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018836&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601884&&-7                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018894                   0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
6018895&-6                0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018897                   0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018898                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018899                   0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018900&&-5               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018906&&-9               0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018910&&-5               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018916&-7                0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018955                   0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018956&&6018974          0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601897520&&-9             0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60189753&&60189765        0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60189766&&60189786        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60189787&&-9              0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
601898                    0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6018990&&-3               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60189940&-1               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60189942&&-9              0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
6018995&&-9               0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601900&&601912            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6019130&&-7               0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
60191380&&-3              0 ETBCHICENPSB 1   N   IPMSSTRI02   0     CHARGE      
60191384&&-9              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
6019139                   0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601914&&601920            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601921                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601922&-3                 0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60192400&&-8              0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60192409                  0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60192410&&60192458        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60192459                  0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60192460&&60192508        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60192509                  0 ETBCHINORPSB 1   N   IPMSSTRI02   0     CHARGE      
60192510&&60192599        0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601926&&601959            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
60196&-7                  0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
601980&&601999            0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
601                      0 DEFAULPST031 1   N   IPMSS03ARA   0     CHARGE      
602301                    0 SSCARA5      1   N   IPMSS05ARA   0     CHARGE      
602                      0 DEFAULPST032 1   N   IPMSS03CAL   0     CHARGE      
6042004&&6042013          0 SSCARA5      1   N   IPMSS05ARA   0     CHARGE      
604                      0 DEFAULPST034 1   N   IPMSS02MED   0     CHARGE      
605400                    0 SSCARA5      1   N   IPMSS05ARA   0     CHARGE      
6055581                   0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
6055661&-2                0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
6055781                   0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
605584                    0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
6055850&&-7               0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
60558580&-1               0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
6056888&&-9               0 TRANSEDATEL  1   N   IPMSSMAR01   0     CHARGE      
60592015&&-9              0 EDATELVADB   1   N   IPMSSMAR01   0     CHARGE      
605                      0 DEFAULPST035 1   N   IPMSSMAR01   0     CHARGE      
606                       0 DEFAULPST036 1   N   IPMSS01PER   0     CHARGE      
607500                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075010                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60750110&&-8              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607528                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607529400&&-9             0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075410&-1                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607555500&&607555999      0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607555                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075560&-3&-4             0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60755650&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075574                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075600                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60756010&&-6              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075602&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60756050&&-7              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60756400&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60756430&&60756443        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075645&-6                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075650000&&6075653499    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607565350&&607565439      0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60756560&&-7              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075658                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60759091&&60759170        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075920000&&6075922699    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607592270&&607592879      0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60759288                  0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075930&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607594                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075950&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6075970&&-6               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60760100&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076011&-2                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076014&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60760190&&-5              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076035                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60760360&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076050&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076063&&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607607                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60761335&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076134&-5                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60761410&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076145&&6076151          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076156&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60761612&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076162&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076171&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076181                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60761820&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076183000&&6076183999    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076184&&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607619                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076230&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076243&&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076262&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076283&&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60762880&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076648&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60766510&&60766596        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607665                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60766610&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60766630&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076690&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60766940&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076695&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60768614&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076862&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076876&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076881                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076920&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076930                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60769355&&60769399        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607694&-5                 0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076960&&-4&-6&&-9        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6076970&&6076989          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607701                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6077174                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6077220&&-6               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60772330&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60775890&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60788370&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
607                      0 DEFAULPST037 1   N   IPMSSBUC01   0     CHARGE      
6082422&&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60824260&&-3              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6082540&&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6082553&-4                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60825550&&-5              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608259                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6084337&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6085010                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60850110&&-2              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608630                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6086454&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608647                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608674                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6086876&&6086881          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60868820&&-3              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087202&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087211&&-3               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60872495&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60872520&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60872850&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60872990&&-6              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60873220&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60873280&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60873565&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60873640&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60873650&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60873730&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087462&&6087473          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60874740                  0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60874761&&60874779        0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608747                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087480&&-4               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60874850&&-2              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087488                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608748                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608749                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087506&&6087513          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60875430&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087644&&6087650          0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60876510&-7&&-9           0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087652&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608766                    0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087743&&-8               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087750&&-5               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60877560&&-2              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087760&-1                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60877620&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087792                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60877950&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60877975&-6               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6087855&&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60878660&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60878820&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60878906&-7               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60883400&-1               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60883570&&-4              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
60884605&&-9              0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6088461&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6088489                   0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608849&&608850            0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6088617&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608862&&-5                0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
6088666&&-9               0 TELMEXNEWORI 1   N   IPMSSTRI02   0     CHARGE      
608                      0 DEFAULPST038 1   N   IPMSS03ARA   0     CHARGE      
910                       0 HLRENQSTP    1   N   HLRENQSTP    0     CHARGE      
992804123                 0 SC123RZ04    1   N   IPMSS05ARA   0     CHARGE      
B229                      0 SCB229DEF    1   N   IPMSS02VEN   0     CHARGE      
B257&&B261                0 ORQSIPVEN    1   N   IPMSS03VEN   0     CHARGE      
B552                      0 RBTACCESS    1   N   IPMSS04ARA   0     CHARGE      
B8726277                  0 SCB160ORIMOD 1   N   IPMSS03ARA   0     CHARGE      
BC111C03                  0 TREE002NATAN 2   N   ANN105       0     NOCHARGE    
BC111C3102159800&-6&-8    0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3102159980          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3103154500          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3103604500          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3104255000          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3106111611          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3106714000          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3112984953          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3112984963&-4       0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3112984970&-3&-7    0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3112984996&-7       0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C314499              0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C3206004003          0 ANN0994      2   N   ANN0994      0     NOCHARGE    
BC111C                   0 ANNORQSIPTRI 1   N   IPMSS03VEN   0     CHARGE      
TREE 2 ATYPE N TON NAT tiene 919 tuplas
3*- ZRIH:TREE=2,ATYPE=N,TON=SUB;
