Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\PING With FSCLISH\Ping_FSCLISH_Macro_Commands_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MGWVEN02: Already connected
Tue Oct 18 10:19:20 -05 2022
Se ha creado LOG: -1#####################################################################################
# C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\PING With FSCLISH\PING.txt #
#####################################################################################
1 OK fsclish -c "start networking tools ping network-host 10.61.156.1 node IPNIMP-0 count 6"
2 OK fsclish -c "start networking tools ping network-host 10.61.156.9 node IPNIMP-0 count 6"
3 OK fsclish -c "start networking tools ping network-host 10.61.156.17 node IPNIMP-0 count 6"
4 OK fsclish -c "start networking tools ping network-host 10.61.156.25 node IPNIMP-0 count 6"
5 OK fsclish -c "start networking tools ping network-host 10.61.156.33 node IPNIMP-0 count 6"
6 OK fsclish -c "start networking tools ping network-host 10.61.156.41 node IPNIMP-0 count 6"
7 OK fsclish -c "start networking tools ping network-host 10.61.156.49 node IPNIMP-0 count 6"
8 