Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\44_oMSS_load_balancer_config_handling\oMSS_load_balancer_config_handling.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\44_oMSS_load_balancer_config_handling\oMSS_load_balancer_config_handling.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\44_oMSS_load_balancer_config_handling\oMSS_load_balancer_config_handling.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\44_oMSS_load_balancer_config_handling\oMSS_load_balancer_config_handling.tel', line 3 
   Variable 'y' declared but its value is never used

Got no compile errors.

