Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 2 
   Variable 'filename2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 2 
   Variable 'ASOC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 2 
   Variable 'ASOC_NAME' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 2 
   Variable 'FEBU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'CHU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'CGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'NCGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'TCGR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'TDIR' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'NBCRCT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'STATE' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'CKTNOWO' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 3 
   Variable 'COMCAL' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'handle2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'a' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'b' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'PORC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'CKTOOS' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'm1' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 4 
   Variable 'm2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 23 
   Variable 'n' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Cloud_TCP_IP_Parameters\oMSS_Cloud_TCP_IP_Parameters.tel', line 37 
   Variable 'n' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Connected
MSSARA02: Connected
########
# IPDU #
########
IPDU 0
IPDU 1
IPDU 2
IPDU 3
IPDU 4
IPDU 5
IPDU 6
IPDU 7
IPDU 8
IPDU 9
IPDU 10
IPDU 11
FIN!!!!