Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\89_oMSS_ss7_signalling_route_set_params\oMSS_ss7_signalling_route_set_params.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\89_oMSS_ss7_signalling_route_set_params\oMSS_ss7_signalling_route_set_params.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\89_oMSS_ss7_signalling_route_set_params\oMSS_ss7_signalling_route_set_params.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\89_oMSS_ss7_signalling_route_set_params\oMSS_ss7_signalling_route_set_params.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
###################################
# ss7_signalling_route_set_params #
###################################
FIN!!!!