Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\42_oMSS_outgoing_call_control_parameter\oMSS_outgoing_call_control_parameter.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
###################################
# outgoing_call_control_parameter #
###################################
1*- 1 MAS
2*- 2 HANDOVER
3*- 4 CALLFORWARDING
4*- 11 SSAP
5*- 21 BASICOUTPSTNPBX
6*- 22 BSSAP
7*- 23 PAD
8*- 24 INTERMSS
9*- 25 INTERMSC
10*- 26 OLCM
11*- 27 TIGO
12*- 28 ETB2MSS
13*- 29 MOVISTAR
14*- 30 SIPSSR
15*- 31 WOM
16*- 32 IMSSIP
FIN!!!!