Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Ubicar_MSISDN_Number\oMSS_Ubicar_MSISDN.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Ubicar_MSISDN_Number\oMSS_Ubicar_MSISDN.tel', line 22 
   Variable 'filename' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Ubicar_MSISDN_Number\oMSS_Ubicar_MSISDN.tel', line 23 
   Variable 'handle' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Ubicar_MSISDN_Number\oMSS_Ubicar_MSISDN.tel', line 129 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Ubicar_MSISDN_Number\oMSS_Ubicar_MSISDN.tel', line 129 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.


############
# MSSTRI01 #
############
ACCESING 39: MSSTRI01
MSSTRI01: Connected
MSSTRI01: Connected
El acceso al MSS: MSSTRI01 esta OK
MSSTRI01: Closing..
MSSTRI01: Disconnected
MSSTRI01: Connected
MSSTRI01: Connected
El acceso al MSS: MSSTRI01 esta OK
MSSTRI01: Closing..
MSSTRI01: Disconnected
MSSTRI01: Connected
MSSTRI01: Connected
El acceso al MSS: MSSTRI01 esta OK
