Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 2 
   Variable 'CC' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 2 
   Variable 'CCB' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'z' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'z0' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'SIG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'RING' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'SPEACH' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'SIGB' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'RINGB' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Observacion_V2.tel', line 3 
   Variable 'SPEACHB' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Connected
MSSARA02: Connected
INICIO DE MACRO PARA MSSARA02: 2023-11-24  16:57:47
       152        163        581  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        582  B13H RADIO IF FAILURE          
       152        163        583  B13H RADIO IF FAILURE          
       152        163        583  B13H RADIO IF FAILURE          
       153        163        583  B13H RADIO IF FAILURE          
       153        163        584  B13H RADIO IF FAILURE          
       153        163        584  B13H RADIO IF FAILURE          
       153        163        584  B13H RADIO IF FAILURE          
       153        163        584  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        585  B13H RADIO IF FAILURE          
       153        163        586  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        587  B13H RADIO IF FAILURE          
       153        163        588  B13H RADIO IF FAILURE          
       153        163        589  B13H RADIO IF FAILURE          
       153        163        589  B13H RADIO IF FAILURE          
       153        163        590  B13H RADIO IF FAILURE          
       153        163        591  B13H RADIO IF FAILURE          
       153        163        592  B13H RADIO IF FAILURE          
       153        163        592  B13H RADIO IF FAILURE          
       153        163        593  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        594  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        595  B13H RADIO IF FAILURE          
       153        163        596  B13H RADIO IF FAILURE          
       153        163        596  B13H RADIO IF FAILURE          
       153        163        597  B13H RADIO IF FAILURE          
       153        163        597  B13H RADIO IF FAILURE          
       153        163        597  B13H RADIO IF FAILURE          
       153        163        597  B13H RADIO IF FAILURE          
       153        163        597  B13H RADIO IF FAILURE          
       154        163        598  B13H RADIO IF FAILURE          
       154        163        598  B13H RADIO IF FAILURE          
       154        163        598  B13H RADIO IF FAILURE          
       154        163        598  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        599  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        601  B13H RADIO IF FAILURE          
       154        163        602  B13H RADIO IF FAILURE          
       154        163        602  B13H RADIO IF FAILURE          
       154        163        602  B13H RADIO IF FAILURE          
       154        163        602  B13H RADIO IF FAILURE          
       154        163        602  B13H RADIO IF FAILURE          
       154        163        602  B13H RADIO IF FAILURE          
MSSARA02: Disconnected
