Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Single_Traficability_Observacion.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Observation_Reports\oMSS_Clear_Code_Traficability_Observation\oMSS_CC_Single_Traficability_Observacion.tel', line 2 
   Variable 'CLEAR_CODE' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Connected
MSSARA02: Connected
INICIO DE MACRO PARA MSSARA02: 2023-11-24  10:38:46
ERRORRRRRRERRORRRRRRERRORRRRRRERRORRRRRRERRORRRRRRERRORRRRRRERRORRRRRRERRORRRRRRMissing or incomplete echo
MSSARA02: Disconnected
