Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\35_oMSS_rnc_amr_mode_sets\oMSS_rnc_amr_mode_sets.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\35_oMSS_rnc_amr_mode_sets\oMSS_rnc_amr_mode_sets.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
#####################
# rnc_amr_mode_sets #
#####################
FIN!!!!