Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\8_oMSS_ss7_own_signaling_point_code\oMSS_ss7_own_signaling_point_code.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
ss7_own_signaling_point_code
################################
# ss7_own_signaling_point_code #
################################
NA0    07A7/01959        MSVE2             STP   ITU-T    1    14  OWN SP
NA1    07A7/01959        MSVE2             STP   ITU-T    1    14  OWN SP
FIN!!!!