Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\94_oMSS_isup_screening_mask\oMSS_isup_screening_mask.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\94_oMSS_isup_screening_mask\oMSS_isup_screening_mask.tel', line 2 
   Variable 'temp' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
########################
# _isup_screening_mask #
########################
1 LSI: IU064
2 LSI: IU164
3 LSI: IU264
4 LSI: IU364
5 LSI: IU464
6 LSI: IU564
7 LSI: IU664
8 LSI: IU764
9 LSI: IU864
10 LSI: IU964
##########################
# IU064 MESSAGE SETTINGS #
##########################
############################
# IU064 PARAMETER SETTINGS #
############################
##########################
# IU164 MESSAGE SETTINGS #
##########################
############################
# IU164 PARAMETER SETTINGS #
############################
##########################
# IU264 MESSAGE SETTINGS #
##########################
############################
# IU264 PARAMETER SETTINGS #
############################
##########################
# IU364 MESSAGE SETTINGS #
##########################
############################
# IU364 PARAMETER SETTINGS #
############################
##########################
# IU464 MESSAGE SETTINGS #
##########################
############################
# IU464 PARAMETER SETTINGS #
############################
##########################
# IU564 MESSAGE SETTINGS #
##########################
############################
# IU564 PARAMETER SETTINGS #
############################
##########################
# IU664 MESSAGE SETTINGS #
##########################
############################
# IU664 PARAMETER SETTINGS #
############################
##########################
# IU764 MESSAGE SETTINGS #
##########################
############################
# IU764 PARAMETER SETTINGS #
############################
##########################
# IU864 MESSAGE SETTINGS #
##########################
############################
# IU864 PARAMETER SETTINGS #
############################
##########################
# IU964 MESSAGE SETTINGS #
##########################
############################
# IU964 PARAMETER SETTINGS #
############################
FIN!!!!