Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\40_oMSS_a_interf_attrib_subanalysis_mtc\oMSS_a_interf_attrib_subanalysis_mtc.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\40_oMSS_a_interf_attrib_subanalysis_mtc\oMSS_a_interf_attrib_subanalysis_mtc.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\40_oMSS_a_interf_attrib_subanalysis_mtc\oMSS_a_interf_attrib_subanalysis_mtc.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\40_oMSS_a_interf_attrib_subanalysis_mtc\oMSS_a_interf_attrib_subanalysis_mtc.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
###################################
# a_interf_attrib_subanalysis_mtc #
###################################
FIN!!!!