Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\102_oMSS_routing_attribute_subanalysis\oMSS_routing_attribute_subanalysis.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\102_oMSS_routing_attribute_subanalysis\oMSS_routing_attribute_subanalysis.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\102_oMSS_routing_attribute_subanalysis\oMSS_routing_attribute_subanalysis.tel', line 2 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\102_oMSS_routing_attribute_subanalysis\oMSS_routing_attribute_subanalysis.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\102_oMSS_routing_attribute_subanalysis\oMSS_routing_attribute_subanalysis.tel', line 3 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\102_oMSS_routing_attribute_subanalysis\oMSS_routing_attribute_subanalysis.tel', line 3 
   Variable 'z' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
#################################
# routing_attribute_subanalysis #
#################################
FIN!!!!