Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\12_oMSS_msc_specific_number_range\oMSS_msc_specific_number_range.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
msc_specific_number_range
#############################
# msc_specific_number_range #
#############################
FIN!!!!