Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\46_oMSS_ss7_signalling_route_sets\oMSS_ss7_signalling_route_sets.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\46_oMSS_ss7_signalling_route_sets\oMSS_ss7_signalling_route_sets.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\46_oMSS_ss7_signalling_route_sets\oMSS_ss7_signalling_route_sets.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
#############################
# ss7_signalling_route_sets #
#############################
1*- NA0    03C5/00965        MS2ME               AV        6
2*- NA0    03C8/00968        MS3ME               AV        6
3*- NA0    03E2/00994        MS5ME               AV        6
4*- NA0    03EA/01002        MSMG2               AV        6
5*- NA0    03EC/01004        MSMG1               AV        6
6*- NA0    06A0/01696        MSAR1               AV        6
7*- NA0    06A3/01699        MSVE1               AV        6
8*- NA0    0709/01801        MS5VE               AV        6
9*- NA0    070C/01804        STPVE               AV        6
10*- NA0    0727/01831        MSTR1               AV        6
11*- NA0    072B/01835        MS6VE               AV        6
12*- NA0    072C/01836        MS7VE               AV        6
13*- NA0    072F/01839        MSTR2               AV        6
14*- NA0    0761/01889        MS3PR               AV        6
15*- NA0    0791/01937        MS4VE               AV        6
16*- NA0    0794/01940        MS3VE               AV        6
17*- NA0    0796/01942        MS2VE               AV        6
18*- NA0    07AF/01967        MS5AR               AV        6
19*- NA0    07B4/01972        MS6AR               AV        6
20*- NA0    07B7/01975        MGVE4               AV        6
21*- NA0    07B9/01977        MS7AR               AV        6
22*- NA0    07BB/01979        MS1TO               AV        6
23*- NA0    07BE/01982        MS2TO               AV        6
24*- NA0    07C8/01992        MSTR3               AV        6
25*- NA0    07DE/02014        MS3AR               AV        6
26*- NA0    07E1/02017        MS4AR               AV        6
27*- NA0    082D/02093        MSIN1               AV        6
28*- NA0    099A/02458        MSIN2               AV        6
29*- NA0    0BC7/03015        MS2CL               AV        6
30*- NA0    0BCA/03018        MS3CL               AV        6
31*- NA0    0BE7/03047        MS4CL               AV        6
32*- NA0    0BEA/03050        MS1IN               AV        6
33*- NA0    1551/05457        MS1SI               AV        6
34*- NA0    17B2/06066        MSAK1               AV        6
35*- NA0    17C1/06081        MS3BA               AV        6
36*- NA0    17C3/06083        MSAK2               AV        6
37*- NA0    17DE/06110        MS1CA               AV        6
38*- NA0    17ED/06125        MS2AK               AV        6
39*- NA0    1BC4/07108        MS1PE               AV        6
40*- NA0    1BC6/07110        MS2PE               AV        6
41*- NA0    1BCE/07118        MSPE1               AV        6
42*- NA0    1FCD/08141        MS2BU               AV        6
43*- NA0    1FD3/08147        STPBU               AV        6
44*- NA0    1FD6/08150        MSBU1               AV        6
45*- NA0    3C4A/15434        MSMA1               AV        6
46*- NA0    3F1A/16154        CPCOS               AV        6
47*- NA0    3F29/16169        CPCOR               AV        6
48*- NA0    3FAA/16298        CPCOC               AV        6
49*- NA1    07B7/01975        MGVE4               AV        6
50*- NA1    3F28/16168        RVE09               AV        6
FIN!!!!