Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\50_oMSS_sccp_subsystems\oMSS_sccp_subsystems.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
###################
# sccp_subsystems #
###################
NA1 SPNAME MSVE2 SPC 07A7
NA1 SPNAME BTO11 SPC 3DB5
NA1 SPNAME RVE09 SPC 3F28
MSVE2: NA1,07A7:A;
                                   01/001  SCMG    AV-EX       N*
                                   07/007  MAPV    AV-EX     0 Y*
                                   08/008  MAPM    AV-EX     0 Y*
                                   8E/142  RANAP   AV-EX     1 Y*
                                   FE/254  BSSAP   AV-EX     1 Y*
BTO11: NA1,3DB5:A;
                                   01/001  SCMG    UA-INS      N*
                                   FE/254  BSSAP   UA-INS    1 Y*
RVE09: NA1,3F28:A;
                                   01/001  SCMG    AV-EX       N 
                                   8E/142  RANAP   AV-EX     0 Y 
NA0 SPNAME STPVE SPC 070C
NA0 SPNAME MSVE2 SPC 07A7
NA0 SPNAME STPBU SPC 1FD3
NA0 SPNAME CPCOS SPC 3F1A
NA0 SPNAME CPCOR SPC 3F29
NA0 SPNAME CPCOC SPC 3FAA
STPVE: NA0,070C:A;
                                   01/001  SCMG    AV-EX       N*
MSVE2: NA0,07A7:A;
                                   01/001  SCMG    AV-EX       N*
                                   07/007  MAPV    AV-EX     0 Y*
                                   08/008  MAPM    AV-EX     0 Y*
                                   8E/142  RANAP   AV-EX     1 Y*
                                   92/146  CAP     AV-EX     0 Y*
                                   93/147  CAPMP   AV-EX     0 N*
                                   C0/192  BSSGS   AV-EX     0 Y*
                                   FE/254  BSSAP   AV-EX     1 Y*
STPBU: NA0,1FD3:A;
                                   01/001  SCMG    AV-EX       N*
CPCOS: NA0,3F1A:A;
                                   01/001  SCMG    AV-EX       N*
CPCOR: NA0,3F29:A;
                                   01/001  SCMG    AV-EX       N*
                                   91/145  GMLC    AV-EX     0 Y*
CPCOC: NA0,3FAA:A;
                                   01/001  SCMG    AV-EX       N*
FIN!!!!