Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\81_oMSS_user_plane_analysis_final_res\oMSS_user_plane_analysis_final_res.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Already connected
############
# MSSARA02 #
############
#################################
# user_plane_analysis_final_res #
#################################
FIN!!!!