Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\RAN-UTRAN\3G\oMSS_3G_RNC_NODEB_CHECK\oMSS_CHECK_3G_RNC_STATUS_NODEB.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSARA02: Already connected

############
# MSSARA02 #
############

#########################
# ASSOCIATIONS SET NAME #
#########################
MGAR4NA0                          0   M3UA        CLIENT
MGAR4NA1                          1   M3UA        CLIENT
STPVE                             2   M3UA        CLIENT
STPBU                             3   M3UA        CLIENT
BTO11                             4   M3UA        SERVER
RVE09                             5   M3UA        SERVER
RAR02                             6   M3UA        SERVER


######################
# ASSOCIATIONS STATE #
######################
      0    IPDU-3    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.1                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.1                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.161/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.177/28                            
      1    IPDU-4    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.2                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.2                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.162/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.178/28                            
      2    IPDU-5    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.3                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.3                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.163/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.179/28                            
      3    IPDU-6    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.4                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.4                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.164/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.180/28                            
      4    IPDU-7    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.5                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.5                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.165/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.181/28                            
      5    IPDU-8    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.6                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.6                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.166/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.182/28                            
      6    IPDU-9    ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.7                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.7                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.167/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.183/28                            
      7    IPDU-10   ---     SIGTRAN          DOWN-BY-USER        
        SOURCE ADDRESS 1 . . . . . : 10.40.172.8                                
        SOURCE ADDRESS 2 . . . . . : 10.41.172.8                                
        PRIMARY DEST. ADDRESS  . . : 10.63.62.168/28                            
        SECONDARY DEST. ADDRESS  . : 10.63.62.184/28                            

*1/8- ASSC_NAME: RAR02 ID: 0 UNIT IPDU-3 OPIP 10.40.172.1 OSIP 10.41.172.1 DOPIP 10.63.62.161 DOSIP 10.63.62.177
 -->> # PING PRIMARY OPIP 10.40.172.1 OSIP 10.63.62.161 OK
 -->> # PING SECONDARY OPIP 10.41.172.1 OSIP 10.63.62.177 OK

*2/8- ASSC_NAME: RAR02 ID: 1 UNIT IPDU-4 OPIP 10.40.172.2 OSIP 10.41.172.2 DOPIP 10.63.62.162 DOSIP 10.63.62.178
 -->> # PING PRIMARY OPIP 10.40.172.2 OSIP 10.63.62.162 OK
 -->> # PING SECONDARY OPIP 10.41.172.2 OSIP 10.63.62.178 OK

*3/8- ASSC_NAME: RAR02 ID: 2 UNIT IPDU-5 OPIP 10.40.172.3 OSIP 10.41.172.3 DOPIP 10.63.62.163 DOSIP 10.63.62.179
 -->> # PING PRIMARY OPIP 10.40.172.3 OSIP 10.63.62.163 OK
 -->> # PING SECONDARY OPIP 10.41.172.3 OSIP 10.63.62.179 OK

*4/8- ASSC_NAME: RAR02 ID: 3 UNIT IPDU-6 OPIP 10.40.172.4 OSIP 10.41.172.4 DOPIP 10.63.62.164 DOSIP 10.63.62.180
 -->> # PING PRIMARY OPIP 10.40.172.4 OSIP 10.63.62.164 OK
 -->> # PING SECONDARY OPIP 10.41.172.4 OSIP 10.63.62.180 OK

*5/8- ASSC_NAME: RAR02 ID: 4 UNIT IPDU-7 OPIP 10.40.172.5 OSIP 10.41.172.5 DOPIP 10.63.62.165 DOSIP 10.63.62.181
 -->> # PING PRIMARY OPIP 10.40.172.5 OSIP 10.63.62.165 OK
 -->> # PING SECONDARY OPIP 10.41.172.5 OSIP 10.63.62.181 OK

*6/8- ASSC_NAME: RAR02 ID: 5 UNIT IPDU-8 OPIP 10.40.172.6 OSIP 10.41.172.6 DOPIP 10.63.62.166 DOSIP 10.63.62.182
 -->> # PING PRIMARY OPIP 10.40.172.6 OSIP 10.63.62.166 OK
 -->> # PING SECONDARY OPIP 10.41.172.6 OSIP 10.63.62.182 OK

*7/8- ASSC_NAME: RAR02 ID: 6 UNIT IPDU-9 OPIP 10.40.172.7 OSIP 10.41.172.7 DOPIP 10.63.62.167 DOSIP 10.63.62.183
 -->> # PING PRIMARY OPIP 10.40.172.7 OSIP 10.63.62.167 OK
 -->> # PING SECONDARY OPIP 10.41.172.7 OSIP 10.63.62.183 OK

*8/8- ASSC_NAME: RAR02 ID: 7 UNIT IPDU-10 OPIP 10.40.172.8 OSIP 10.41.172.8 DOPIP 10.63.62.168 DOSIP 10.63.62.184
 -->> # PING PRIMARY OPIP 10.40.172.8 OSIP 10.63.62.168 OK
 -->> # PING SECONDARY OPIP 10.41.172.8 OSIP 10.63.62.184 OK


############################
# SIGNALLING LINK SET DATA #
############################
ZNSI:NA1,3EFF;

LOADING PROGRAM VERSION 8.19-0

MSS       MSSARA02                  2023-11-21  23:56:43

INTERROGATING SIGNALLING LINK SET DATA

                                                                   LS    IP
NET SP CODE H/D        LINK SET              ASSOCIATION SET       STATE LINK
--- ------------------ --------------------- --------------------- ----- ----
NA1   3EFF/16127         44 RAR02               6 RAR02             UA      4
                                       LINK TEST NOT ALLOWED


COMMAND EXECUTED


SIGNALLING LINK SET DATA HANDLING COMMAND <NS_>
<  

#############################
# SIGNALLING LINK SET STATE #
#############################
ZNLI;

LOADING PROGRAM VERSION 8.8-0

MSS       MSSARA02                  2023-11-21  23:56:44

SIGNALLING LINK STATES

M3UA BASED LINKS
================
 M3UA                            ASSOCIATION  LINK
 LINK      LINK SET              SET          STATE
 ----      -------------------   ----------   -----
    0      16 MGAR4                 0         AV-EX     
    1      17 MGAR4                 1         AV-EX     
    2      18 STPVE                 2         AV-EX     
    3      19 STPBU                 3         AV-EX     
    4      44 RAR02                 6         UA-AD     
   63      36 RVE09                 5         AV-EX     
   64      34 BTO11                 4         UA-AD     

COMMAND EXECUTED


SIGNALLING LINK STATE HANDLING COMMAND <NL_>
<  ZNEL;

LOADING PROGRAM VERSION 8.49-0

MSS       MSSARA02                  2023-11-21  23:56:44

SIGNALLING LINK STATES

M3UA BASED LINKS
================
 M3UA                          ASSOCIATION  LINK
 LINK  LINK SET                SET          STATE
 ====  =====================   ===========  ======
    0    16 MGAR4                0          AV-EX     
    1    17 MGAR4                1          AV-EX     
    2    18 STPVE                2          AV-EX     
    3    19 STPBU                3          AV-EX     
    4    44 RAR02                6          UA-AD     
   63    36 RVE09                5          AV-EX     
   64    34 BTO11                4          UA-AD     

COMMAND EXECUTED


SIGNALLING NETWORK STATE INTERROGATION COMMAND <NE_>
<  

#########################
# SIGNALLING POINT DATA #
#########################
ZNRI:NA1,3EFF;

LOADING PROGRAM VERSION 8.38-0

MSS       MSSARA02                  2023-11-21  23:56:45

INTERROGATING SIGNALLING POINT DATA

NET  SP CODE H/D         NAME              RS STATE  PAR SET
---  ------------------  ----------------  --------  -------
NA1    3EFF/16127        RAR02               UA        6
LOAD SHARING BETWEEN SIGNALLING ROUTES DENIED
SCREENING GROUPS: AASG 0, ADSG 0, OOSG 0, ODSG 0

ROUTES: SP CODE H/D         NAME              STATE   PRIO
        ------------------  ----------------  ------  ----
          3EFF/16127        RAR02             UA-AD     7    



COMMAND EXECUTED


SIGNALLING ROUTE SET DATA HANDLING COMMAND <NR_>
<  

##########################
# SIGNALLING ROUTE STATE #
##########################
ZNVI:NA1,3EFF;

LOADING PROGRAM VERSION 8.2-0

MSS       MSSARA02                  2023-11-21  23:56:46

SIGNALLING ROUTE STATES

DESTINATION:           SP               RS     ROUTES:            
NET SP CODE H/D        NAME             STATE  SP CODE H/D        STATE   PRIO
--- ------------------ ---------------- -----  ------------------ ------- ----
NA1   3EFF/16127       RAR02             UA      3EFF/16127        UA-AD   7

COMMAND EXECUTED


SIGNALLING ROUTE STATE HANDLING COMMAND <NV_>
<  

##################################
# SCCP DATA OF SIGNALLING POINTS #
##################################
ZNFI:NA1,3EFF:A;

LOADING PROGRAM VERSION 8.8-0

MSS       MSSARA02                  2023-11-21  23:56:47

SCCP STATES

DESTINATION:           SP                    
NET SP CODE H/D        NAME             ST RM
--- ------------------ ---------------- -- --
NA1   3EFF/16127       RAR02            UA - 

           ROUTING:               SP                       PAR
           NET SP CODE H/D        NAME             STATE   SET
           --- ------------------ ---------------- ------- ---
           NA1   3EFF/16127       RAR02            UA-INU    3 

                                                           PAR    
                      SUBSYSTEMS:  NO H/D  SS NAME STATE   SET SST
                      ===========  ------- ------- ------- --- ---
                                   01/001  SCMG    UA-INS      N 
                                   8E/142  RANAP   UA-INU    1 Y 


COMMAND EXECUTED


SCCP DATA HANDLING COMMAND <NF_>
<  ZNGI:NA1,3EFF:A;

LOADING PROGRAM VERSION 7.10-0

MSS       MSSARA02                  2023-11-21  23:56:47

SCCP STATES

DESTINATION:             SP            
NET  SP CODE H/D         NAME             STATE RM
---  ------------------  ---------------- ----- --
NA1    3EFF/16127        RAR02             UA   - 
          
          ROUTING:                 SP             
          NET  SP CODE H/D         NAME             STATE    
          ---  ------------------  ---------------- -------  
          NA1    3EFF/16127        RAR02            UA-INU 

                      SUBSYSTEMS:  NO H/D   SS NAME  STATE
                      ===========  -------  -------  -------
                                   01/001   SCMG     UA-INS 
                                   8E/142   RANAP    UA-INU 


COMMAND EXECUTED


SCCP STATE HANDLING COMMAND <NG_>
<  ZNHI:NA1,3EFF:;

LOADING PROGRAM VERSION 7.7-0

MSS       MSSARA02                  2023-11-21  23:56:48

SUBSYSTEM STATES

NETWORK: NA1   POINT H/D:   3EFF/16127          SP NAME: RAR02           
============   =============================    =========================
DESTINATION:                ROUTING:                 SP
NO H/D  SS NAME  STATE  RM  NET  SP CODE H/D         NAME              STATE
------  -------  -----  --  ---  ------------------  ----------------  -------
01/001  SCMG      UA    -   NA1    3EFF/16127        RAR02             UA-INS 

8E/142  RANAP     UA    -   NA1    3EFF/16127        RAR02             UA-INU 


COMMAND EXECUTED


SCCP SUBSYSTEM STATE HANDLING COMMAND <NH_>
<  

#########################
# RADIO - Location Area #
#########################
LA    NAME :AUXLACDEF                   LAC     :65533
LA    NAME :LAC013104                   LAC     :13104
LA    NAME :LAC0538                     LAC     :00538
LA    NAME :LAC9902                     LAC     :09902
LA    NAME :LAC09601                    LAC     :09601
LA    NAME :LACC9602                    LAC     :09602
LA    NAME :LAC13620                    LAC     :13620
LA    NAME :LAC13642                    LAC     :13642

#######
# UPD #
#######
ZJFL;

LOADING PROGRAM VERSION 10.34-0

NAME             ID   BNCC
----             --   ----
UPDMGWALLIPV4   0000  IPV4
UPDIP4RNC02ARA  0001  IPV4
UPDRNC09VEN     0300  IPV4
UPDMCBSC11TOB   0301  IPV4

COMMAND EXECUTED


USER PLANE TOPOLOGY DATA HANDLING COMMAND <JF_>
<  