Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\22_oMSS_charging_day_classes\oMSS_charging_day_classes.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSVEN02: Connected
MSSVEN02: Connected
############
# MSSVEN02 #
############
########################
# charging_day_classes #
########################
FIN!!!!