Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\96_oMSS_number_modif_formating_set\oMSS_number_modif_formating_set.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\96_oMSS_number_modif_formating_set\oMSS_number_modif_formating_set.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\96_oMSS_number_modif_formating_set\oMSS_number_modif_formating_set.tel', line 2 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\96_oMSS_number_modif_formating_set\oMSS_number_modif_formating_set.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\96_oMSS_number_modif_formating_set\oMSS_number_modif_formating_set.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Connected
MSSARA02: Connected
############
# MSSARA02 #
############
##############################
# number_modif_formating_set #
##############################
FIN!!!!MSSARA02: Disconnected
