Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\55_oMSS_ss7_services\oMSS_ss7_services.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\55_oMSS_ss7_services\oMSS_ss7_services.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\55_oMSS_ss7_services\oMSS_ss7_services.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\55_oMSS_ss7_services\oMSS_ss7_services.tel', line 2 
   Variable 'FLAG' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
################
# ss7_services #
################
00H     IN0        00H       SNM         YES        YES     007FH  006DH 
01H     IN0        01H       SNT         YES        YES     007FH    -   
03H     IN0        03H       SCCP        YES        YES     0208H  010FH 
05H     IN0        05H       ISUP        YES        YES     01CAH    -   CIC-12
40H     IN1        00H       SNM         YES        YES     007FH  006DH 
41H     IN1        01H       SNT         YES        YES     007FH    -   
42H     IN1        02H       SNTA        YES        YES     007FH    -   
43H     IN1        03H       SCCP        YES        YES     0208H  010FH 
45H     IN1        05H       ISUP        YES        YES     01CAH    -   CIC-12
80H     NA0        00H       SNM         YES        YES     007FH  006DH 
81H     NA0        01H       SNT         YES        YES     007FH    -   
82H     NA0        02H       SNTT1       YES        YES     007FH    -   
83H     NA0        03H       SCCP        YES        YES     0208H  010FH 
85H     NA0        05H       ISUP        YES        YES     01CAH    -   CIC-12
8CH     NA0        0CH       AAL2        YES        YES     0452H    -   
8DH     NA0        0DH       BICC        YES        YES     05C9H    -   
C0H     NA1        00H       SNM         YES        YES     007FH  006DH 
C1H     NA1        01H       SNT         YES        YES     007FH    -   
C2H     NA1        02H       SNTT1       YES        YES     007FH    -   
C3H     NA1        03H       SCCP        YES        YES     0208H  010FH 
C5H     NA1        05H       ISUP        YES        YES     01CAH    -   CIC-12
CCH     NA1        0CH       AAL2        YES        YES     0452H    -   
CDH     NA1        0DH       BICC        YES        YES     05C9H    -   

Existen 23 tuplas insertadas

FIN!!!!