Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\77_oMSS_mgw_interconnection\oMSS_mgw_interconnection_.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\77_oMSS_mgw_interconnection\oMSS_mgw_interconnection_.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\77_oMSS_mgw_interconnection\oMSS_mgw_interconnection_.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\77_oMSS_mgw_interconnection\oMSS_mgw_interconnection_.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
#######################
# mgw_interconnection #
#######################
FIN!!!!