Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\82_oMSS_user_plane_subanalysis\oMSS_user_plane_subanalysis.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSARA02: Already connected
############
# MSSARA02 #
############
##########################
# user_plane_subanalysis #
##########################
1 UPD Subanalysis: PUPSIANA
2 UPD Subanalysis: SBPSIANA
3 UPD Subanalysis: CMPSIANA
4 UPD Subanalysis: SUSSIANA
5 UPD Subanalysis: SASBNANA
6 UPD Subanalysis: ICSBNANA
FIN!!!!