Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\76_oMSS_upd_creation\oMSS_upd_creation_.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MSSING02: Already connected
############
# MSSING02 #
############
################
# upd_creation #
################
Existen 3 UPD
UPDMGWALLIPV4 000 BOTH BOTH IPV4
UPDRNC09VEN 300 BOTH BOTH IPV4
UPDMCBSC11TOB 301 BOTH BOTH IPV4
FIN!!!!