Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\104_oMSS_traffica_and_simo\oMSS_traffica_and_simo.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\104_oMSS_traffica_and_simo\oMSS_traffica_and_simo.tel', line 2 
   Variable 'TEMP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\104_oMSS_traffica_and_simo\oMSS_traffica_and_simo.tel', line 2 
   Variable 'temp' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\104_oMSS_traffica_and_simo\oMSS_traffica_and_simo.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\104_oMSS_traffica_and_simo\oMSS_traffica_and_simo.tel', line 3 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\104_oMSS_traffica_and_simo\oMSS_traffica_and_simo.tel', line 3 
   Variable 'z' declared but its value is never used
Code generation...

Got no compile errors.

MSSARA02: Connected
MSSARA02: Connected
############
# MSSARA02 #
############
#####################
# traffica_and_simo #
#####################
FIN!!!!MSSARA02: Disconnected
