Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\4_oMSS_tcp_ip_policy_route\oMSS_tcp_ip_policy_route.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\4_oMSS_tcp_ip_policy_route\oMSS_tcp_ip_policy_route.tel', line 2 
   Variable 'UNIT' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\4_oMSS_tcp_ip_policy_route\oMSS_tcp_ip_policy_route.tel', line 3 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\4_oMSS_tcp_ip_policy_route\oMSS_tcp_ip_policy_route.tel', line 3 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
MSSING02: Disconnected
############
# MSSVEN02 #
############
tcp_ip_policy_route
#######################
# tcp_ip_policy_route #
#######################
FIN!!!!