Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 2 
   Variable 'line3' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 3 
   Variable 'filter' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 3 
   Variable 'file' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 4 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 4 
   Variable 'y' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 4 
   Variable 'm1' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 4 
   Variable 'm2' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 4 
   Variable 'file_handle' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Subanalisys_State\oMSS_Subanalisys_State.tel', line 4 
   Variable 'cuenta' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
SUBANALYSIS NAME        : EMERCALL
SUBANALYSIS NAME        : MTCPRIO
SUBANALYSIS NAME        : CAUSECK
SUBANALYSIS NAME        : AIMSICK
SUBANALYSIS NAME        : CBTYPECK
SUBANALYSIS NAME        : TDPANA
FIN!!!!