Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_Users_definition\oMSS_Users_definition.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.


############
# MSS01ING #
############
ACCESING 1/48: MSS01ING
MSS01ING: Connected
MSS01ING: Connected
Acceso Comprobado a MSS: MSS01ING
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS01ING: Closing..
MSS01ING: Disconnected


############
# MSS01PER #
############
ACCESING 2/48: MSS01PER
MSS01PER: Connected
MSS01PER: Connected
Acceso Comprobado a MSS: MSS01PER
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS01PER: Closing..
MSS01PER: Disconnected


############
# MSS01SIN #
############
ACCESING 3/48: MSS01SIN
MSS01SIN: Connected
MSS01SIN: Connected
Acceso Comprobado a MSS: MSS01SIN
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS01SIN: Closing..
MSS01SIN: Disconnected


############
# MSS01TOB #
############
ACCESING 4/48: MSS01TOB
MSS01TOB: Connected
MSS01TOB: Connected
Acceso Comprobado a MSS: MSS01TOB
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS01TOB: Closing..
MSS01TOB: Disconnected


############
# MSS02ALK #
############
ACCESING 5/48: MSS02ALK
MSS02ALK: Connected
MSS02ALK: Connected
Acceso Comprobado a MSS: MSS02ALK
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS02ALK: Closing..
MSS02ALK: Disconnected


############
# MSS02BUC #
############
ACCESING 6/48: MSS02BUC
MSS02BUC: Connected
MSS02BUC: Connected
Acceso Comprobado a MSS: MSS02BUC
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS02BUC: Closing..
MSS02BUC: Disconnected


############
# MSS02CAL #
############
ACCESING 7/48: MSS02CAL
MSS02CAL: Connected
MSS02CAL: Connected
Acceso Comprobado a MSS: MSS02CAL
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS02CAL: Closing..
MSS02CAL: Disconnected


############
# MSS02MED #
############
ACCESING 8/48: MSS02MED
MSS02MED: Connected
MSS02MED: Connected
Acceso Comprobado a MSS: MSS02MED
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS02MED: Closing..
MSS02MED: Disconnected


############
# MSS02PER #
############
ACCESING 9/48: MSS02PER
MSS02PER: Connected
MSS02PER: Connected
Acceso Comprobado a MSS: MSS02PER
USER_ID: NKFNAB -- PASSWORD VALIDITY TIME LEFT:  27 DAY(S)
MSS02PER: Closing..
MSS02PER: Disconnected


############
# MSS02SIN #
############
ACCESING 10/48: MSS02SIN
MSS02SIN: Connected
Closing all connections
MSS02SIN: Disconnected
MSS02SIN: Disconnected
Sin acceso a MSS: MSS02SIN


############
# MSS02TOB #
############
ACCESING 11/48: MSS02TOB
MSS02TOB: Connected
MSS02TOB: Disconnected
