Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\53_oMSS_ip_signalling_link_sets\oMSS_ip_signalling_link_sets.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\53_oMSS_ip_signalling_link_sets\oMSS_ip_signalling_link_sets.tel', line 2 
   Variable 'IND' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMSS\oMSS_AUDITORIA\53_oMSS_ip_signalling_link_sets\oMSS_ip_signalling_link_sets.tel', line 2 
   Variable 'FLAG' declared but its value is never used
Code generation...

Got no compile errors.

MSSVEN02: Already connected
############
# MSSVEN02 #
############
###########################
# ip_signalling_link_sets #
###########################
*1/6*- ASSOC SET MGVE4NA0
*2/6*- ASSOC SET MGVE4NA1
*3/6*- ASSOC SET STPVE
*4/6*- ASSOC SET STPBU
*5/6*- ASSOC SET RVE09
*6/6*- ASSOC SET BTO11
*1/6*- ASSOC SET MGVE4NA0
      0    IPDU-9          4 SIGTRAN          ASP-ACTIVE          
      1    IPDU-6          4 SIGTRAN          ASP-ACTIVE          
      2    IPDU-3          4 SIGTRAN          ASP-ACTIVE          
      3    IPDU-7          4 SIGTRAN          ASP-ACTIVE          
      4    IPDU-4          4 SIGTRAN          ASP-ACTIVE          
      5    IPDU-5          4 SIGTRAN          ASP-ACTIVE          
      6    IPDU-11         4 SIGTRAN          ASP-ACTIVE          
      7    IPDU-8          4 SIGTRAN          ASP-ACTIVE          
*2/6*- ASSOC SET MGVE4NA1
      0    IPDU-9          3 SIGTRAN          ASP-ACTIVE          
      1    IPDU-6          3 SIGTRAN          ASP-ACTIVE          
      2    IPDU-3          3 SIGTRAN          ASP-ACTIVE          
      3    IPDU-7          3 SIGTRAN          ASP-ACTIVE          
      4    IPDU-4          3 SIGTRAN          ASP-ACTIVE          
      5    IPDU-5          3 SIGTRAN          ASP-ACTIVE          
      6    IPDU-11         3 SIGTRAN          ASP-ACTIVE          
      7    IPDU-8          3 SIGTRAN          ASP-ACTIVE          
*3/6*- ASSOC SET STPVE
      0    IPDU-9          2 SIGTRANSTP       ASP-ACTIVE          
      1    IPDU-6          2 SIGTRANSTP       ASP-ACTIVE          
      2    IPDU-3          2 SIGTRANSTP       ASP-ACTIVE          
      3    IPDU-7          2 SIGTRANSTP       ASP-ACTIVE          
      4    IPDU-4          2 SIGTRANSTP       ASP-ACTIVE          
      5    IPDU-5          2 SIGTRANSTP       ASP-ACTIVE          
      6    IPDU-11         2 SIGTRANSTP       ASP-ACTIVE          
      7    IPDU-8          2 SIGTRANSTP       ASP-ACTIVE          
*4/6*- ASSOC SET STPBU
      0    IPDU-9         11 SIGTRANSTP       ASP-ACTIVE          
      1    IPDU-6         14 SIGTRANSTP       ASP-ACTIVE          
      2    IPDU-3          7 SIGTRANSTP       ASP-ACTIVE          
      3    IPDU-7          5 SIGTRANSTP       ASP-ACTIVE          
      4    IPDU-4          6 SIGTRANSTP       ASP-ACTIVE          
      5    IPDU-5          5 SIGTRANSTP       ASP-ACTIVE          
      6    IPDU-11         8 SIGTRANSTP       ASP-ACTIVE          
      7    IPDU-8          8 SIGTRANSTP       ASP-ACTIVE          
*5/6*- ASSOC SET RVE09
      0    IPDU-9         10 SIGTRAN          ASP-ACTIVE          
      1    IPDU-6          9 SIGTRAN          ASP-ACTIVE          
*6/6*- ASSOC SET BTO11
      0    IPDU-9    ---     SIGTRAN          SCTP-DOWN           
      1    IPDU-6    ---     SIGTRAN          SCTP-DOWN           
*1/48*- SGsAP MME01VEN01
*2/48*- SGsAP MME01VEN02
*3/48*- SGsAP MME01VEN03
*4/48*- SGsAP MME01VEN04
*5/48*- SGsAP MME01ING01
*6/48*- SGsAP MME01ING02
*7/48*- SGsAP MME01ING03
*8/48*- SGsAP MME01ING04
*9/48*- SGsAP MME01ALK01
*10/48*- SGsAP MME01ALK02
*11/48*- SGsAP MME01ALK03
*12/48*- SGsAP MME01ALK04
*13/48*- SGsAP MME01SIN01
*14/48*- SGsAP MME01SIN02
*15/48*- SGsAP MME01SIN03
*16/48*- SGsAP MME01SIN04
*17/48*- SGsAP MME01MEG01
*18/48*- SGsAP MME01MEG02
*19/48*- SGsAP MME01MEG03
*20/48*- SGsAP MME01MEG04
*21/48*- SGsAP MME01TRI01
*22/48*- SGsAP MME01TRI02
*23/48*- SGsAP MME01TRI03
*24/48*- SGsAP MME01TRI04
*25/48*- SGsAP MME01ARA01
*26/48*- SGsAP MME01ARA02
*27/48*- SGsAP MME01ARA03
*28/48*- SGsAP MME01ARA04
*29/48*- SGsAP MME02TRI01
*30/48*- SGsAP MME02TRI02
*31/48*- SGsAP MME02TRI03
*32/48*- SGsAP MME02TRI04
*33/48*- SGsAP CMM01ALK01
*34/48*- SGsAP CMM01ALK02
*35/48*- SGsAP CMM01ALK03
*36/48*- SGsAP CMM01ALK04
*37/48*- SGsAP CMM03TRI1
*38/48*- SGsAP CMM03TRI2
*39/48*- SGsAP CMM03TRI3
*40/48*- SGsAP CMM03TRI4
*41/48*- SGsAP CMM01VEN01
*42/48*- SGsAP CMM01VEN02
*43/48*- SGsAP CMM01VEN03
*44/48*- SGsAP CMM01VEN04
*45/48*- SGsAP CMM01ARA01
*46/48*- SGsAP CMM01ARA02
*47/48*- SGsAP CMM01ARA03
*48/48*- SGsAP CMM01ARA04
MME01VEN01           0 GISU-60 SGSAP SERVER SGS              ASP-ACTIVE    
MME01VEN02           1 GISU-1  SGSAP SERVER SGS              ASP-ACTIVE    
MME01VEN03           2 GISU-2  SGSAP SERVER SGS              ASP-ACTIVE    
MME01VEN04           3 GISU-3  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ING01           4 GISU-4  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ING02           5 GISU-5  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ING03           6 GISU-6  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ING04           7 GISU-7  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ALK01           8 GISU-8  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ALK02           9 GISU-9  SGSAP SERVER SGS              ASP-ACTIVE    
MME01ALK03          10 GISU-10 SGSAP SERVER SGS              ASP-ACTIVE    
MME01ALK04          11 GISU-11 SGSAP SERVER SGS              ASP-ACTIVE    
MME01SIN01          12 GISU-12 SGSAP SERVER SGS              ASP-ACTIVE    
MME01SIN02          13 GISU-13 SGSAP SERVER SGS              ASP-ACTIVE    
MME01SIN03          14 GISU-14 SGSAP SERVER SGS              ASP-ACTIVE    
MME01SIN04          15 GISU-15 SGSAP SERVER SGS              ASP-ACTIVE    
MME01MEG01          16 GISU-16 SGSAP SERVER SGS              ASP-ACTIVE    
MME01MEG02          17 GISU-17 SGSAP SERVER SGS              ASP-ACTIVE    
MME01MEG03          18 GISU-18 SGSAP SERVER SGS              ASP-ACTIVE    
MME01MEG04          19 GISU-19 SGSAP SERVER SGS              ASP-ACTIVE    
MME01TRI01          20 GISU-20 SGSAP SERVER SGS              ASP-ACTIVE    
MME01TRI02          21 GISU-21 SGSAP SERVER SGS              ASP-ACTIVE    
MME01TRI03          22 GISU-22 SGSAP SERVER SGS              ASP-ACTIVE    
MME01TRI04          23 GISU-23 SGSAP SERVER SGS              ASP-ACTIVE    
MME01ARA01          24 GISU-24 SGSAP SERVER SGS              ASP-ACTIVE    
MME01ARA02          25 GISU-25 SGSAP SERVER SGS              ASP-ACTIVE    
MME01ARA03          26 GISU-26 SGSAP SERVER SGS              ASP-ACTIVE    
MME01ARA04          27 GISU-27 SGSAP SERVER SGS              ASP-ACTIVE    
MME02TRI01          28 GISU-28 SGSAP SERVER SGS              ASP-ACTIVE    
MME02TRI02          29 GISU-29 SGSAP SERVER SGS              ASP-ACTIVE    
MME02TRI03          30 GISU-30 SGSAP SERVER SGS              ASP-ACTIVE    
MME02TRI04          31 GISU-31 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01ALK01          40 GISU-40 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01ALK02          41 GISU-41 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01ALK03          42 GISU-42 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01ALK04          43 GISU-43 SGSAP SERVER SGS              ASP-ACTIVE    
CMM03TRI1           44 GISU-44 SGSAP SERVER SGS              ASP-ACTIVE    
CMM03TRI2           45 GISU-45 SGSAP SERVER SGS              ASP-ACTIVE    
CMM03TRI3           46 GISU-46 SGSAP SERVER SGS              ASP-ACTIVE    
CMM03TRI4           47 GISU-47 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01VEN01          48 GISU-48 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01VEN02          49 GISU-49 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01VEN03          50 GISU-50 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01VEN04          51 GISU-51 SGSAP SERVER SGS              ASP-ACTIVE    
CMM01ARA01          52 GISU-52 SGSAP SERVER SGS              SCTP-DOWN     
CMM01ARA02          53 GISU-53 SGSAP SERVER SGS              SCTP-DOWN     
CMM01ARA03          54 GISU-54 SGSAP SERVER SGS              SCTP-DOWN     
CMM01ARA04          55 GISU-55 SGSAP SERVER SGS              SCTP-DOWN     
FIN!!!!